# <center> Case - Webmotors <center>

O objetivo deste trabalho é expôr a minha solução para o case da Webmotors apresentado como parte do processo seletivo para Cientista de Dados da GCB Investimentos.

Este notebook está dividido nos seguintes tópicos :

1. **Introdução**


    1.1 Leitura dos Arquivos Disponibilizados
    1.2 Algumas Observações Iniciais
    1.3 Entendendo a Distribuição da Variável Leads
    
2. **Parte 1 - Variação da Quantidade de Leads de acordo com outras Variáveis**


    2.1 cod_marca_veiculo
    2.2 cod_modelo_veiculo
    2.3 uf_cidade
    
3. **Pré-Processamento dos Dados**

    3.1 Tratamento de Valores Ausentes
        3.1.1 vlr_mercado
        3.1.2 flg_ipva_pago
        3.1.3 flg_todas_revisoes_concessionaria
        3.1.4 flg_garantia_fabrica
        3.1.5 flg_adaptado_pcd
        3.1.6 airbag
    3.2 Tratamento de Variáveis Categóricas
        3.2.1 Variáveis que possuem 2 categorias
        3.2.2 Variáveis que possuem mais de 2 Categorias
    3.3 Tratamento de Outliers
        3.3.1 klm_veiculo
        3.3.2 ano_modelo
        3.3.3 vlr_anuncio
        3.3.4 vlr_mercado
    3.4 Feature Scaling
     
        
4. **Desafio Bônus**


    4.1 Seleção das Features com RFECV
    4.2 Validação - Cruzada
    4.3 Gerando Previsões em um Conjunto de Teste
    4.4 Otimização de Hiperparâmetros com GridSearchCV
    4.5 Conclusão
        
5. **Parte 2 - Modelo para determinar se um Anúncio receberá um Lead**


    5.1 Considerações Iniciais
    5.2 Oversampling
    5.3 Medindo a Performance pós Oversampling
    5.4 Feature Selection
    5.5 O que poderia nos levar a conclusões melhores ?

In [1]:
# Algumas importações básicas

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (mean_squared_error , mean_absolute_error , r2_score , accuracy_score , precision_score ,
recall_score , f1_score)
from sklearn.model_selection import cross_val_score , train_test_split , GridSearchCV
from lightgbm import LGBMRegressor , LGBMClassifier
from sklearn.linear_model import LinearRegression , LogisticRegression
from xgboost import XGBRegressor , XGBClassifier
from catboost import CatBoostRegressor , CatBoostClassifier
from sklearn.ensemble import (GradientBoostingRegressor, RandomForestRegressor, AdaBoostRegressor, GradientBoostingClassifier,
RandomForestClassifier, AdaBoostClassifier)
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor , DecisionTreeClassifier
from sklearn.feature_selection import RFECV
from imblearn.over_sampling import RandomOverSampler

# <center> 1. Introdução <center>

## 1.1 Leitura dos Arquivos Disponibilizados

In [2]:
# Lendo o Dicionário de Dados

pd.read_csv("Case 1 - dicionario.csv")

attribute  \
0                         cod_anuncio   
1                         cod_cliente   
2                     cod_tipo_pessoa   
3                          prioridade   
4                               leads   
5                               views   
6                    cliques_telefone   
7                   cod_marca_veiculo   
8                  cod_modelo_veiculo   
9                  cod_versao_veiculo   
10                         ano_modelo   
11                           cep_2dig   
12                          uf_cidade   
13                        vlr_anuncio   
14                          qtd_fotos   
15                         km_veiculo   
16                        vlr_mercado   
17                     flg_unico_dono   
18                     flg_licenciado   
19                      flg_ipva_pago   
20  flg_todas_revisoes_concessionaria   
21  flg_todas_revisoes_agenda_veiculo   
22               flg_garantia_fabrica   
23                       flg_blindado   
24                   flg_aceita_troca   
25                   flg_adaptado_pcd   
26                        combustivel   
27                             cambio   
28                             portas   
29                             alarme   
30                             airbag   
31                           arquente   
32                         bancocouro   
33                           arcondic   
34                                abs   
35                         desembtras   
36                         travaeletr   
37                        vidroseletr   
38                          rodasliga   
39                        sensorchuva   
40                     sensorestacion   

                                          description  
0                                   código do anúncio  
1                                código do anunciante  
2                      tipo de anunciante: PF=1, PJ=2  
3    prioridade do anúncio (1=alta, 2-média, 3-baixa)  
4                         tota de propostas recebidas  
5              quantidade de visualizações no anúncio  
6         quantidade de cliques no telefone anunciado  
7                          código da marca do veículo  
8                            código do modelo veículo  
9                         código da versão do veículo  
10                              ano-modelo do veículo  
11        dois primeiros dígitos do cep do anunciante  
12                          UF e cidade do anunciante  
13                        valor do veículo no anúncio  
14                     quantidade de fotos no anúncio  
15                            Kilometragem do veículo  
16            valor de referência do veículo na praça  
17                            indicador de único dono  
18                  indicador de licenciamento em dia  
19                           indicador de IPVA em dia  
20  indicador realização de todas as revisões na c...  
21  indicador realização de todas as revisões prev...  
22        indicador de veículo em garantia de fábrica  
23                             indicador de blindagem  
24         indicador de que o anunciante aceita troca  
25  indicador de veículo adaptado para pessoa com ...  
26                       especificação de combustível  
27                            especificação de câmbio  
28                                   número de portas  
29                                 presença de alarme  
30                                 presença de airbag  
31                              presença de ar quente  
32                         presença de banco de couro  
33                        presença de ar condicionado  
34                              presença de freio abs  
35                  presença de desembaçador traseiro  
36                       presença de travas elétricas  
37                       presença de vidros elétricos  
38                     presença de rodas de liga-leve  
39                        presença de sensor de chuva  
40       

In [3]:
# Lendo o arquivo que contém os dados, salvando este como um dataframe e exibindo o dataframe

df = pd.read_csv("Case 1 - dados.csv")

df

cod_anuncio  cod_cliente  cod_tipo_pessoa  prioridade  leads  views  \
0                2         7941                2           3      1      0   
1                6         1770                1           3      1      0   
2                8          709                1           3      4      0   
3               13         9708                1           2     12      0   
4               15         1363                1           2      8      0   
...            ...          ...              ...         ...    ...    ...   
48660       195918         3065                2           3      1  34184   
48661       195924        12535                2           3      1  45048   
48662       195930         2284                2           3      1  71020   
48663       195934         2284                2           3      0  82940   
48664       195939         2284                2           3      0  93608   

       cliques_telefone*  cod_marca_veiculo  cod_modelo_veiculo  \
0                      0                 34                 769   
1                      4                  2                 704   
2                     11                 30                1071   
3                     14                 10                2028   
4                     11                 12                 805   
...                  ...                ...                 ...   
48660                  0                280                3365   
48661                  0                  4                1177   
48662                  0                  5                3128   
48663                  0                  2                3323   
48664                  0                 17                3338   

       cod_versao_veiculo  ...  arquente  bancocouro arcondic  abs  \
0                  346932  ...       NaN         NaN      NaN  NaN   
1                  340148  ...         S           N        N    S   
2                  310713  ...         S           N        S    S   
3                  341195  ...         S           S        S    N   
4                  332063  ...         S           S        S    S   
...                   ...  ...       ...         ...      ...  ...   
48660              346359  ...         S           S        S    S   
48661              343882  ...         N           N        N    N   
48662              344252  ...         N           N        N    N   
48663              344421  ...         S           N        S    N   
48664              344532  ...         S           N        S    S   

       desembtras  travaeletr  vidroseletr  rodasliga  sensorchuva  \
0             NaN         NaN          NaN        NaN          NaN   
1               N           S            S          N            N   
2               S           S            S          S            N   
3               N           S            S          S            N   
4               S           S            S          S            N   
...           ...         ...          ...        ...          ...   
48660           S           S            S          S            N   
48661           N           N            N          N            N   
48662           N           N            N          N            N   
48663           S           S            S          S            N   
48664           S           S            S          S            N   

       sensorestacion  
0                 NaN  
1                   N  
2                   N  
3                   N  
4                   N  
...               ...  
48660               S  
48661               N  
48662               N  
48663               N  
48664               N  

[48665 rows x 41 columns]

## 1.2 Algumas Observações Iniciais

In [4]:
# Olhando as 5 primeiras linhas do dataset

df.head()

cod_anuncio  cod_cliente  cod_tipo_pessoa  prioridade  leads  views  \
0            2         7941                2           3      1      0   
1            6         1770                1           3      1      0   
2            8          709                1           3      4      0   
3           13         9708                1           2     12      0   
4           15         1363                1           2      8      0   

   cliques_telefone*  cod_marca_veiculo  cod_modelo_veiculo  \
0                  0                 34                 769   
1                  4                  2                 704   
2                 11                 30                1071   
3                 14                 10                2028   
4                 11                 12                 805   

   cod_versao_veiculo  ...  arquente  bancocouro arcondic  abs  desembtras  \
0              346932  ...       NaN         NaN      NaN  NaN         NaN   
1              340148  ...         S           N        N    S           N   
2              310713  ...         S           N        S    S           S   
3              341195  ...         S           S        S    N           N   
4              332063  ...         S           S        S    S           S   

   travaeletr  vidroseletr  rodasliga  sensorchuva  sensorestacion  
0         NaN          NaN        NaN          NaN             NaN  
1           S            S          N            N               N  
2           S            S          S            N               N  
3           S            S          S            N               N  
4           S            S          S            N               N  

[5 rows x 41 columns]

In [5]:
# Dimensão do conjunto de dados

df.shape

(48665, 41)

Temos 48665 amostras de anúncios e cada um destes possui 41 variáveis descrevendo-o.

In [6]:
# Observando os tipos de dado

df.dtypes

cod_anuncio                            int64
cod_cliente                            int64
cod_tipo_pessoa                        int64
prioridade                             int64
leads                                  int64
views                                  int64
cliques_telefone*                      int64
cod_marca_veiculo                      int64
cod_modelo_veiculo                     int64
cod_versao_veiculo                     int64
ano_modelo                             int64
cep_2dig                               int64
uf_cidade                             object
vlr_anuncio                          float64
qtd_fotos                              int64
km_veiculo                             int64
vlr_mercado                          float64
flg_unico_dono                         int64
flg_licenciado                         int64
flg_ipva_pago                        float64
flg_todas_revisoes_concessionaria    float64
flg_todas_revisoes_agenda_veiculo      int64
flg_garant

In [7]:
# Algumas estatísticas básicas

df.describe()

cod_anuncio   cod_cliente  cod_tipo_pessoa    prioridade  \
count   48665.000000  48665.000000     48665.000000  48665.000000   
mean    98293.326518   8804.717374         1.847940      2.601397   
std     56501.266859   7954.688001         0.359083      0.767795   
min         2.000000      1.000000         1.000000      1.000000   
25%     49530.000000   3630.000000         2.000000      3.000000   
50%     98030.000000   6778.000000         2.000000      3.000000   
75%    147292.000000  10504.000000         2.000000      3.000000   
max    195939.000000  38733.000000         2.000000      3.000000   

              leads         views  cliques_telefone*  cod_marca_veiculo  \
count  48665.000000  48665.000000       48665.000000       48665.000000   
mean       4.416521    446.328737           7.467687          19.282791   
std       11.961256   1105.247844          11.448334          37.630803   
min        0.000000      0.000000           0.000000          -1.000000   
25%        1.000000     76.000000           2.000000           4.000000   
50%        1.000000    196.000000           4.000000           5.000000   
75%        4.000000    452.000000           9.000000          26.000000   
max      364.000000  93608.000000         457.000000         320.000000   

       cod_modelo_veiculo  cod_versao_veiculo  ...  flg_unico_dono  \
count        48665.000000        48665.000000  ...    48665.000000   
mean          2063.215658       342632.759149  ...        0.207089   
std           1112.006604        13247.921372  ...        0.405224   
min             -1.000000           -1.000000  ...        0.000000   
25%            788.000000       342364.000000  ...        0.000000   
50%           2487.000000       344132.000000  ...        0.000000   
75%           3202.000000       345633.000000  ...        0.000000   
max           3695.000000       347841.000000  ...        1.000000   

       flg_licenciado  flg_ipva_pago  flg_todas_revisoes_concessionaria  \
count    48665.000000   48353.000000                       48353.000000   
mean         0.304099       0.401340                           0.151283   
std          0.460030       0.490175                           0.358328   
min          0.000000       0.000000                           0.000000   
25%          0.000000       0.000000                           0.000000   
50%          0.000000       0.000000                           0.000000   
75%          1.000000       1.000000                           0.000000   
max          1.000000       1.000000                           1.000000   

       flg_todas_revisoes_agenda_veiculo  flg_garantia_fabrica  flg_blindado  \
count                       48665.000000          48353.000000  48665.000000   
mean                            0.066742              0.085786      0.020836   
std                             0.249577              0.280050      0.142838   
min                             0.000000              0.000000      0.000000   
25%                             0.000000              0.000000      0.000000   
50%                             0.000000              0.000000      0.000000   
75%                             0.000000              0.000000      0.000000   
max                             1.000000              1.000000      1.000000   

       flg_aceita_troca  flg_adaptado_pcd        portas  
count      48665.000000      48353.000000  48664.000000  
mean           0.085523          0.000414      3.727170  
std            0.279662          0.020334      0.822248  
min            0.000000          0.000000      0.000000  
25%            0.000000          0.000000      4.000000  
50%            0.000000          0.000000      4.000000  
75%            0.000000          0.000000      4.000000  
max            1.000000          1.000000      4.000000  

[8 rows x 26 columns]

In [8]:
# Número de valores ausentes por variável

df.isnull().sum()

cod_anuncio                             0
cod_cliente                             0
cod_tipo_pessoa                         0
prioridade                              0
leads                                   0
views                                   0
cliques_telefone*                       0
cod_marca_veiculo                       0
cod_modelo_veiculo                      0
cod_versao_veiculo                      0
ano_modelo                              0
cep_2dig                                0
uf_cidade                               0
vlr_anuncio                             0
qtd_fotos                               0
km_veiculo                              0
vlr_mercado                          6217
flg_unico_dono                          0
flg_licenciado                          0
flg_ipva_pago                         312
flg_todas_revisoes_concessionaria     312
flg_todas_revisoes_agenda_veiculo       0
flg_garantia_fabrica                  312
flg_blindado                      

<p style='text-align: justify;'>Possuimos valores ausentes em várias variáveis, porém na maioria dessas o número de valores faltantes é bem pequeno quando comparamos com a dimensão do dataset. Repare que possuimos somente 5 variáveis onde o número de valores ausentes é superior a 300 (destaque para a variável vlr_mercado que possui 6217 valores ausentes).

O tratamento dos valores ausentes será realizado mais adiante.

## 1.3 Entendendo a Distribuição da Variável Leads

In [9]:
# Distribuição da Quantidade de leads

df['leads'].value_counts()

1      23394
0      10633
4       6507
8       2870
12      1586
       ...  
252        1
160        1
172        1
156        1
140        1
Name: leads, Length: 64, dtype: int64

In [10]:
# Percentual de anúncios que não recebem nenhum Lead 

(10633/48665)*100

21.84937840336998

In [11]:
## Percentual de anúncios que recebem pelo menos um Lead

100 - 21.84937840336998

78.15062159663002

Repare que aproximadamente **78 % dos anúncios recebem pelo menos 1 Lead**.

In [12]:
# Percentual de anúncios que recebem no máximo 1 lead (recebem 0 ou 1 lead)

((23394 + 10633)/48665)*100

69.92088770163362

Agora veja que aproximadamente 70% recebem no máximo 1 Lead e, portanto, apenas 30 % dos anúncios recebem mais que 1 Lead.

In [13]:
# Número médio de leads por anúncio

df['leads'].mean()

4.4165211137367715

# <center> 2. Parte 1 - Variação da Quantidade de Leads de acordo com outras Variáveis<center>

## 2.1 cod_marca_veiculo

A variável cod_marca_veiculo indica a marca do veículo.

In [14]:
# Calculando quantas marcas existem em nosso dataset

len(np.unique(df['cod_marca_veiculo']))

75

Existem 75 marcas distintas !

In [15]:
# Olhando para a distribuição da variável

df['cod_marca_veiculo'].value_counts()

2      6843
5      6680
4      6454
3      4636
30     3616
       ... 
320       1
176       1
232       1
246       1
219       1
Name: cod_marca_veiculo, Length: 75, dtype: int64

<p style='text-align: justify;'>Apesar de existirem 75 marcas percebemos a cima que a maioria dos anúncios fazem referência a marcas específicas. Por exemplo somente a marca de código 2 está presente em 6843 anúncios.

In [16]:
# Calculando a quantidade de marcas que possuem mais de 1000 anúncios

sum(df['cod_marca_veiculo'].value_counts() > 1000)

12

Somente 12 das 75 marcas possuem mais que 1000 anúncios.

In [17]:
# Percentual de anúncios referente a essas 12 marcas

(sum(df['cod_marca_veiculo'].value_counts()[0:12])/48665)*100

86.88996198499949

Aproximadamente **87% dos anúncios são dessas 12 marcas**. Portanto podemos considerar que os anúncios dessas 12 marcas representam fortemente nosso dataset. Vamos agora avaliar como a quantidade de Leads está distribuída para anúncios dessas 12 marcas.

In [18]:
códigos = list(df['cod_marca_veiculo'].value_counts()[0:12].index)

n_veículos = []

n_leads = []

for código in códigos :
    n_veículos.append(sum(df['cod_marca_veiculo'] == código))
    n_leads.append(df[df['cod_marca_veiculo'] == código]['leads'].sum()) 

média_leads_por_marca = np.array(n_leads)/np.array(n_veículos)

(pd.DataFrame({'Código da Marca' : códigos , "N° Anúncios" : n_veículos , 'Total de Leads' : n_leads , 'Média de Leads' :
              média_leads_por_marca})).sort_values(by = 'Média de Leads' , ascending = False)

Código da Marca  N° Anúncios  Total de Leads  Média de Leads
6                16         2779           20706        7.450882
11               26         1261            6563        5.204600
5                17         3224           15912        4.935484
7                35         2620           12260        4.679389
9                28         1364            5689        4.170821
1                 5         6680           27213        4.073802
10               27         1327            5343        4.026375
3                 3         4636           18537        3.998490
0                 2         6843           26911        3.932632
8                12         1481            4966        3.353140
2                 4         6454           19798        3.067555
4                30         3616            9913        2.741427

<p style='text-align: justify;'>Como podemos ver na tabela a cima o código da marca do veículo não influencia tanto assim o número de leads que o anúncio recebe. A maioria das marcas recebem em média algo em torno de 4 leads. Das 12 marcas 9 recebem em média algo entre 3 e 5 leads . Apenas a marca de código 30 recebe em média menos que 3 leads e apenas as marcas de código 16 e 26 recebem em média mais do que 5 leads. Destaque para a marca de código 16 que recebe em média 7.45 leads (um número expressivo que demonstra que essa marca é bastante procurada).

## 2.2 cod_modelo_veiculo

A variável cod_modelo_veiculo indica o modelo do veículo.

In [19]:
# Calculando quantos modelos de veículo existem em nosso dataset

len(np.unique(df['cod_modelo_veiculo']))

656

Existem 656 modelos distintos de veículo !

In [20]:
# Olhando para a distribuição da variável

df['cod_modelo_veiculo'].value_counts()

2848    1494
740     1458
1222    1222
788     1214
687     1198
        ... 
805        1
2171       1
2655       1
2151       1
3293       1
Name: cod_modelo_veiculo, Length: 656, dtype: int64

In [21]:
(sum(df['cod_modelo_veiculo'].value_counts()[0:31]))/48665

0.5015514229939382

Repare que o código logo a cima nos diz que os 30 modelos que mais aparecem no dataset representam sozinhos aproximadamente 50% dos dados.

Vamos ver abaixo como é a distribuição do número de leads para carros desses 30 modelos :

In [22]:
códigos = list(df['cod_modelo_veiculo'].value_counts()[0:31].index)

n_veículos = []

n_leads = []

for código in códigos :
    n_veículos.append(sum(df['cod_modelo_veiculo'] == código))
    n_leads.append(df[df['cod_modelo_veiculo'] == código]['leads'].sum()) 

média_leads_por_modelo = np.array(n_leads)/np.array(n_veículos)

(pd.DataFrame({'Código do Modelo' : códigos , "N° Anúncios" : n_veículos , 'Total de Leads' : n_leads , 'Média de Leads' :
              média_leads_por_modelo})).sort_values(by = 'Média de Leads' , ascending = False)

Código do Modelo  N° Anúncios  Total de Leads  Média de Leads
9                690          976            7982        8.178279
12              1194          746            5927        7.945040
30              2862          437            2473        5.659039
24              1143          489            2764        5.652352
23              3511          525            2474        4.712381
6                776         1151            5410        4.700261
22               761          534            2443        4.574906
26              2600          466            2114        4.536481
28               778          457            2061        4.509847
13               703          725            2946        4.063448
10              3338          946            3760        3.974630
4                687         1198            4509        3.763773
8               1193         1001            3646        3.642358
16              1146          629            2174        3.456280
3                788         1214            4074        3.355848
15              3202          693            2272        3.278499
29              3359          453            1482        3.271523
17              2752          617            1955        3.168558
20               763          588            1837        3.124150
1                740         1458            4533        3.109053
2               1222         1222            3743        3.063011
25              3337          478            1416        2.962343
14              1195          694            2034        2.930836
5               3340         1194            3405        2.851759
7                781         1007            2847        2.827210
27              2165          464            1227        2.644397
18              2487          615            1520        2.471545
19              3272          607            1462        2.408567
0               2848         1494            3569        2.388889
11              1057          752            1788        2.377660
21              2804          578            1297        2.243945

<p style='text-align: justify;'>Repare que dos 30 modelos que mais aparecem nos anúncios (representantes de 50% dos dados) 28 recebem algo entre 2 e 6 leads em média. Levando em conta que ao considerarmos o dataset inteiro o número médio de leads por anúncio é ~ 4.42 podemos ver que o modelo não afeta tanto assim o número de leads de um carro. 

## 2.3 uf_cidade

Essa variável descreve a Unidade da Federação e a cidade do anunciante.

Como existem muitas cidades vamos concentrar nosso estudo na distribuição do número de leads por UF.

In [23]:
df['uf_cidade']

0              GO_Itumbiara
1                 SP_Osasco
2             SP_SÃ£o Paulo
3             SP_SÃ£o Paulo
4             SP_SÃ£o Paulo
                ...        
48660               SP_JaÃº
48661    RJ_Duque de Caxias
48662           SP_JundiaÃ­
48663           SP_JundiaÃ­
48664           SP_JundiaÃ­
Name: uf_cidade, Length: 48665, dtype: object

In [24]:
# Dividindo em UF e cidade

uf_cidade_split = df['uf_cidade'].str.split('_')

uf_cidade_split

0              [GO, Itumbiara]
1                 [SP, Osasco]
2             [SP, SÃ£o Paulo]
3             [SP, SÃ£o Paulo]
4             [SP, SÃ£o Paulo]
                 ...          
48660               [SP, JaÃº]
48661    [RJ, Duque de Caxias]
48662           [SP, JundiaÃ­]
48663           [SP, JundiaÃ­]
48664           [SP, JundiaÃ­]
Name: uf_cidade, Length: 48665, dtype: object

In [25]:
# Extraindo a UF da variável uf_cidade

ufs = []

for uf_cidade in uf_cidade_split :
    ufs.append(uf_cidade[0])

In [26]:
# Exibindo o resultado

ufs

['GO',
 'SP',
 'SP',
 'SP',
 'SP',
 'RS',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'MG',
 'SP',
 'SP',
 'DF',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'RJ',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'RJ',
 'SP',
 'SP',
 'SP',
 'SP',
 'MG',
 'GO',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'RJ',
 'SP',
 'SP',
 'PI',
 'SP',
 'SP',
 'MG',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'PA',
 'SP',
 'SP',
 'SP',
 'SP',
 'RJ',
 'SP',
 'SP',
 'PA',
 'SP',
 'SP',
 'PR',
 'SC',
 'RJ',
 'SP',
 'RS',
 'RS',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'RS',
 'MG',
 'PR',
 'SP',
 'DF',
 'PR',
 'RJ',
 'SP',
 'SP',
 'SP',
 'PR',
 'RJ',
 'SP',
 'SP',
 'SP',
 'SP',
 'RN',
 'SP',
 'SP',
 'SP',
 'SP',
 'ES',
 'SP',
 'SC',
 'SP',
 'SP',
 'SC',
 'SP',
 'SP',
 'SP',
 'RJ',
 'SP',
 'SP',
 'RJ',
 'SP',
 'RJ',
 'MG',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',
 'SP',

In [27]:
# Eliminando a feature uf_cidade do df , pois ela não é mais útil

df.drop('uf_cidade' , axis = 1 , inplace = True)

In [28]:
# Criando a feature UF que indica a unidade da Federação do anúncio

df['UF'] = ufs

Vamos abaixo ver como é de fato a distribuição do número de Leads por UF :

In [29]:
ufs = list(np.unique(ufs))

n_veículos = []

n_leads = []

for uf in ufs :
    n_veículos.append(sum(df['UF'] == uf))
    n_leads.append(df[df['UF'] == uf]['leads'].sum()) 

média_leads_por_uf = np.array(n_leads)/np.array(n_veículos)

(pd.DataFrame({'UF' : ufs , "N° Anúncios" : n_veículos , 'Total de Leads' : n_leads , 'Média de Leads' :
              média_leads_por_uf})).sort_values(by = 'Média de Leads' , ascending = False)

UF  N° Anúncios  Total de Leads  Média de Leads
26   SP        22918          151382        6.605376
19   RJ         3717           15177        4.083132
0    AC           32             114        3.562500
10   MG         3243            9973        3.075239
1    AL           80             242        3.025000
8    GO          931            2390        2.567132
4    BA          632            1614        2.553797
6    DF         1758            4305        2.448805
20   RN          530            1287        2.428302
15   PB          236             549        2.326271
18   PR         4440            9638        2.170721
7    ES          472            1018        2.156780
11   MS          553            1141        2.063291
5    CE          524             981        1.872137
23   RS         2609            4846        1.857417
17   PI          146             263        1.801370
16   PE          771            1362        1.766537
24   SC         3760            6609        1.757713
12   MT          409             703        1.718826
9    MA          232             383        1.650862
25   SE          119             187        1.571429
21   RO          164             238        1.451220
14   PA          181             258        1.425414
2    AM          158             220        1.392405
3    AP           18              25        1.388889
27   TO           13              13        1.000000
22   RR           15              12        0.800000
13  N/A            4               0        0.000000

In [30]:
# Percentual de anunciantes em SP

(22918/48665)*100

47.09339360937018

In [31]:
# Percentual de anunciantes na região Sudeste

((22918 + 3717 + 3243 + 472)/48665)*100

62.36514949142094

In [32]:
# Percentual de anunciantes na região Sul

((4440 + 2609 + 3760)/48665)*100

22.21103462447344

In [33]:
# Percentual de anunciantes nas regiões Sul e Sudeste juntas

22.21 + 62.37

84.58

<p style='text-align: justify;'>O que vemos aqui é um comportamento bem diferente entre os estados ! Perceba que quase metade de todos os anúncios são de SP (47%) . Além disso, somente na região Sudeste temos 62% dos anúncios e quando pensamos nas duas regiões mais desenvolvidas do país juntas chegamos a ~ 84% . É importante destacar também que o número médio de leads por anúncio é visivelmente bem mais elevado na região Sudeste que possui 3 dos 4 estados melhores colocados nesse quesito (Acre está a frente de MG provavelmente porque sua amostra é pequena). Na região Sul apesar do alto número de anúncios não temos um número de leads médio tão considerável como na região Sudeste. Por fim vale destacar a liderança com muita margem de SP frente aos outros estados tanto em número de anúncios como em número médio de leads por anúncio.

# <center> 3. Pré-Processamento dos Dados <center>

## 3.1 Tratamento de Valores Ausentes

In [34]:
# Observando novamente as features com valores ausentes

df.isnull().sum()

cod_anuncio                             0
cod_cliente                             0
cod_tipo_pessoa                         0
prioridade                              0
leads                                   0
views                                   0
cliques_telefone*                       0
cod_marca_veiculo                       0
cod_modelo_veiculo                      0
cod_versao_veiculo                      0
ano_modelo                              0
cep_2dig                                0
vlr_anuncio                             0
qtd_fotos                               0
km_veiculo                              0
vlr_mercado                          6217
flg_unico_dono                          0
flg_licenciado                          0
flg_ipva_pago                         312
flg_todas_revisoes_concessionaria     312
flg_todas_revisoes_agenda_veiculo       0
flg_garantia_fabrica                  312
flg_blindado                            0
flg_aceita_troca                  

Podemos reparar abaixo que muitas das features possuem 1 valor ausente somente e **esse valor ausente corresponde a primeira linha do nosso conjunto de dados**.

In [35]:
# Primeira linha do df

df.head(1)

cod_anuncio  cod_cliente  cod_tipo_pessoa  prioridade  leads  views  \
0            2         7941                2           3      1      0   

   cliques_telefone*  cod_marca_veiculo  cod_modelo_veiculo  \
0                  0                 34                 769   

   cod_versao_veiculo  ...  bancocouro  arcondic  abs  desembtras  travaeletr  \
0              346932  ...         NaN       NaN  NaN         NaN         NaN   

   vidroseletr  rodasliga  sensorchuva  sensorestacion  UF  
0          NaN        NaN          NaN             NaN  GO  

[1 rows x 41 columns]

Excluir apenas uma observação não fará falta afinal são mais de 48000 amostras. Melhor do que imputar vários campos em apenas uma linha do dataset.

In [36]:
# Excluindo a primeira linha do df

df.drop(0 , axis = 0 , inplace = True)

In [37]:
# Verificando que deu certo

df.head()

cod_anuncio  cod_cliente  cod_tipo_pessoa  prioridade  leads  views  \
1            6         1770                1           3      1      0   
2            8          709                1           3      4      0   
3           13         9708                1           2     12      0   
4           15         1363                1           2      8      0   
5           18         1880                2           3      0      0   

   cliques_telefone*  cod_marca_veiculo  cod_modelo_veiculo  \
1                  4                  2                 704   
2                 11                 30                1071   
3                 14                 10                2028   
4                 11                 12                 805   
5                  4                  2                1042   

   cod_versao_veiculo  ...  bancocouro  arcondic  abs  desembtras  travaeletr  \
1              340148  ...           N         N    S           N           S   
2              310713  ...           N         S    S           S           S   
3              341195  ...           S         S    N           N           S   
4              332063  ...           S         S    S           S           S   
5              337626  ...           S         S    N           S           S   

   vidroseletr  rodasliga  sensorchuva  sensorestacion  UF  
1            S          N            N               N  SP  
2            S          S            N               N  SP  
3            S          S            N               N  SP  
4            S          S            N               N  SP  
5            S          S            N               N  RS  

[5 rows x 41 columns]

In [38]:
# Agora temos apenas 6 features com valores ausentes

df.isnull().sum()

cod_anuncio                             0
cod_cliente                             0
cod_tipo_pessoa                         0
prioridade                              0
leads                                   0
views                                   0
cliques_telefone*                       0
cod_marca_veiculo                       0
cod_modelo_veiculo                      0
cod_versao_veiculo                      0
ano_modelo                              0
cep_2dig                                0
vlr_anuncio                             0
qtd_fotos                               0
km_veiculo                              0
vlr_mercado                          6216
flg_unico_dono                          0
flg_licenciado                          0
flg_ipva_pago                         312
flg_todas_revisoes_concessionaria     312
flg_todas_revisoes_agenda_veiculo       0
flg_garantia_fabrica                  312
flg_blindado                            0
flg_aceita_troca                  

### 3.1.1 vlr_mercado

Temos 6216 valores ausentes para essa feature. Vamos substituí-los pelos respectivos valores da feature vlr_anuncio, pois o valor que está sendo anunciado é uma boa estimativa para o valor de mercado. Essa é uma opção melhor do que imputar a média da variável vlr_mercado nos campos ausentes.

In [39]:
# Substituindo

df.loc[df['vlr_mercado'].isnull() , 'vlr_mercado'] = df[df['vlr_mercado'].isnull()]['vlr_anuncio']

In [40]:
# Não temos mais nenhum valor ausente nessa coluna !

df['vlr_mercado'].isnull().sum()

0

### 3.1.2 flg_ipva_pago

In [41]:
# Olhando para a distribuição dessa feature

df['flg_ipva_pago'].value_counts()

0.0    28946
1.0    19406
Name: flg_ipva_pago, dtype: int64

Vamos substituir os valores ausentes pela classe que mais ocorre, isto é, por 0 :

In [42]:
# Substituindo !

df.loc[df['flg_ipva_pago'].isnull() , 'flg_ipva_pago'] = 0

In [43]:
# Não temos mais nenhum valor ausente nessa coluna !

df['flg_ipva_pago'].isnull().sum()

0

### 3.1.3 flg_todas_revisoes_concessionaria

In [44]:
# Observando a distribuição dessa feature

df['flg_todas_revisoes_concessionaria'].value_counts()

0.0    41037
1.0     7315
Name: flg_todas_revisoes_concessionaria, dtype: int64

In [45]:
# Substituindo valores ausentes pela classe mais comum, ou seja, por 0

df.loc[df['flg_todas_revisoes_concessionaria'].isnull() , 'flg_todas_revisoes_concessionaria'] = 0

In [46]:
# Não temos mais nenhum valor ausente nessa coluna !

df['flg_todas_revisoes_concessionaria'].isnull().sum()

0

### 3.1.4 flg_garantia_fabrica

In [47]:
# Observando a distribuição dessa feature

df['flg_garantia_fabrica'].value_counts()

0.0    44204
1.0     4148
Name: flg_garantia_fabrica, dtype: int64

In [48]:
# Substituindo pela classe mais comum

df.loc[df['flg_garantia_fabrica'].isnull() , 'flg_garantia_fabrica'] = 0

In [49]:
# Não temos mais nenhum valor ausente nessa coluna !

df['flg_garantia_fabrica'].isnull().sum()

0

### 3.1.5 flg_adaptado_pcd

In [50]:
# Observando a distribuição dessa feature

df['flg_adaptado_pcd'].value_counts()

0.0    48332
1.0       20
Name: flg_adaptado_pcd, dtype: int64

In [51]:
# Substituindo pela classe mais comum

df.loc[df['flg_adaptado_pcd'].isnull() , 'flg_adaptado_pcd'] = 0

In [52]:
# Não temos mais nenhum valor ausente nessa coluna !

df['flg_adaptado_pcd'].isnull().sum()

0

### 3.1.6 airbag

In [53]:
# Observando a distribuição dessa feature

df['airbag'].value_counts()

S    32864
N    15793
Name: airbag, dtype: int64

In [54]:
# Substituindo pela classe mais comum, ou seja, por S

df.loc[df['airbag'].isnull() , 'airbag'] = 'S'

In [55]:
# Não temos mais nenhum valor ausente nessa coluna !

df['airbag'].isnull().sum()

0

Como podemos ver abaixo não temos mais valores faltantes em nosso dataset !

In [56]:
df.isnull().sum()

cod_anuncio                          0
cod_cliente                          0
cod_tipo_pessoa                      0
prioridade                           0
leads                                0
views                                0
cliques_telefone*                    0
cod_marca_veiculo                    0
cod_modelo_veiculo                   0
cod_versao_veiculo                   0
ano_modelo                           0
cep_2dig                             0
vlr_anuncio                          0
qtd_fotos                            0
km_veiculo                           0
vlr_mercado                          0
flg_unico_dono                       0
flg_licenciado                       0
flg_ipva_pago                        0
flg_todas_revisoes_concessionaria    0
flg_todas_revisoes_agenda_veiculo    0
flg_garantia_fabrica                 0
flg_blindado                         0
flg_aceita_troca                     0
flg_adaptado_pcd                     0
combustivel              

## 3.2 Tratamento de Variáveis Categóricas

In [57]:
# Obtendo quem são as features categóricas

features_categoricas = []
for feature , tipo in zip(df.dtypes.index , df.dtypes) :
    if tipo == 'object' :
        features_categoricas.append(feature)

In [58]:
# Observando nossas features categóricas

features_categoricas

['combustivel',
 'cambio',
 'alarme',
 'airbag',
 'arquente',
 'bancocouro',
 'arcondic',
 'abs',
 'desembtras',
 'travaeletr',
 'vidroseletr',
 'rodasliga',
 'sensorchuva',
 'sensorestacion',
 'UF']

### 3.2.1 Variáveis que possuem 2 categorias

Vamos selecionar abaixo as variáveis que possuem 2 categorias apenas. Todas elas assumem apenas o valor "S" ou "N" indicando se possuem ou não determinado atributo.

In [59]:
features_2_categorias = ['alarme', 'airbag', 'arquente', 'bancocouro', 'arcondic', 'abs', 'desembtras', 'travaeletr',
 'vidroseletr', 'rodasliga', 'sensorchuva', 'sensorestacion']

Nossa estratégia será substituir em cada feature S por 1 e N por 0 . Assim estaremos transformando uma feature categórica em numérica e não teremos problemas ao rodar nossos modelos.

In [60]:
# Aplicando a estratégia citada a cima

for feature in features_2_categorias :
    df.loc[df[feature] == 'S' , feature] = 1
    df.loc[df[feature] == 'N' , feature] = 0

In [61]:
# Vendo como ficou

df[features_2_categorias]

alarme airbag arquente bancocouro arcondic abs desembtras travaeletr  \
1          1      1        1          0        0   1          0          1   
2          1      1        1          0        1   1          1          1   
3          0      1        1          1        1   0          0          1   
4          1      0        1          1        1   1          1          1   
5          0      1        0          1        1   0          1          1   
...      ...    ...      ...        ...      ...  ..        ...        ...   
48660      1      1        1          1        1   1          1          1   
48661      0      0        0          0        0   0          0          0   
48662      0      0        0          0        0   0          0          0   
48663      1      0        1          0        1   0          1          1   
48664      1      0        1          0        1   1          1          1   

      vidroseletr rodasliga sensorchuva sensorestacion  
1               1         0           0              0  
2               1         1           0              0  
3               1         1           0              0  
4               1         1           0              0  
5               1         1           0              0  
...           ...       ...         ...            ...  
48660           1         1           0              1  
48661           0         0           0              0  
48662           0         0           0              0  
48663           1         1           0              0  
48664           1         1           0              0  

[48664 rows x 12 columns]

Perfeito !

### 3.2.2 Variáveis que possuem mais de 2 categorias

As features que possuem mais de 2 categorias são "combustivel" , "cambio" e "UF" .

### cambio

In [62]:
# Observando as categorias da variável câmbio

df['cambio'].value_counts()

manual                   27011
automatico               20866
CVT                        507
automatizado               134
semi-automatico            124
automatico sequencial       11
automatizado DCT            11
Name: cambio, dtype: int64

In [63]:
# Adicionando as variáveis que indicam a presença de cada tipo de cambio ao df

df = pd.concat([df, pd.get_dummies(df['cambio'])] , axis = 1)

In [64]:
# O número de colunas aumente em 7, pois são 7 tipos diferentes de câmbio

df.shape

(48664, 48)

In [65]:
# Observando a estrutura

df[['cambio' , 'manual' , 'automatico' , 'CVT' , 'automatizado' , 'semi-automatico' , 'automatico sequencial' ,
    'automatizado DCT']]

cambio  manual  automatico  CVT  automatizado  semi-automatico  \
1          manual       1           0    0             0                0   
2          manual       1           0    0             0                0   
3      automatico       0           1    0             0                0   
4      automatico       0           1    0             0                0   
5          manual       1           0    0             0                0   
...           ...     ...         ...  ...           ...              ...   
48660      manual       1           0    0             0                0   
48661      manual       1           0    0             0                0   
48662  automatico       0           1    0             0                0   
48663  automatico       0           1    0             0                0   
48664      manual       1           0    0             0                0   

       automatico sequencial  automatizado DCT  
1                          0                 0  
2                          0                 0  
3                          0                 0  
4                          0                 0  
5                          0                 0  
...                      ...               ...  
48660                      0                 0  
48661                      0                 0  
48662                      0                 0  
48663                      0                 0  
48664                      0                 0  

[48664 rows x 8 columns]

In [66]:
# Excluindo a variável cambio, pois não precisamos mais dela

df.drop('cambio' , axis = 1 , inplace = True)

### combustível

In [67]:
# Observando as categorias da variável combustível

df['combustivel'].value_counts()

gasolina e alcool                          35195
gasolina                                   10325
diesel                                      2683
gasolina, alcool e gas natural               204
alcool                                       118
gasolina e gas natural                        55
gas natural                                   29
gasolina e eletrico                           29
alcool e gas natural                          18
gasolina, alcool, gas natural e benzina        8
Name: combustivel, dtype: int64

In [68]:
# Adicionando as variáveis que indicam a presença de cada tipo de combustível ao df

df = pd.concat([df, pd.get_dummies(df['combustivel'])] , axis = 1)

In [69]:
# Excluindo a variável combustível, pois não precisamos mais dela

df.drop('combustivel' , axis = 1 , inplace = True)

### UF

In [70]:
# Observando as categorias da variável UF

df['UF'].value_counts()

SP     22918
PR      4440
SC      3760
RJ      3717
MG      3243
RS      2609
DF      1758
GO       930
PE       771
BA       632
MS       553
RN       530
CE       524
ES       472
MT       409
PB       236
MA       232
PA       181
RO       164
AM       158
PI       146
SE       119
AL        80
AC        32
AP        18
RR        15
TO        13
N/A        4
Name: UF, dtype: int64

In [71]:
# Adicionando as variáveis que indicam a presença de cada UF 

df = pd.concat([df, pd.get_dummies(df['UF'])] , axis = 1)

In [72]:
# Excluindo a variável UF, pois não precisamos mais dela

df.drop('UF' , axis = 1 , inplace = True)

## 3.3 Tratamento de Outliers

### 3.3.1 klm_veiculo

<p style='text-align: justify;'>A quilometragem máxima de um veículo tende a ser um número próximo a 400000. Claro que sempre existirão alguns carros que rodarão mais do que 400000 quilômetros (em geral carros mais velho).

In [73]:
# Analisando quantos carros possuem quilometragem superior a 400000 km

(df['km_veiculo'] > 400000).sum()

373

373 veículos é um número muito elevado, deve estar acontecendo alguma coisa com os dados.

Analisando os dados parece que muitos veículos acusam ter 999999 km rodados. 

In [74]:
# Quantos carros possuem 999999 km rodados ?

(df['km_veiculo'] == 999999).sum()

242

In [75]:
# Quantos carros possuem 999999 ou mais km rodados ?

(df['km_veiculo'] >= 999999).sum()

312

312 carros com número de km rodados maior ou igual a 999999 km rodados não parece fazer sentido. Vamos substituir essas quilometragens pela média de km rodados pelos carros dos outros anúncios.

In [76]:
média_de_km_rodados = df[df['km_veiculo'] < 999999]['km_veiculo'].mean()

In [77]:
média_de_km_rodados 

63236.737921906024

63236 parece ser um valor bem mais justo para a quilometragem dos carros.

In [78]:
# Substituindo

df.loc[df['km_veiculo'] >= 999999 , 'km_veiculo'] = média_de_km_rodados

### 3.3.2 ano_modelo

Repare que em duas observações temos valores negativos para o ano do modelo :

In [79]:
sum(df['ano_modelo'] < 0)

2

Nessas duas observações o ano do modelo recebe o valor -1.

In [80]:
df[df['ano_modelo'] < 0]['ano_modelo']

595     -1
35714   -1
Name: ano_modelo, dtype: int64

Vamos substituir -1 pela média dos anos dos outros veículos :

In [81]:
# Calculando a média dos anos

média_ano_modelo = df[df['ano_modelo'] != -1]['ano_modelo'].mean()

In [82]:
média_ano_modelo

2013.1933336073323

In [83]:
df.loc[df['ano_modelo'] == -1 , 'ano_modelo'] = 2013

### 3.3.3 vlr_anuncio

Existem alguns valores no nosso conjunto de dados que estão muito a cima do preço que é considerado condizente com o preço de um automóvel.

Vamos observar os 35 valores mais elevados :

In [84]:
df['vlr_anuncio'].sort_values(ascending = False)[0:35]

28985    405000000.0
17564    218500000.0
20971    195000000.0
15054    158000000.0
45956    122000000.0
35988    122000000.0
30300    113900000.0
36590    108000000.0
16924     90899000.0
47079     87000000.0
22959     82500000.0
41307     81500000.0
46372     81000000.0
45060     79000000.0
44185     74900000.0
47115     54000000.0
26527     53000000.0
16931     50900000.0
18623     49900000.0
22250     46000000.0
19207     45500000.0
36939     43000000.0
4594      42990000.0
33525     33000000.0
39756     29200000.0
34541     28000000.0
21986     27000000.0
22120     25000000.0
45731     18000000.0
940        8888888.0
29754      7100000.0
47085      3299000.0
35977      2860000.0
44616      2149000.0
41897      2149000.0
Name: vlr_anuncio, dtype: float64

Como podemos ver temos 31 carros com valor de anúncio superior a 7 milhões. Inclusive temos valores fora da realidade como 405 milhões.

Iremos substituir os valores de anúncios superiores a 7 milhões pelos seus respectivos valores de mercado.

In [85]:
df.loc[df['vlr_anuncio'] > 7000000 , 'vlr_anuncio'] = df[df['vlr_anuncio'] > 7000000]['vlr_mercado']

In [86]:
# Observando novamente os 35 anúncios mais caros

df['vlr_anuncio'].sort_values(ascending = False)[0:35]

28985    405000000.0
17564    218500000.0
20971    195000000.0
15054    158000000.0
35988    122000000.0
16924     90899000.0
940        8888888.0
47085      3299000.0
35977      2860000.0
41897      2149000.0
44616      2149000.0
45515      1990000.0
34163      1990000.0
42544      1799000.0
41896      1590000.0
47943      1300000.0
2144       1290000.0
39844      1275000.0
43176      1250000.0
99         1235000.0
725        1230000.0
43996      1220000.0
11582      1200000.0
17768      1166900.0
16957      1150000.0
6305       1074800.0
32487      1050000.0
42996      1050000.0
42537      1000000.0
34549       990000.0
2556        980000.0
5321        970000.0
28070       950000.0
13779       940000.0
37850       850000.0
Name: vlr_anuncio, dtype: float64

Ainda temos alguns valores surreais porque nesses casos o valor do anúncio é igual ao valor de mercado (Lembre-se que substituimos os valores ausentes na coluna "vlr_mercado" pelos respectivs valores de anúncio).

Vamos imputar a média dos valores de anúncio nesses valores surreais :

In [87]:
df.loc[df['vlr_anuncio'] > 7000000 , 'vlr_anuncio'] = df[df['vlr_anuncio'] < 7000000]['vlr_anuncio'].mean()

### 3.3.4 vlr_mercado

In [88]:
# Maiores valores de mercado

df['vlr_mercado'].sort_values(ascending = False)[0:10]

28985    405000000.0
17564    218500000.0
20971    195000000.0
15054    158000000.0
35988    122000000.0
16924     90899000.0
940        8888888.0
47085      3299000.0
35977      2860000.0
41897      2149000.0
Name: vlr_mercado, dtype: float64

In [89]:
# Substituindo os maiores valores de mercado pela média dos valores de mercado

df.loc[df['vlr_mercado'] > 7000000 , 'vlr_mercado'] = df[df['vlr_mercado'] < 7000000]['vlr_mercado'].mean()

In [90]:
# Exibindo novamente os maiores valores de mercado

df['vlr_mercado'].sort_values(ascending = False)[0:10]

47085    3299000.0
35977    2860000.0
41897    2149000.0
44616    2149000.0
34163    1990000.0
42544    1799000.0
41896    1590000.0
47943    1300000.0
2144     1290000.0
39844    1275000.0
Name: vlr_mercado, dtype: float64

## 3.4 Feature Scaling

In [91]:
# Instanciando

scaler = StandardScaler()

In [92]:
# Selecionando as features que vamos aplicar o dimensionamento

features_scaler = ['vlr_mercado' , 'km_veiculo' , 'qtd_fotos' , 'vlr_anuncio' , 'cep_2dig' , 'ano_modelo', 
                  'cod_versao_veiculo' , 'cod_modelo_veiculo' , 'cod_marca_veiculo' , 'cliques_telefone*' ,
                   'views' , 'cod_cliente' , 'cod_anuncio']

In [93]:
# Aplicando o dimensionamento padrão em cada uma das features a cima

for feature in features_scaler :
    df[feature] = scaler.fit_transform(np.array(df[feature]).reshape(-1,1))

In [94]:
# Observando como ficaram os valores nas columas em que aplicamos o dimensionamento de variáveis

df[features_scaler]

vlr_mercado  km_veiculo  qtd_fotos  vlr_anuncio  cep_2dig  ano_modelo  \
1        -0.801908   12.037971  -3.053281    -0.785747 -0.952290   -3.601467   
2        -0.295083   -0.567467  -1.210059    -0.286341 -1.071897   -2.344653   
3        -0.208674    0.802366   0.633162    -0.201196 -1.012093   -3.810935   
4        -0.441315    0.153761  -0.288448    -0.430432 -0.982191   -3.810935   
5        -0.324994   -1.214919  -1.210059    -0.315814  1.559465   -1.716247   
...            ...         ...        ...          ...       ...         ...   
48660    -0.142016   -0.542491   0.633162    -0.135700 -0.623369    0.587911   
48661    -0.223873    0.537660  -2.592476    -0.217570 -0.384155   -0.040496   
48662     0.417738    1.090549  -3.053281     0.615864 -0.742977   -0.249965   
48663    -0.178696   -0.446430  -3.053281    -0.040731 -0.742977    0.168973   
48664    -0.384185   -0.965160  -3.053281    -0.335463 -0.742977   -0.040496   

       cod_versao_veiculo  cod_modelo_veiculo  cod_marca_veiculo  \
1               -0.187552           -1.222350          -0.459265   
2               -2.409412           -0.892311           0.284807   
3               -0.108521           -0.031693          -0.246673   
4               -0.797837           -1.131522          -0.193525   
5               -0.377922           -0.918391          -0.459265   
...                   ...                 ...                ...   
48660            0.281277            1.170655           6.928311   
48661            0.094304           -0.796987          -0.406117   
48662            0.122233            0.957524          -0.379543   
48663            0.134990            1.132885          -0.459265   
48664            0.143368            1.146374          -0.060655   

       cliques_telefone*      views  cod_cliente  cod_anuncio  
1              -0.302914  -0.403836    -0.884351    -1.739650  
2               0.308532  -0.403836    -1.017731    -1.739614  
3               0.570580  -0.403836     0.113551    -1.739526  
4               0.308532  -0.403836    -0.935516    -1.739490  
5              -0.302914  -0.403836    -0.870523    -1.739437  
...                  ...        ...          ...          ...  
48660          -0.652311  30.525026    -0.721554     1.727850  
48661          -0.652311  40.354512     0.468939     1.727956  
48662          -0.652311  63.853353    -0.819735     1.728062  
48663          -0.652311  74.638282    -0.819735     1.728133  
48664          -0.652311  84.290432    -0.819735     1.728221  

[48664 rows x 13 columns]

# <center> 4. Desafio Bônus <center>

## 4.1 Seleção das Features com RFECV

In [95]:
# Criando a lista de todas features que temos a disposição para utilizarmos no treinamento de nossos modelos

features = ['cod_anuncio', 'cod_cliente' , 'cod_tipo_pessoa', 'prioridade',
       'views', 'cliques_telefone*', 'cod_marca_veiculo', 'cod_modelo_veiculo',
       'cod_versao_veiculo', 'ano_modelo', 'cep_2dig', 'vlr_anuncio',
       'qtd_fotos', 'km_veiculo', 'vlr_mercado', 'flg_unico_dono',
       'flg_licenciado', 'flg_ipva_pago', 'flg_todas_revisoes_concessionaria',
       'flg_todas_revisoes_agenda_veiculo', 'flg_garantia_fabrica',
       'flg_blindado', 'flg_aceita_troca', 'flg_adaptado_pcd', 'portas',
       'alarme', 'airbag', 'arquente', 'bancocouro', 'arcondic', 'abs',
       'desembtras', 'travaeletr', 'vidroseletr', 'rodasliga', 'sensorchuva',
       'sensorestacion', 'CVT', 'automatico', 'automatico sequencial',
       'automatizado', 'automatizado DCT', 'manual', 'semi-automatico',
       'alcool', 'alcool e gas natural', 'diesel', 'gas natural', 'gasolina',
       'gasolina e alcool', 'gasolina e eletrico', 'gasolina e gas natural',
       'gasolina, alcool e gas natural',
       'gasolina, alcool, gas natural e benzina' , 'AC', 'AL', 'AM', 'AP',
       'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'N/A', 'PA', 'PB',
       'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO']

In [96]:
# Criando a matriz de features e a variável alvo (leads)

X = np.array(df[features])

y = np.array(df['leads'])

Agora surge a grande pergunta : Quais dessas features devemos selecionar para treinar nossos modelos ?

<p style='text-align: justify;'>Utilizar todas as features disponíveis nem sempre é uma boa idéia. Devemos nos lembrar que algumas features podem estar correlacionadas com outras, ou seja, uma feature pode "carregar consigo" boa parte da informação presente em outra e isso geralmente piora o desempenho dos modelos. Além disso, um número elevado de variávies pode acabar por gerar ruído e piorar a performance dos modelos. Devemos nos lembrar também que se tivermos muitas features o modelo pode acabar "decorando" os exemplos de treino e se ajustar excessivamente ao conjunto de treino (overfitting).

Existem várias maneiras de selecionar as features adequadas :

 - Remover features com baixa variância

- Selecionar com base em testes estatísticos

- Eliminação recursiva de features (RFE)

Escolheremos a última opção para selecionar nossas features. Na verdade utilizaremos um método baseado nessa opção, porém um pouco mais robusto : Recursive Feature Elimination with Cross-Validation (RFECV).

<p style='text-align: justify;'>O objetivo da eliminação recursiva de features (RFE) é selecionar as features considerando recursivamente conjuntos cada vez menores de variáveis. Primeiro, o estimador é treinado no conjunto inicial de features e a importância de cada variável é obtida através de qualquer atributo específico (como coef_, feature_importances_) ou callable. Em seguida, as features menos importantes são removidos do conjunto atual de features. Esse procedimento é repetido recursivamente no conjunto podado até que o número desejado de features a serem selecionadas seja finalmente alcançado. O algoritmo RFECV ainda se utiliza da validação cruzada para determinar o número ótimo de features.

Para rodar o algoritmo RFECV utilizaremos o modelo LightGBM , pois além de ser um modelo que possui o atributo feature_importances ele costuma ter um tempo de treinamento inferior aos demais modelos e como o RFECV é custoso computacionalmente esse modelo se revela uma ótima opção.

<p style='text-align: justify;'>Além disso utilizaremos como métrica a negação do erro absoluto médio. Por padrão do Scikit-Learn o melhor score é sempre o maior, porém sabemos que quanto menor o erro absoluto médio melhor o modelo e, portanto, buscaremos o maior valor da negação do erro absoluto médio, pois quanto maior a negação menor o erro absoluto médio.

In [97]:
# Criando o array com todas as features disponíveis

X = np.array(df[features])

In [98]:
# Instanciando o algoritmo RFECV

selector = RFECV(estimator = LGBMRegressor() , step = 1 , cv = 5 , scoring = 'neg_mean_absolute_error')

In [99]:
# Essa célula demora pra rodar, pois o algoritmo RFECV treina muitos modelos

selector.fit(X, y)

RFECV(cv=5, estimator=LGBMRegressor(), scoring='neg_mean_absolute_error')

In [100]:
# Número de features selecionadas

selector.n_features_

1

Que interessante ! **O RFECV nos diz que o melhor modelo possível é treinado em apenas 1 feature** ! 

Treinar o modelo LGBMRegressor com 1 feature nos traz melhor score do que se treinássemos em todo o conjunto de variáveis !

In [101]:
# Obtendo a máscara de features selecionadas

mask = selector.support_

mask

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [102]:
# Descobrindo qual foi a Feature indicada pelo RFECV

(np.array(features))[mask]

array(['cliques_telefone*'], dtype='<U39')

A melhor feature para rodar nosso modelo é **"cliques_telefone*"** .

Faz sentido ! Realmente o número de cliques no telefone do anunciante é algo que indica que o cliente parece estar perto de fazer uma proposta. Afinal por que ligar se não tiver fortemente interessado no anúncio ?

## 4.2 Validação - Cruzada

Vamos agora obter o score médio de validação cruzada para diferentes modelos treinados somente na feature "cliques_telefone*" . A validação cruzada nos permitirá ver como os modelos estão desempenhando em dados não vistos durante o treinamento e, com isso, poderemos escolher o modelo que obtém as melhores métricas.

In [103]:
# Nova matriz de features 

X = np.array(df['cliques_telefone*']).reshape(-1,1)

In [104]:
# Modelos

modelos = [LGBMRegressor() , LinearRegression() , KNeighborsRegressor() , DecisionTreeRegressor(),
          RandomForestRegressor() , AdaBoostRegressor(), GradientBoostingRegressor(), 
          XGBRegressor(use_label_encoder = False),
          CatBoostRegressor()]

In [105]:
# Nome dos Modelos

nome_modelos = ['LGBM' , 'Linear Regression' , 'KNN' , 'Decision Tree' , 'Random Forest' , 'ADA Boost',
               'Gradient Boosting' , 'XGB' , 'CatBoost']

In [106]:
# Demora um pouco pra rodar

scores_MAE = []
scores_MSE = []
scores_R2 = []

for model in modelos :
    scores_MAE.append(-np.mean(cross_val_score(model, X, y , cv = 5, scoring = 'neg_mean_absolute_error')))
    scores_MSE.append(-np.mean(cross_val_score(model, X, y , cv = 5, scoring = 'neg_mean_squared_error')))
    scores_R2.append(np.mean(cross_val_score(model, X, y , cv = 5, scoring = 'r2')))

Learning rate set to 0.073021
0:	learn: 10.9837389	total: 204ms	remaining: 3m 23s
1:	learn: 10.5414390	total: 223ms	remaining: 1m 51s
2:	learn: 10.1396668	total: 243ms	remaining: 1m 20s
3:	learn: 9.7708279	total: 264ms	remaining: 1m 5s
4:	learn: 9.4339036	total: 283ms	remaining: 56.4s
5:	learn: 9.1321228	total: 303ms	remaining: 50.2s
6:	learn: 8.8544678	total: 332ms	remaining: 47.1s
7:	learn: 8.6129707	total: 352ms	remaining: 43.6s
8:	learn: 8.3945367	total: 368ms	remaining: 40.6s
9:	learn: 8.1964045	total: 385ms	remaining: 38.1s
10:	learn: 8.0243479	total: 407ms	remaining: 36.6s
11:	learn: 7.8703881	total: 428ms	remaining: 35.2s
12:	learn: 7.7293153	total: 447ms	remaining: 33.9s
13:	learn: 7.6049112	total: 467ms	remaining: 32.9s
14:	learn: 7.4924265	total: 489ms	remaining: 32.1s
15:	learn: 7.3925322	total: 515ms	remaining: 31.7s
16:	learn: 7.3041543	total: 532ms	remaining: 30.8s
17:	learn: 7.2250179	total: 552ms	remaining: 30.1s
18:	learn: 7.1555551	total: 569ms	remaining: 29.4s
19:	l

169:	learn: 6.3696087	total: 3.39s	remaining: 16.6s
170:	learn: 6.3691481	total: 3.41s	remaining: 16.5s
171:	learn: 6.3675681	total: 3.43s	remaining: 16.5s
172:	learn: 6.3671238	total: 3.44s	remaining: 16.5s
173:	learn: 6.3666955	total: 3.46s	remaining: 16.4s
174:	learn: 6.3651754	total: 3.48s	remaining: 16.4s
175:	learn: 6.3647621	total: 3.5s	remaining: 16.4s
176:	learn: 6.3643638	total: 3.51s	remaining: 16.3s
177:	learn: 6.3633627	total: 3.53s	remaining: 16.3s
178:	learn: 6.3619393	total: 3.54s	remaining: 16.3s
179:	learn: 6.3605664	total: 3.56s	remaining: 16.2s
180:	learn: 6.3579577	total: 3.59s	remaining: 16.2s
181:	learn: 6.3575735	total: 3.6s	remaining: 16.2s
182:	learn: 6.3562887	total: 3.62s	remaining: 16.2s
183:	learn: 6.3538803	total: 3.64s	remaining: 16.1s
184:	learn: 6.3516250	total: 3.66s	remaining: 16.1s
185:	learn: 6.3504466	total: 3.67s	remaining: 16.1s
186:	learn: 6.3493116	total: 3.69s	remaining: 16s
187:	learn: 6.3472580	total: 3.7s	remaining: 16s
188:	learn: 6.34630

336:	learn: 6.2703931	total: 6.34s	remaining: 12.5s
337:	learn: 6.2703194	total: 6.35s	remaining: 12.4s
338:	learn: 6.2697187	total: 6.37s	remaining: 12.4s
339:	learn: 6.2694414	total: 6.39s	remaining: 12.4s
340:	learn: 6.2693704	total: 6.41s	remaining: 12.4s
341:	learn: 6.2693019	total: 6.42s	remaining: 12.4s
342:	learn: 6.2688788	total: 6.44s	remaining: 12.3s
343:	learn: 6.2686161	total: 6.46s	remaining: 12.3s
344:	learn: 6.2679425	total: 6.47s	remaining: 12.3s
345:	learn: 6.2676371	total: 6.49s	remaining: 12.3s
346:	learn: 6.2668453	total: 6.51s	remaining: 12.3s
347:	learn: 6.2665535	total: 6.53s	remaining: 12.2s
348:	learn: 6.2661216	total: 6.55s	remaining: 12.2s
349:	learn: 6.2652687	total: 6.57s	remaining: 12.2s
350:	learn: 6.2646543	total: 6.58s	remaining: 12.2s
351:	learn: 6.2645883	total: 6.6s	remaining: 12.2s
352:	learn: 6.2642650	total: 6.62s	remaining: 12.1s
353:	learn: 6.2641207	total: 6.63s	remaining: 12.1s
354:	learn: 6.2637393	total: 6.65s	remaining: 12.1s
355:	learn: 6

498:	learn: 6.2336047	total: 9.12s	remaining: 9.15s
499:	learn: 6.2331572	total: 9.14s	remaining: 9.14s
500:	learn: 6.2330807	total: 9.15s	remaining: 9.12s
501:	learn: 6.2328276	total: 9.17s	remaining: 9.1s
502:	learn: 6.2324832	total: 9.19s	remaining: 9.08s
503:	learn: 6.2323250	total: 9.21s	remaining: 9.07s
504:	learn: 6.2322595	total: 9.23s	remaining: 9.05s
505:	learn: 6.2321778	total: 9.24s	remaining: 9.03s
506:	learn: 6.2320630	total: 9.26s	remaining: 9.01s
507:	learn: 6.2318361	total: 9.28s	remaining: 8.99s
508:	learn: 6.2317311	total: 9.29s	remaining: 8.96s
509:	learn: 6.2316300	total: 9.31s	remaining: 8.95s
510:	learn: 6.2315574	total: 9.33s	remaining: 8.93s
511:	learn: 6.2314689	total: 9.35s	remaining: 8.91s
512:	learn: 6.2311777	total: 9.37s	remaining: 8.89s
513:	learn: 6.2309624	total: 9.38s	remaining: 8.87s
514:	learn: 6.2308580	total: 9.4s	remaining: 8.85s
515:	learn: 6.2304269	total: 9.42s	remaining: 8.83s
516:	learn: 6.2300415	total: 9.43s	remaining: 8.81s
517:	learn: 6.

667:	learn: 6.2129206	total: 12s	remaining: 5.97s
668:	learn: 6.2128898	total: 12s	remaining: 5.95s
669:	learn: 6.2128314	total: 12s	remaining: 5.93s
670:	learn: 6.2127734	total: 12.1s	remaining: 5.92s
671:	learn: 6.2125983	total: 12.1s	remaining: 5.9s
672:	learn: 6.2125877	total: 12.1s	remaining: 5.88s
673:	learn: 6.2125322	total: 12.1s	remaining: 5.86s
674:	learn: 6.2124737	total: 12.1s	remaining: 5.84s
675:	learn: 6.2124385	total: 12.2s	remaining: 5.83s
676:	learn: 6.2124282	total: 12.2s	remaining: 5.81s
677:	learn: 6.2122671	total: 12.2s	remaining: 5.79s
678:	learn: 6.2121585	total: 12.2s	remaining: 5.77s
679:	learn: 6.2121411	total: 12.2s	remaining: 5.75s
680:	learn: 6.2121106	total: 12.2s	remaining: 5.73s
681:	learn: 6.2120547	total: 12.3s	remaining: 5.72s
682:	learn: 6.2118826	total: 12.3s	remaining: 5.7s
683:	learn: 6.2118536	total: 12.3s	remaining: 5.68s
684:	learn: 6.2117275	total: 12.3s	remaining: 5.66s
685:	learn: 6.2115590	total: 12.3s	remaining: 5.64s
686:	learn: 6.211549

827:	learn: 6.2029941	total: 14.8s	remaining: 3.08s
828:	learn: 6.2029185	total: 14.8s	remaining: 3.06s
829:	learn: 6.2028863	total: 14.8s	remaining: 3.04s
830:	learn: 6.2028488	total: 14.9s	remaining: 3.02s
831:	learn: 6.2028396	total: 14.9s	remaining: 3.01s
832:	learn: 6.2028045	total: 14.9s	remaining: 2.99s
833:	learn: 6.2027267	total: 14.9s	remaining: 2.97s
834:	learn: 6.2026868	total: 14.9s	remaining: 2.95s
835:	learn: 6.2026812	total: 14.9s	remaining: 2.93s
836:	learn: 6.2026653	total: 15s	remaining: 2.91s
837:	learn: 6.2026361	total: 15s	remaining: 2.9s
838:	learn: 6.2026078	total: 15s	remaining: 2.88s
839:	learn: 6.2025887	total: 15s	remaining: 2.86s
840:	learn: 6.2025550	total: 15s	remaining: 2.84s
841:	learn: 6.2024917	total: 15.1s	remaining: 2.83s
842:	learn: 6.2024652	total: 15.1s	remaining: 2.81s
843:	learn: 6.2024349	total: 15.1s	remaining: 2.79s
844:	learn: 6.2023860	total: 15.1s	remaining: 2.77s
845:	learn: 6.2023605	total: 15.1s	remaining: 2.75s
846:	learn: 6.2022903	t

996:	learn: 6.1974105	total: 17.7s	remaining: 53.3ms
997:	learn: 6.1973751	total: 17.7s	remaining: 35.5ms
998:	learn: 6.1973613	total: 17.7s	remaining: 17.8ms
999:	learn: 6.1973495	total: 17.8s	remaining: 0us
Learning rate set to 0.073021
0:	learn: 11.7476150	total: 23.2ms	remaining: 23.2s
1:	learn: 11.2545222	total: 44.7ms	remaining: 22.3s
2:	learn: 10.8143400	total: 62.3ms	remaining: 20.7s
3:	learn: 10.4051762	total: 79.5ms	remaining: 19.8s
4:	learn: 10.0348359	total: 96.4ms	remaining: 19.2s
5:	learn: 9.7027351	total: 114ms	remaining: 18.9s
6:	learn: 9.4070292	total: 131ms	remaining: 18.6s
7:	learn: 9.1433709	total: 147ms	remaining: 18.3s
8:	learn: 8.9037694	total: 164ms	remaining: 18s
9:	learn: 8.6931515	total: 180ms	remaining: 17.8s
10:	learn: 8.4951941	total: 196ms	remaining: 17.7s
11:	learn: 8.3275608	total: 217ms	remaining: 17.8s
12:	learn: 8.1713652	total: 237ms	remaining: 18s
13:	learn: 8.0354845	total: 257ms	remaining: 18.1s
14:	learn: 7.9138689	total: 279ms	remaining: 18.3s


160:	learn: 6.7843597	total: 2.85s	remaining: 14.8s
161:	learn: 6.7831803	total: 2.87s	remaining: 14.8s
162:	learn: 6.7822441	total: 2.88s	remaining: 14.8s
163:	learn: 6.7812092	total: 2.9s	remaining: 14.8s
164:	learn: 6.7801766	total: 2.92s	remaining: 14.8s
165:	learn: 6.7798761	total: 2.94s	remaining: 14.8s
166:	learn: 6.7789586	total: 2.95s	remaining: 14.7s
167:	learn: 6.7768749	total: 2.97s	remaining: 14.7s
168:	learn: 6.7764432	total: 2.98s	remaining: 14.7s
169:	learn: 6.7761747	total: 3s	remaining: 14.7s
170:	learn: 6.7759249	total: 3.02s	remaining: 14.6s
171:	learn: 6.7754346	total: 3.03s	remaining: 14.6s
172:	learn: 6.7746352	total: 3.05s	remaining: 14.6s
173:	learn: 6.7741554	total: 3.07s	remaining: 14.6s
174:	learn: 6.7722433	total: 3.09s	remaining: 14.6s
175:	learn: 6.7715603	total: 3.1s	remaining: 14.5s
176:	learn: 6.7707936	total: 3.12s	remaining: 14.5s
177:	learn: 6.7700058	total: 3.14s	remaining: 14.5s
178:	learn: 6.7695547	total: 3.15s	remaining: 14.5s
179:	learn: 6.769

326:	learn: 6.6854850	total: 5.68s	remaining: 11.7s
327:	learn: 6.6854052	total: 5.7s	remaining: 11.7s
328:	learn: 6.6849936	total: 5.71s	remaining: 11.7s
329:	learn: 6.6846302	total: 5.73s	remaining: 11.6s
330:	learn: 6.6845355	total: 5.75s	remaining: 11.6s
331:	learn: 6.6840012	total: 5.77s	remaining: 11.6s
332:	learn: 6.6835384	total: 5.79s	remaining: 11.6s
333:	learn: 6.6824493	total: 5.81s	remaining: 11.6s
334:	learn: 6.6820531	total: 5.83s	remaining: 11.6s
335:	learn: 6.6813927	total: 5.84s	remaining: 11.5s
336:	learn: 6.6808755	total: 5.86s	remaining: 11.5s
337:	learn: 6.6806096	total: 5.88s	remaining: 11.5s
338:	learn: 6.6803123	total: 5.9s	remaining: 11.5s
339:	learn: 6.6799314	total: 5.92s	remaining: 11.5s
340:	learn: 6.6798399	total: 5.93s	remaining: 11.5s
341:	learn: 6.6795889	total: 5.95s	remaining: 11.5s
342:	learn: 6.6794733	total: 5.97s	remaining: 11.4s
343:	learn: 6.6791929	total: 5.98s	remaining: 11.4s
344:	learn: 6.6791074	total: 6s	remaining: 11.4s
345:	learn: 6.678

490:	learn: 6.6431445	total: 8.67s	remaining: 8.99s
491:	learn: 6.6426270	total: 8.69s	remaining: 8.97s
492:	learn: 6.6424145	total: 8.71s	remaining: 8.96s
493:	learn: 6.6420930	total: 8.73s	remaining: 8.94s
494:	learn: 6.6419069	total: 8.75s	remaining: 8.93s
495:	learn: 6.6418317	total: 8.77s	remaining: 8.91s
496:	learn: 6.6417383	total: 8.8s	remaining: 8.9s
497:	learn: 6.6415623	total: 8.83s	remaining: 8.9s
498:	learn: 6.6414617	total: 8.86s	remaining: 8.89s
499:	learn: 6.6411624	total: 8.88s	remaining: 8.88s
500:	learn: 6.6411056	total: 8.91s	remaining: 8.87s
501:	learn: 6.6406470	total: 8.93s	remaining: 8.86s
502:	learn: 6.6403658	total: 8.95s	remaining: 8.84s
503:	learn: 6.6400555	total: 8.97s	remaining: 8.83s
504:	learn: 6.6398786	total: 8.99s	remaining: 8.81s
505:	learn: 6.6397847	total: 9.01s	remaining: 8.79s
506:	learn: 6.6396216	total: 9.02s	remaining: 8.77s
507:	learn: 6.6395264	total: 9.04s	remaining: 8.75s
508:	learn: 6.6391806	total: 9.05s	remaining: 8.73s
509:	learn: 6.6

650:	learn: 6.6184902	total: 11.5s	remaining: 6.19s
651:	learn: 6.6184116	total: 11.6s	remaining: 6.17s
652:	learn: 6.6183785	total: 11.6s	remaining: 6.15s
653:	learn: 6.6183467	total: 11.6s	remaining: 6.14s
654:	learn: 6.6183084	total: 11.6s	remaining: 6.12s
655:	learn: 6.6182435	total: 11.6s	remaining: 6.1s
656:	learn: 6.6182045	total: 11.7s	remaining: 6.08s
657:	learn: 6.6181391	total: 11.7s	remaining: 6.07s
658:	learn: 6.6181095	total: 11.7s	remaining: 6.05s
659:	learn: 6.6180363	total: 11.7s	remaining: 6.03s
660:	learn: 6.6179413	total: 11.7s	remaining: 6.01s
661:	learn: 6.6176942	total: 11.7s	remaining: 5.99s
662:	learn: 6.6176140	total: 11.8s	remaining: 5.98s
663:	learn: 6.6174938	total: 11.8s	remaining: 5.96s
664:	learn: 6.6174655	total: 11.8s	remaining: 5.94s
665:	learn: 6.6174385	total: 11.8s	remaining: 5.92s
666:	learn: 6.6174125	total: 11.8s	remaining: 5.91s
667:	learn: 6.6173981	total: 11.8s	remaining: 5.89s
668:	learn: 6.6172022	total: 11.9s	remaining: 5.87s
669:	learn: 6

818:	learn: 6.6051706	total: 14.5s	remaining: 3.19s
819:	learn: 6.6051066	total: 14.5s	remaining: 3.18s
820:	learn: 6.6050516	total: 14.5s	remaining: 3.16s
821:	learn: 6.6049154	total: 14.5s	remaining: 3.14s
822:	learn: 6.6048717	total: 14.5s	remaining: 3.13s
823:	learn: 6.6048191	total: 14.5s	remaining: 3.11s
824:	learn: 6.6048087	total: 14.6s	remaining: 3.09s
825:	learn: 6.6047782	total: 14.6s	remaining: 3.07s
826:	learn: 6.6047245	total: 14.6s	remaining: 3.05s
827:	learn: 6.6046213	total: 14.6s	remaining: 3.04s
828:	learn: 6.6045226	total: 14.6s	remaining: 3.02s
829:	learn: 6.6044738	total: 14.7s	remaining: 3s
830:	learn: 6.6044127	total: 14.7s	remaining: 2.98s
831:	learn: 6.6043692	total: 14.7s	remaining: 2.97s
832:	learn: 6.6043212	total: 14.7s	remaining: 2.95s
833:	learn: 6.6042370	total: 14.7s	remaining: 2.93s
834:	learn: 6.6042039	total: 14.7s	remaining: 2.91s
835:	learn: 6.6041109	total: 14.8s	remaining: 2.9s
836:	learn: 6.6040875	total: 14.8s	remaining: 2.88s
837:	learn: 6.60

982:	learn: 6.5975707	total: 17.4s	remaining: 301ms
983:	learn: 6.5975561	total: 17.4s	remaining: 283ms
984:	learn: 6.5975147	total: 17.4s	remaining: 265ms
985:	learn: 6.5975052	total: 17.4s	remaining: 248ms
986:	learn: 6.5974587	total: 17.5s	remaining: 230ms
987:	learn: 6.5974014	total: 17.5s	remaining: 212ms
988:	learn: 6.5973807	total: 17.5s	remaining: 195ms
989:	learn: 6.5973236	total: 17.5s	remaining: 177ms
990:	learn: 6.5972899	total: 17.5s	remaining: 159ms
991:	learn: 6.5972501	total: 17.5s	remaining: 141ms
992:	learn: 6.5971823	total: 17.6s	remaining: 124ms
993:	learn: 6.5971748	total: 17.6s	remaining: 106ms
994:	learn: 6.5971572	total: 17.6s	remaining: 88.4ms
995:	learn: 6.5971347	total: 17.6s	remaining: 70.7ms
996:	learn: 6.5970709	total: 17.6s	remaining: 53ms
997:	learn: 6.5970510	total: 17.6s	remaining: 35.4ms
998:	learn: 6.5970106	total: 17.7s	remaining: 17.7ms
999:	learn: 6.5969936	total: 17.7s	remaining: 0us
Learning rate set to 0.073021
0:	learn: 12.2011708	total: 22.1m

144:	learn: 6.9712074	total: 2.59s	remaining: 15.3s
145:	learn: 6.9708905	total: 2.61s	remaining: 15.3s
146:	learn: 6.9699708	total: 2.63s	remaining: 15.3s
147:	learn: 6.9696145	total: 2.65s	remaining: 15.2s
148:	learn: 6.9693378	total: 2.67s	remaining: 15.2s
149:	learn: 6.9691534	total: 2.69s	remaining: 15.2s
150:	learn: 6.9679869	total: 2.71s	remaining: 15.2s
151:	learn: 6.9668105	total: 2.72s	remaining: 15.2s
152:	learn: 6.9664082	total: 2.74s	remaining: 15.2s
153:	learn: 6.9635526	total: 2.75s	remaining: 15.1s
154:	learn: 6.9633850	total: 2.77s	remaining: 15.1s
155:	learn: 6.9621834	total: 2.79s	remaining: 15.1s
156:	learn: 6.9606808	total: 2.82s	remaining: 15.1s
157:	learn: 6.9600620	total: 2.83s	remaining: 15.1s
158:	learn: 6.9591775	total: 2.85s	remaining: 15.1s
159:	learn: 6.9586195	total: 2.87s	remaining: 15.1s
160:	learn: 6.9583522	total: 2.91s	remaining: 15.2s
161:	learn: 6.9576271	total: 2.93s	remaining: 15.1s
162:	learn: 6.9570725	total: 2.94s	remaining: 15.1s
163:	learn: 

313:	learn: 6.8801535	total: 5.63s	remaining: 12.3s
314:	learn: 6.8801073	total: 5.64s	remaining: 12.3s
315:	learn: 6.8796115	total: 5.66s	remaining: 12.3s
316:	learn: 6.8793539	total: 5.68s	remaining: 12.2s
317:	learn: 6.8785968	total: 5.71s	remaining: 12.2s
318:	learn: 6.8785469	total: 5.72s	remaining: 12.2s
319:	learn: 6.8784992	total: 5.74s	remaining: 12.2s
320:	learn: 6.8781577	total: 5.76s	remaining: 12.2s
321:	learn: 6.8781119	total: 5.78s	remaining: 12.2s
322:	learn: 6.8778553	total: 5.79s	remaining: 12.1s
323:	learn: 6.8773222	total: 5.81s	remaining: 12.1s
324:	learn: 6.8769089	total: 5.83s	remaining: 12.1s
325:	learn: 6.8766260	total: 5.85s	remaining: 12.1s
326:	learn: 6.8765867	total: 5.87s	remaining: 12.1s
327:	learn: 6.8765512	total: 5.89s	remaining: 12.1s
328:	learn: 6.8761952	total: 5.91s	remaining: 12.1s
329:	learn: 6.8759598	total: 5.93s	remaining: 12s
330:	learn: 6.8755666	total: 5.95s	remaining: 12s
331:	learn: 6.8755256	total: 5.96s	remaining: 12s
332:	learn: 6.8752

478:	learn: 6.8296335	total: 8.72s	remaining: 9.48s
479:	learn: 6.8295033	total: 8.74s	remaining: 9.47s
480:	learn: 6.8291838	total: 8.76s	remaining: 9.45s
481:	learn: 6.8290128	total: 8.78s	remaining: 9.43s
482:	learn: 6.8287968	total: 8.79s	remaining: 9.41s
483:	learn: 6.8286422	total: 8.81s	remaining: 9.4s
484:	learn: 6.8284461	total: 8.83s	remaining: 9.38s
485:	learn: 6.8282836	total: 8.85s	remaining: 9.36s
486:	learn: 6.8282547	total: 8.86s	remaining: 9.34s
487:	learn: 6.8281277	total: 8.88s	remaining: 9.31s
488:	learn: 6.8280068	total: 8.9s	remaining: 9.3s
489:	learn: 6.8279792	total: 8.92s	remaining: 9.28s
490:	learn: 6.8278640	total: 8.94s	remaining: 9.26s
491:	learn: 6.8276038	total: 8.96s	remaining: 9.25s
492:	learn: 6.8274817	total: 8.98s	remaining: 9.23s
493:	learn: 6.8274555	total: 8.99s	remaining: 9.21s
494:	learn: 6.8273384	total: 9.01s	remaining: 9.19s
495:	learn: 6.8272261	total: 9.02s	remaining: 9.17s
496:	learn: 6.8272011	total: 9.04s	remaining: 9.15s
497:	learn: 6.8

638:	learn: 6.8036525	total: 11.5s	remaining: 6.52s
639:	learn: 6.8035037	total: 11.6s	remaining: 6.51s
640:	learn: 6.8033823	total: 11.6s	remaining: 6.49s
641:	learn: 6.8032789	total: 11.6s	remaining: 6.47s
642:	learn: 6.8031364	total: 11.6s	remaining: 6.45s
643:	learn: 6.8029134	total: 11.6s	remaining: 6.43s
644:	learn: 6.8028357	total: 11.7s	remaining: 6.42s
645:	learn: 6.8027171	total: 11.7s	remaining: 6.39s
646:	learn: 6.8026040	total: 11.7s	remaining: 6.38s
647:	learn: 6.8023344	total: 11.7s	remaining: 6.36s
648:	learn: 6.8022971	total: 11.7s	remaining: 6.34s
649:	learn: 6.8021943	total: 11.7s	remaining: 6.32s
650:	learn: 6.8019294	total: 11.8s	remaining: 6.3s
651:	learn: 6.8018141	total: 11.8s	remaining: 6.29s
652:	learn: 6.8017062	total: 11.8s	remaining: 6.27s
653:	learn: 6.8015695	total: 11.8s	remaining: 6.25s
654:	learn: 6.8015575	total: 11.8s	remaining: 6.23s
655:	learn: 6.8014332	total: 11.8s	remaining: 6.21s
656:	learn: 6.8013339	total: 11.9s	remaining: 6.19s
657:	learn: 6

803:	learn: 6.7908224	total: 14.4s	remaining: 3.52s
804:	learn: 6.7908063	total: 14.5s	remaining: 3.5s
805:	learn: 6.7907427	total: 14.5s	remaining: 3.48s
806:	learn: 6.7906814	total: 14.5s	remaining: 3.47s
807:	learn: 6.7906400	total: 14.5s	remaining: 3.45s
808:	learn: 6.7906352	total: 14.5s	remaining: 3.43s
809:	learn: 6.7905538	total: 14.6s	remaining: 3.42s
810:	learn: 6.7903529	total: 14.6s	remaining: 3.4s
811:	learn: 6.7903324	total: 14.6s	remaining: 3.38s
812:	learn: 6.7903278	total: 14.6s	remaining: 3.36s
813:	learn: 6.7901509	total: 14.6s	remaining: 3.34s
814:	learn: 6.7899538	total: 14.7s	remaining: 3.33s
815:	learn: 6.7899494	total: 14.7s	remaining: 3.31s
816:	learn: 6.7898832	total: 14.7s	remaining: 3.29s
817:	learn: 6.7898158	total: 14.7s	remaining: 3.27s
818:	learn: 6.7897515	total: 14.7s	remaining: 3.25s
819:	learn: 6.7896778	total: 14.7s	remaining: 3.24s
820:	learn: 6.7896312	total: 14.8s	remaining: 3.22s
821:	learn: 6.7895692	total: 14.8s	remaining: 3.2s
822:	learn: 6.7

964:	learn: 6.7817509	total: 17.3s	remaining: 629ms
965:	learn: 6.7817176	total: 17.4s	remaining: 611ms
966:	learn: 6.7816728	total: 17.4s	remaining: 593ms
967:	learn: 6.7816500	total: 17.4s	remaining: 575ms
968:	learn: 6.7815896	total: 17.4s	remaining: 557ms
969:	learn: 6.7815466	total: 17.4s	remaining: 539ms
970:	learn: 6.7815058	total: 17.4s	remaining: 521ms
971:	learn: 6.7814652	total: 17.5s	remaining: 503ms
972:	learn: 6.7814366	total: 17.5s	remaining: 485ms
973:	learn: 6.7813363	total: 17.5s	remaining: 467ms
974:	learn: 6.7813279	total: 17.5s	remaining: 449ms
975:	learn: 6.7813018	total: 17.5s	remaining: 431ms
976:	learn: 6.7812703	total: 17.5s	remaining: 413ms
977:	learn: 6.7812371	total: 17.6s	remaining: 395ms
978:	learn: 6.7811560	total: 17.6s	remaining: 377ms
979:	learn: 6.7810224	total: 17.6s	remaining: 359ms
980:	learn: 6.7809744	total: 17.6s	remaining: 341ms
981:	learn: 6.7809385	total: 17.6s	remaining: 323ms
982:	learn: 6.7809073	total: 17.6s	remaining: 305ms
983:	learn: 

126:	learn: 6.7492904	total: 2.32s	remaining: 15.9s
127:	learn: 6.7484865	total: 2.34s	remaining: 15.9s
128:	learn: 6.7473842	total: 2.36s	remaining: 15.9s
129:	learn: 6.7470441	total: 2.38s	remaining: 15.9s
130:	learn: 6.7467349	total: 2.4s	remaining: 15.9s
131:	learn: 6.7462918	total: 2.41s	remaining: 15.9s
132:	learn: 6.7456719	total: 2.43s	remaining: 15.8s
133:	learn: 6.7452776	total: 2.45s	remaining: 15.8s
134:	learn: 6.7444092	total: 2.46s	remaining: 15.8s
135:	learn: 6.7421122	total: 2.48s	remaining: 15.8s
136:	learn: 6.7418282	total: 2.5s	remaining: 15.7s
137:	learn: 6.7411530	total: 2.52s	remaining: 15.7s
138:	learn: 6.7392701	total: 2.54s	remaining: 15.7s
139:	learn: 6.7382821	total: 2.56s	remaining: 15.7s
140:	learn: 6.7372408	total: 2.58s	remaining: 15.7s
141:	learn: 6.7360046	total: 2.59s	remaining: 15.7s
142:	learn: 6.7334432	total: 2.61s	remaining: 15.6s
143:	learn: 6.7327502	total: 2.62s	remaining: 15.6s
144:	learn: 6.7313365	total: 2.64s	remaining: 15.6s
145:	learn: 6.

292:	learn: 6.6364326	total: 5.21s	remaining: 12.6s
293:	learn: 6.6357146	total: 5.23s	remaining: 12.6s
294:	learn: 6.6350596	total: 5.25s	remaining: 12.5s
295:	learn: 6.6343559	total: 5.26s	remaining: 12.5s
296:	learn: 6.6342823	total: 5.28s	remaining: 12.5s
297:	learn: 6.6336612	total: 5.3s	remaining: 12.5s
298:	learn: 6.6329445	total: 5.32s	remaining: 12.5s
299:	learn: 6.6323554	total: 5.34s	remaining: 12.5s
300:	learn: 6.6318214	total: 5.36s	remaining: 12.4s
301:	learn: 6.6312786	total: 5.37s	remaining: 12.4s
302:	learn: 6.6306999	total: 5.39s	remaining: 12.4s
303:	learn: 6.6302325	total: 5.41s	remaining: 12.4s
304:	learn: 6.6296731	total: 5.43s	remaining: 12.4s
305:	learn: 6.6287625	total: 5.45s	remaining: 12.4s
306:	learn: 6.6285845	total: 5.46s	remaining: 12.3s
307:	learn: 6.6277570	total: 5.48s	remaining: 12.3s
308:	learn: 6.6275870	total: 5.5s	remaining: 12.3s
309:	learn: 6.6275160	total: 5.51s	remaining: 12.3s
310:	learn: 6.6274476	total: 5.53s	remaining: 12.2s
311:	learn: 6.

455:	learn: 6.5849471	total: 8.04s	remaining: 9.6s
456:	learn: 6.5847706	total: 8.06s	remaining: 9.58s
457:	learn: 6.5846718	total: 8.08s	remaining: 9.56s
458:	learn: 6.5842844	total: 8.1s	remaining: 9.55s
459:	learn: 6.5839178	total: 8.12s	remaining: 9.53s
460:	learn: 6.5836858	total: 8.13s	remaining: 9.51s
461:	learn: 6.5836214	total: 8.15s	remaining: 9.49s
462:	learn: 6.5835318	total: 8.17s	remaining: 9.47s
463:	learn: 6.5830901	total: 8.18s	remaining: 9.45s
464:	learn: 6.5828666	total: 8.2s	remaining: 9.43s
465:	learn: 6.5825349	total: 8.21s	remaining: 9.41s
466:	learn: 6.5821861	total: 8.23s	remaining: 9.4s
467:	learn: 6.5820958	total: 8.25s	remaining: 9.38s
468:	learn: 6.5816658	total: 8.27s	remaining: 9.37s
469:	learn: 6.5814503	total: 8.29s	remaining: 9.35s
470:	learn: 6.5809831	total: 8.31s	remaining: 9.33s
471:	learn: 6.5808994	total: 8.33s	remaining: 9.31s
472:	learn: 6.5804668	total: 8.34s	remaining: 9.29s
473:	learn: 6.5801401	total: 8.36s	remaining: 9.27s
474:	learn: 6.58

621:	learn: 6.5542985	total: 10.9s	remaining: 6.63s
622:	learn: 6.5541458	total: 10.9s	remaining: 6.62s
623:	learn: 6.5540861	total: 11s	remaining: 6.6s
624:	learn: 6.5539328	total: 11s	remaining: 6.58s
625:	learn: 6.5537870	total: 11s	remaining: 6.57s
626:	learn: 6.5537075	total: 11s	remaining: 6.55s
627:	learn: 6.5534754	total: 11s	remaining: 6.53s
628:	learn: 6.5533424	total: 11s	remaining: 6.51s
629:	learn: 6.5531706	total: 11.1s	remaining: 6.49s
630:	learn: 6.5530627	total: 11.1s	remaining: 6.48s
631:	learn: 6.5528316	total: 11.1s	remaining: 6.46s
632:	learn: 6.5526283	total: 11.1s	remaining: 6.44s
633:	learn: 6.5525771	total: 11.1s	remaining: 6.42s
634:	learn: 6.5523898	total: 11.1s	remaining: 6.41s
635:	learn: 6.5522725	total: 11.2s	remaining: 6.39s
636:	learn: 6.5521192	total: 11.2s	remaining: 6.37s
637:	learn: 6.5520021	total: 11.2s	remaining: 6.35s
638:	learn: 6.5519261	total: 11.2s	remaining: 6.34s
639:	learn: 6.5518779	total: 11.2s	remaining: 6.32s
640:	learn: 6.5516582	tot

785:	learn: 6.5370394	total: 13.8s	remaining: 3.75s
786:	learn: 6.5369196	total: 13.8s	remaining: 3.73s
787:	learn: 6.5368195	total: 13.8s	remaining: 3.72s
788:	learn: 6.5367948	total: 13.8s	remaining: 3.7s
789:	learn: 6.5366492	total: 13.9s	remaining: 3.68s
790:	learn: 6.5365721	total: 13.9s	remaining: 3.67s
791:	learn: 6.5365162	total: 13.9s	remaining: 3.65s
792:	learn: 6.5365077	total: 13.9s	remaining: 3.63s
793:	learn: 6.5364595	total: 13.9s	remaining: 3.61s
794:	learn: 6.5363027	total: 13.9s	remaining: 3.6s
795:	learn: 6.5362945	total: 14s	remaining: 3.58s
796:	learn: 6.5361939	total: 14s	remaining: 3.56s
797:	learn: 6.5360506	total: 14s	remaining: 3.54s
798:	learn: 6.5359977	total: 14s	remaining: 3.53s
799:	learn: 6.5359488	total: 14s	remaining: 3.51s
800:	learn: 6.5358529	total: 14.1s	remaining: 3.49s
801:	learn: 6.5357995	total: 14.1s	remaining: 3.47s
802:	learn: 6.5357488	total: 14.1s	remaining: 3.46s
803:	learn: 6.5357022	total: 14.1s	remaining: 3.44s
804:	learn: 6.5356731	to

953:	learn: 6.5266311	total: 16.7s	remaining: 804ms
954:	learn: 6.5266232	total: 16.7s	remaining: 786ms
955:	learn: 6.5265606	total: 16.7s	remaining: 769ms
956:	learn: 6.5265394	total: 16.7s	remaining: 751ms
957:	learn: 6.5264617	total: 16.7s	remaining: 734ms
958:	learn: 6.5264413	total: 16.8s	remaining: 717ms
959:	learn: 6.5263340	total: 16.8s	remaining: 699ms
960:	learn: 6.5263183	total: 16.8s	remaining: 682ms
961:	learn: 6.5262523	total: 16.8s	remaining: 664ms
962:	learn: 6.5261552	total: 16.8s	remaining: 647ms
963:	learn: 6.5261457	total: 16.8s	remaining: 629ms
964:	learn: 6.5260585	total: 16.9s	remaining: 612ms
965:	learn: 6.5259708	total: 16.9s	remaining: 594ms
966:	learn: 6.5258777	total: 16.9s	remaining: 577ms
967:	learn: 6.5257737	total: 16.9s	remaining: 559ms
968:	learn: 6.5256999	total: 16.9s	remaining: 542ms
969:	learn: 6.5256275	total: 17s	remaining: 524ms
970:	learn: 6.5255330	total: 17s	remaining: 507ms
971:	learn: 6.5255139	total: 17s	remaining: 489ms
972:	learn: 6.5254

118:	learn: 5.0411863	total: 2.08s	remaining: 15.4s
119:	learn: 5.0396919	total: 2.1s	remaining: 15.4s
120:	learn: 5.0377055	total: 2.12s	remaining: 15.4s
121:	learn: 5.0370780	total: 2.13s	remaining: 15.4s
122:	learn: 5.0355815	total: 2.15s	remaining: 15.3s
123:	learn: 5.0352819	total: 2.17s	remaining: 15.3s
124:	learn: 5.0347731	total: 2.19s	remaining: 15.3s
125:	learn: 5.0344736	total: 2.2s	remaining: 15.3s
126:	learn: 5.0327386	total: 2.22s	remaining: 15.3s
127:	learn: 5.0317559	total: 2.23s	remaining: 15.2s
128:	learn: 5.0314651	total: 2.25s	remaining: 15.2s
129:	learn: 5.0301084	total: 2.27s	remaining: 15.2s
130:	learn: 5.0297421	total: 2.29s	remaining: 15.2s
131:	learn: 5.0293271	total: 2.31s	remaining: 15.2s
132:	learn: 5.0277754	total: 2.33s	remaining: 15.2s
133:	learn: 5.0272233	total: 2.34s	remaining: 15.1s
134:	learn: 5.0268295	total: 2.36s	remaining: 15.1s
135:	learn: 5.0262955	total: 2.38s	remaining: 15.1s
136:	learn: 5.0239594	total: 2.39s	remaining: 15.1s
137:	learn: 5.

285:	learn: 4.9247859	total: 4.98s	remaining: 12.4s
286:	learn: 4.9244943	total: 5s	remaining: 12.4s
287:	learn: 4.9242896	total: 5.02s	remaining: 12.4s
288:	learn: 4.9242184	total: 5.04s	remaining: 12.4s
289:	learn: 4.9241529	total: 5.06s	remaining: 12.4s
290:	learn: 4.9233764	total: 5.08s	remaining: 12.4s
291:	learn: 4.9230086	total: 5.1s	remaining: 12.4s
292:	learn: 4.9229455	total: 5.11s	remaining: 12.3s
293:	learn: 4.9224589	total: 5.13s	remaining: 12.3s
294:	learn: 4.9215378	total: 5.15s	remaining: 12.3s
295:	learn: 4.9214735	total: 5.16s	remaining: 12.3s
296:	learn: 4.9207379	total: 5.18s	remaining: 12.3s
297:	learn: 4.9206790	total: 5.2s	remaining: 12.3s
298:	learn: 4.9203252	total: 5.22s	remaining: 12.2s
299:	learn: 4.9201052	total: 5.24s	remaining: 12.2s
300:	learn: 4.9200484	total: 5.25s	remaining: 12.2s
301:	learn: 4.9193439	total: 5.28s	remaining: 12.2s
302:	learn: 4.9191474	total: 5.3s	remaining: 12.2s
303:	learn: 4.9188072	total: 5.32s	remaining: 12.2s
304:	learn: 4.9187

454:	learn: 4.8611817	total: 8.14s	remaining: 9.75s
455:	learn: 4.8611532	total: 8.16s	remaining: 9.73s
456:	learn: 4.8611256	total: 8.17s	remaining: 9.71s
457:	learn: 4.8608774	total: 8.2s	remaining: 9.7s
458:	learn: 4.8608508	total: 8.21s	remaining: 9.68s
459:	learn: 4.8605022	total: 8.23s	remaining: 9.66s
460:	learn: 4.8604296	total: 8.25s	remaining: 9.64s
461:	learn: 4.8599517	total: 8.26s	remaining: 9.62s
462:	learn: 4.8596727	total: 8.28s	remaining: 9.6s
463:	learn: 4.8594175	total: 8.3s	remaining: 9.58s
464:	learn: 4.8588561	total: 8.31s	remaining: 9.57s
465:	learn: 4.8586382	total: 8.34s	remaining: 9.55s
466:	learn: 4.8585284	total: 8.36s	remaining: 9.54s
467:	learn: 4.8580078	total: 8.38s	remaining: 9.52s
468:	learn: 4.8577405	total: 8.39s	remaining: 9.5s
469:	learn: 4.8576234	total: 8.41s	remaining: 9.48s
470:	learn: 4.8575048	total: 8.43s	remaining: 9.47s
471:	learn: 4.8573101	total: 8.45s	remaining: 9.45s
472:	learn: 4.8569380	total: 8.46s	remaining: 9.43s
473:	learn: 4.856

616:	learn: 4.8274883	total: 10.9s	remaining: 6.79s
617:	learn: 4.8272726	total: 11s	remaining: 6.78s
618:	learn: 4.8271490	total: 11s	remaining: 6.76s
619:	learn: 4.8271355	total: 11s	remaining: 6.74s
620:	learn: 4.8269305	total: 11s	remaining: 6.72s
621:	learn: 4.8266836	total: 11s	remaining: 6.71s
622:	learn: 4.8265829	total: 11.1s	remaining: 6.69s
623:	learn: 4.8265087	total: 11.1s	remaining: 6.67s
624:	learn: 4.8263057	total: 11.1s	remaining: 6.65s
625:	learn: 4.8261132	total: 11.1s	remaining: 6.63s
626:	learn: 4.8260420	total: 11.1s	remaining: 6.61s
627:	learn: 4.8258567	total: 11.1s	remaining: 6.59s
628:	learn: 4.8256783	total: 11.1s	remaining: 6.58s
629:	learn: 4.8255066	total: 11.2s	remaining: 6.56s
630:	learn: 4.8254383	total: 11.2s	remaining: 6.54s
631:	learn: 4.8252582	total: 11.2s	remaining: 6.52s
632:	learn: 4.8251441	total: 11.2s	remaining: 6.5s
633:	learn: 4.8249494	total: 11.2s	remaining: 6.49s
634:	learn: 4.8247729	total: 11.3s	remaining: 6.47s
635:	learn: 4.8247073	t

785:	learn: 4.8065839	total: 13.8s	remaining: 3.77s
786:	learn: 4.8065375	total: 13.9s	remaining: 3.75s
787:	learn: 4.8064843	total: 13.9s	remaining: 3.73s
788:	learn: 4.8063640	total: 13.9s	remaining: 3.71s
789:	learn: 4.8062837	total: 13.9s	remaining: 3.7s
790:	learn: 4.8062594	total: 13.9s	remaining: 3.68s
791:	learn: 4.8062126	total: 13.9s	remaining: 3.66s
792:	learn: 4.8061743	total: 14s	remaining: 3.64s
793:	learn: 4.8060998	total: 14s	remaining: 3.63s
794:	learn: 4.8059829	total: 14s	remaining: 3.61s
795:	learn: 4.8059265	total: 14s	remaining: 3.59s
796:	learn: 4.8058281	total: 14s	remaining: 3.57s
797:	learn: 4.8056830	total: 14.1s	remaining: 3.56s
798:	learn: 4.8055439	total: 14.1s	remaining: 3.54s
799:	learn: 4.8054385	total: 14.1s	remaining: 3.52s
800:	learn: 4.8053870	total: 14.1s	remaining: 3.5s
801:	learn: 4.8052540	total: 14.1s	remaining: 3.48s
802:	learn: 4.8052107	total: 14.1s	remaining: 3.47s
803:	learn: 4.8050833	total: 14.2s	remaining: 3.45s
804:	learn: 4.8049707	to

949:	learn: 4.7969794	total: 16.6s	remaining: 876ms
950:	learn: 4.7969141	total: 16.7s	remaining: 858ms
951:	learn: 4.7968813	total: 16.7s	remaining: 841ms
952:	learn: 4.7968184	total: 16.7s	remaining: 823ms
953:	learn: 4.7967868	total: 16.7s	remaining: 806ms
954:	learn: 4.7967345	total: 16.7s	remaining: 788ms
955:	learn: 4.7966745	total: 16.7s	remaining: 771ms
956:	learn: 4.7966229	total: 16.8s	remaining: 753ms
957:	learn: 4.7964776	total: 16.8s	remaining: 735ms
958:	learn: 4.7964435	total: 16.8s	remaining: 718ms
959:	learn: 4.7963857	total: 16.8s	remaining: 700ms
960:	learn: 4.7963572	total: 16.8s	remaining: 683ms
961:	learn: 4.7962803	total: 16.8s	remaining: 665ms
962:	learn: 4.7962365	total: 16.9s	remaining: 648ms
963:	learn: 4.7961755	total: 16.9s	remaining: 630ms
964:	learn: 4.7960967	total: 16.9s	remaining: 613ms
965:	learn: 4.7960733	total: 16.9s	remaining: 595ms
966:	learn: 4.7959944	total: 16.9s	remaining: 578ms
967:	learn: 4.7959285	total: 16.9s	remaining: 560ms
968:	learn: 

113:	learn: 6.4392440	total: 2.05s	remaining: 15.9s
114:	learn: 6.4354307	total: 2.07s	remaining: 15.9s
115:	learn: 6.4337396	total: 2.08s	remaining: 15.9s
116:	learn: 6.4319732	total: 2.1s	remaining: 15.9s
117:	learn: 6.4309430	total: 2.12s	remaining: 15.9s
118:	learn: 6.4305830	total: 2.14s	remaining: 15.9s
119:	learn: 6.4283391	total: 2.16s	remaining: 15.8s
120:	learn: 6.4262272	total: 2.17s	remaining: 15.8s
121:	learn: 6.4252592	total: 2.19s	remaining: 15.8s
122:	learn: 6.4244277	total: 2.21s	remaining: 15.7s
123:	learn: 6.4234816	total: 2.22s	remaining: 15.7s
124:	learn: 6.4200834	total: 2.24s	remaining: 15.7s
125:	learn: 6.4188939	total: 2.26s	remaining: 15.7s
126:	learn: 6.4172027	total: 2.28s	remaining: 15.7s
127:	learn: 6.4151570	total: 2.29s	remaining: 15.6s
128:	learn: 6.4139391	total: 2.32s	remaining: 15.6s
129:	learn: 6.4130147	total: 2.33s	remaining: 15.6s
130:	learn: 6.4124168	total: 2.35s	remaining: 15.6s
131:	learn: 6.4112852	total: 2.37s	remaining: 15.6s
132:	learn: 6

282:	learn: 6.2913929	total: 4.95s	remaining: 12.5s
283:	learn: 6.2909241	total: 4.96s	remaining: 12.5s
284:	learn: 6.2902770	total: 4.98s	remaining: 12.5s
285:	learn: 6.2900927	total: 5s	remaining: 12.5s
286:	learn: 6.2898840	total: 5.02s	remaining: 12.5s
287:	learn: 6.2894321	total: 5.03s	remaining: 12.4s
288:	learn: 6.2888271	total: 5.05s	remaining: 12.4s
289:	learn: 6.2886386	total: 5.07s	remaining: 12.4s
290:	learn: 6.2884458	total: 5.08s	remaining: 12.4s
291:	learn: 6.2880104	total: 5.1s	remaining: 12.4s
292:	learn: 6.2875908	total: 5.11s	remaining: 12.3s
293:	learn: 6.2874482	total: 5.13s	remaining: 12.3s
294:	learn: 6.2869287	total: 5.15s	remaining: 12.3s
295:	learn: 6.2860975	total: 5.17s	remaining: 12.3s
296:	learn: 6.2851809	total: 5.18s	remaining: 12.3s
297:	learn: 6.2850700	total: 5.2s	remaining: 12.3s
298:	learn: 6.2843069	total: 5.22s	remaining: 12.2s
299:	learn: 6.2838922	total: 5.23s	remaining: 12.2s
300:	learn: 6.2833954	total: 5.25s	remaining: 12.2s
301:	learn: 6.283

447:	learn: 6.2427102	total: 7.79s	remaining: 9.59s
448:	learn: 6.2425651	total: 7.8s	remaining: 9.57s
449:	learn: 6.2424750	total: 7.82s	remaining: 9.56s
450:	learn: 6.2423760	total: 7.84s	remaining: 9.54s
451:	learn: 6.2422920	total: 7.86s	remaining: 9.53s
452:	learn: 6.2420742	total: 7.88s	remaining: 9.51s
453:	learn: 6.2419442	total: 7.9s	remaining: 9.5s
454:	learn: 6.2416645	total: 7.91s	remaining: 9.48s
455:	learn: 6.2411210	total: 7.93s	remaining: 9.46s
456:	learn: 6.2407483	total: 7.95s	remaining: 9.44s
457:	learn: 6.2405096	total: 7.96s	remaining: 9.42s
458:	learn: 6.2404311	total: 7.98s	remaining: 9.4s
459:	learn: 6.2403114	total: 8s	remaining: 9.39s
460:	learn: 6.2401972	total: 8.02s	remaining: 9.38s
461:	learn: 6.2401166	total: 8.04s	remaining: 9.36s
462:	learn: 6.2400261	total: 8.05s	remaining: 9.34s
463:	learn: 6.2397068	total: 8.07s	remaining: 9.32s
464:	learn: 6.2396319	total: 8.09s	remaining: 9.31s
465:	learn: 6.2395415	total: 8.11s	remaining: 9.29s
466:	learn: 6.23935

612:	learn: 6.2165346	total: 10.6s	remaining: 6.72s
613:	learn: 6.2164934	total: 10.7s	remaining: 6.7s
614:	learn: 6.2163194	total: 10.7s	remaining: 6.69s
615:	learn: 6.2162651	total: 10.7s	remaining: 6.67s
616:	learn: 6.2160469	total: 10.7s	remaining: 6.65s
617:	learn: 6.2160265	total: 10.7s	remaining: 6.64s
618:	learn: 6.2159666	total: 10.8s	remaining: 6.62s
619:	learn: 6.2159353	total: 10.8s	remaining: 6.6s
620:	learn: 6.2158251	total: 10.8s	remaining: 6.58s
621:	learn: 6.2158060	total: 10.8s	remaining: 6.56s
622:	learn: 6.2157765	total: 10.8s	remaining: 6.54s
623:	learn: 6.2157197	total: 10.8s	remaining: 6.53s
624:	learn: 6.2155174	total: 10.9s	remaining: 6.51s
625:	learn: 6.2154889	total: 10.9s	remaining: 6.5s
626:	learn: 6.2153314	total: 10.9s	remaining: 6.48s
627:	learn: 6.2152298	total: 10.9s	remaining: 6.46s
628:	learn: 6.2152125	total: 10.9s	remaining: 6.45s
629:	learn: 6.2151782	total: 10.9s	remaining: 6.43s
630:	learn: 6.2151617	total: 11s	remaining: 6.41s
631:	learn: 6.215

775:	learn: 6.2058074	total: 13.5s	remaining: 3.89s
776:	learn: 6.2057277	total: 13.5s	remaining: 3.87s
777:	learn: 6.2056789	total: 13.5s	remaining: 3.86s
778:	learn: 6.2056382	total: 13.5s	remaining: 3.84s
779:	learn: 6.2055232	total: 13.6s	remaining: 3.82s
780:	learn: 6.2054457	total: 13.6s	remaining: 3.8s
781:	learn: 6.2054060	total: 13.6s	remaining: 3.79s
782:	learn: 6.2053867	total: 13.6s	remaining: 3.77s
783:	learn: 6.2053489	total: 13.6s	remaining: 3.75s
784:	learn: 6.2052528	total: 13.6s	remaining: 3.73s
785:	learn: 6.2051789	total: 13.6s	remaining: 3.71s
786:	learn: 6.2051348	total: 13.7s	remaining: 3.7s
787:	learn: 6.2050925	total: 13.7s	remaining: 3.68s
788:	learn: 6.2049960	total: 13.7s	remaining: 3.66s
789:	learn: 6.2048905	total: 13.7s	remaining: 3.65s
790:	learn: 6.2048200	total: 13.7s	remaining: 3.63s
791:	learn: 6.2047529	total: 13.8s	remaining: 3.61s
792:	learn: 6.2046888	total: 13.8s	remaining: 3.59s
793:	learn: 6.2046704	total: 13.8s	remaining: 3.58s
794:	learn: 6.

940:	learn: 6.1988161	total: 16.4s	remaining: 1.03s
941:	learn: 6.1987986	total: 16.4s	remaining: 1.01s
942:	learn: 6.1987792	total: 16.4s	remaining: 992ms
943:	learn: 6.1987591	total: 16.4s	remaining: 975ms
944:	learn: 6.1987305	total: 16.5s	remaining: 958ms
945:	learn: 6.1987083	total: 16.5s	remaining: 941ms
946:	learn: 6.1986952	total: 16.5s	remaining: 924ms
947:	learn: 6.1986756	total: 16.5s	remaining: 906ms
948:	learn: 6.1986218	total: 16.5s	remaining: 889ms
949:	learn: 6.1985614	total: 16.6s	remaining: 871ms
950:	learn: 6.1985504	total: 16.6s	remaining: 854ms
951:	learn: 6.1985218	total: 16.6s	remaining: 837ms
952:	learn: 6.1984929	total: 16.6s	remaining: 819ms
953:	learn: 6.1984687	total: 16.6s	remaining: 802ms
954:	learn: 6.1984208	total: 16.7s	remaining: 785ms
955:	learn: 6.1984154	total: 16.7s	remaining: 768ms
956:	learn: 6.1983890	total: 16.7s	remaining: 750ms
957:	learn: 6.1983785	total: 16.7s	remaining: 733ms
958:	learn: 6.1983622	total: 16.7s	remaining: 715ms
959:	learn: 

105:	learn: 6.8369802	total: 2.06s	remaining: 17.4s
106:	learn: 6.8354195	total: 2.08s	remaining: 17.3s
107:	learn: 6.8340167	total: 2.1s	remaining: 17.3s
108:	learn: 6.8329313	total: 2.12s	remaining: 17.3s
109:	learn: 6.8319022	total: 2.13s	remaining: 17.3s
110:	learn: 6.8309781	total: 2.15s	remaining: 17.2s
111:	learn: 6.8299628	total: 2.17s	remaining: 17.2s
112:	learn: 6.8283575	total: 2.19s	remaining: 17.2s
113:	learn: 6.8270415	total: 2.2s	remaining: 17.1s
114:	learn: 6.8259366	total: 2.22s	remaining: 17.1s
115:	learn: 6.8251446	total: 2.23s	remaining: 17s
116:	learn: 6.8243036	total: 2.25s	remaining: 17s
117:	learn: 6.8230130	total: 2.27s	remaining: 17s
118:	learn: 6.8219363	total: 2.29s	remaining: 17s
119:	learn: 6.8202242	total: 2.31s	remaining: 16.9s
120:	learn: 6.8192034	total: 2.33s	remaining: 16.9s
121:	learn: 6.8182732	total: 2.35s	remaining: 16.9s
122:	learn: 6.8174143	total: 2.37s	remaining: 16.9s
123:	learn: 6.8166547	total: 2.38s	remaining: 16.8s
124:	learn: 6.8159732	

266:	learn: 6.7136075	total: 4.96s	remaining: 13.6s
267:	learn: 6.7134898	total: 4.97s	remaining: 13.6s
268:	learn: 6.7124366	total: 4.99s	remaining: 13.6s
269:	learn: 6.7117610	total: 5.01s	remaining: 13.5s
270:	learn: 6.7116480	total: 5.03s	remaining: 13.5s
271:	learn: 6.7112600	total: 5.05s	remaining: 13.5s
272:	learn: 6.7111512	total: 5.06s	remaining: 13.5s
273:	learn: 6.7107556	total: 5.08s	remaining: 13.5s
274:	learn: 6.7100093	total: 5.09s	remaining: 13.4s
275:	learn: 6.7093817	total: 5.11s	remaining: 13.4s
276:	learn: 6.7092788	total: 5.13s	remaining: 13.4s
277:	learn: 6.7091799	total: 5.14s	remaining: 13.4s
278:	learn: 6.7082626	total: 5.16s	remaining: 13.3s
279:	learn: 6.7078107	total: 5.18s	remaining: 13.3s
280:	learn: 6.7074481	total: 5.2s	remaining: 13.3s
281:	learn: 6.7068650	total: 5.22s	remaining: 13.3s
282:	learn: 6.7065156	total: 5.23s	remaining: 13.3s
283:	learn: 6.7059550	total: 5.25s	remaining: 13.2s
284:	learn: 6.7057257	total: 5.26s	remaining: 13.2s
285:	learn: 6

426:	learn: 6.6577642	total: 7.79s	remaining: 10.5s
427:	learn: 6.6576198	total: 7.81s	remaining: 10.4s
428:	learn: 6.6574598	total: 7.83s	remaining: 10.4s
429:	learn: 6.6574171	total: 7.85s	remaining: 10.4s
430:	learn: 6.6573497	total: 7.87s	remaining: 10.4s
431:	learn: 6.6571955	total: 7.88s	remaining: 10.4s
432:	learn: 6.6567807	total: 7.9s	remaining: 10.3s
433:	learn: 6.6564640	total: 7.92s	remaining: 10.3s
434:	learn: 6.6563706	total: 7.93s	remaining: 10.3s
435:	learn: 6.6562200	total: 7.95s	remaining: 10.3s
436:	learn: 6.6561097	total: 7.96s	remaining: 10.3s
437:	learn: 6.6556722	total: 7.98s	remaining: 10.2s
438:	learn: 6.6555887	total: 8s	remaining: 10.2s
439:	learn: 6.6554653	total: 8.02s	remaining: 10.2s
440:	learn: 6.6553852	total: 8.04s	remaining: 10.2s
441:	learn: 6.6552378	total: 8.06s	remaining: 10.2s
442:	learn: 6.6549463	total: 8.07s	remaining: 10.2s
443:	learn: 6.6546105	total: 8.09s	remaining: 10.1s
444:	learn: 6.6545731	total: 8.11s	remaining: 10.1s
445:	learn: 6.65

590:	learn: 6.6247998	total: 10.7s	remaining: 7.4s
591:	learn: 6.6247650	total: 10.7s	remaining: 7.38s
592:	learn: 6.6246877	total: 10.7s	remaining: 7.36s
593:	learn: 6.6245568	total: 10.7s	remaining: 7.34s
594:	learn: 6.6245234	total: 10.8s	remaining: 7.33s
595:	learn: 6.6244914	total: 10.8s	remaining: 7.31s
596:	learn: 6.6243321	total: 10.8s	remaining: 7.29s
597:	learn: 6.6243014	total: 10.8s	remaining: 7.27s
598:	learn: 6.6240944	total: 10.8s	remaining: 7.25s
599:	learn: 6.6240350	total: 10.8s	remaining: 7.23s
600:	learn: 6.6240056	total: 10.9s	remaining: 7.21s
601:	learn: 6.6239773	total: 10.9s	remaining: 7.2s
602:	learn: 6.6239168	total: 10.9s	remaining: 7.18s
603:	learn: 6.6237498	total: 10.9s	remaining: 7.16s
604:	learn: 6.6235455	total: 10.9s	remaining: 7.15s
605:	learn: 6.6234380	total: 11s	remaining: 7.13s
606:	learn: 6.6234109	total: 11s	remaining: 7.11s
607:	learn: 6.6233848	total: 11s	remaining: 7.09s
608:	learn: 6.6232693	total: 11s	remaining: 7.07s
609:	learn: 6.6230820	

753:	learn: 6.6105947	total: 13.7s	remaining: 4.46s
754:	learn: 6.6105130	total: 13.7s	remaining: 4.45s
755:	learn: 6.6104259	total: 13.7s	remaining: 4.43s
756:	learn: 6.6103480	total: 13.7s	remaining: 4.41s
757:	learn: 6.6102407	total: 13.8s	remaining: 4.39s
758:	learn: 6.6101489	total: 13.8s	remaining: 4.37s
759:	learn: 6.6099850	total: 13.8s	remaining: 4.35s
760:	learn: 6.6098607	total: 13.8s	remaining: 4.34s
761:	learn: 6.6097439	total: 13.8s	remaining: 4.32s
762:	learn: 6.6096666	total: 13.9s	remaining: 4.3s
763:	learn: 6.6096266	total: 13.9s	remaining: 4.29s
764:	learn: 6.6095271	total: 13.9s	remaining: 4.27s
765:	learn: 6.6094691	total: 13.9s	remaining: 4.25s
766:	learn: 6.6094360	total: 13.9s	remaining: 4.23s
767:	learn: 6.6093553	total: 14s	remaining: 4.22s
768:	learn: 6.6093180	total: 14s	remaining: 4.2s
769:	learn: 6.6091838	total: 14s	remaining: 4.18s
770:	learn: 6.6090183	total: 14s	remaining: 4.16s
771:	learn: 6.6089580	total: 14s	remaining: 4.14s
772:	learn: 6.6088703	to

913:	learn: 6.6003222	total: 16.6s	remaining: 1.56s
914:	learn: 6.6003135	total: 16.6s	remaining: 1.54s
915:	learn: 6.6002606	total: 16.6s	remaining: 1.52s
916:	learn: 6.6001643	total: 16.6s	remaining: 1.5s
917:	learn: 6.6001185	total: 16.6s	remaining: 1.49s
918:	learn: 6.6000968	total: 16.7s	remaining: 1.47s
919:	learn: 6.6000085	total: 16.7s	remaining: 1.45s
920:	learn: 6.5999502	total: 16.7s	remaining: 1.43s
921:	learn: 6.5998956	total: 16.7s	remaining: 1.41s
922:	learn: 6.5998876	total: 16.7s	remaining: 1.39s
923:	learn: 6.5998663	total: 16.7s	remaining: 1.38s
924:	learn: 6.5998204	total: 16.8s	remaining: 1.36s
925:	learn: 6.5997822	total: 16.8s	remaining: 1.34s
926:	learn: 6.5996789	total: 16.8s	remaining: 1.32s
927:	learn: 6.5996148	total: 16.8s	remaining: 1.3s
928:	learn: 6.5995890	total: 16.8s	remaining: 1.29s
929:	learn: 6.5995351	total: 16.9s	remaining: 1.27s
930:	learn: 6.5994666	total: 16.9s	remaining: 1.25s
931:	learn: 6.5994418	total: 16.9s	remaining: 1.23s
932:	learn: 6.

74:	learn: 7.0492705	total: 1.39s	remaining: 17.2s
75:	learn: 7.0489398	total: 1.41s	remaining: 17.1s
76:	learn: 7.0464889	total: 1.43s	remaining: 17.1s
77:	learn: 7.0450842	total: 1.44s	remaining: 17.1s
78:	learn: 7.0429382	total: 1.46s	remaining: 17s
79:	learn: 7.0409510	total: 1.48s	remaining: 17.1s
80:	learn: 7.0392539	total: 1.5s	remaining: 17s
81:	learn: 7.0378100	total: 1.52s	remaining: 17s
82:	learn: 7.0362184	total: 1.53s	remaining: 16.9s
83:	learn: 7.0355162	total: 1.55s	remaining: 16.9s
84:	learn: 7.0341491	total: 1.57s	remaining: 16.9s
85:	learn: 7.0328384	total: 1.59s	remaining: 16.9s
86:	learn: 7.0312717	total: 1.61s	remaining: 16.9s
87:	learn: 7.0297035	total: 1.62s	remaining: 16.8s
88:	learn: 7.0283035	total: 1.64s	remaining: 16.8s
89:	learn: 7.0274764	total: 1.66s	remaining: 16.8s
90:	learn: 7.0262182	total: 1.67s	remaining: 16.7s
91:	learn: 7.0251099	total: 1.69s	remaining: 16.7s
92:	learn: 7.0234259	total: 1.71s	remaining: 16.6s
93:	learn: 7.0226729	total: 1.73s	rema

238:	learn: 6.9216594	total: 4.22s	remaining: 13.4s
239:	learn: 6.9215873	total: 4.24s	remaining: 13.4s
240:	learn: 6.9199927	total: 4.26s	remaining: 13.4s
241:	learn: 6.9194004	total: 4.28s	remaining: 13.4s
242:	learn: 6.9183887	total: 4.3s	remaining: 13.4s
243:	learn: 6.9183194	total: 4.32s	remaining: 13.4s
244:	learn: 6.9177200	total: 4.33s	remaining: 13.4s
245:	learn: 6.9162116	total: 4.35s	remaining: 13.3s
246:	learn: 6.9157973	total: 4.37s	remaining: 13.3s
247:	learn: 6.9143711	total: 4.38s	remaining: 13.3s
248:	learn: 6.9134864	total: 4.4s	remaining: 13.3s
249:	learn: 6.9129118	total: 4.41s	remaining: 13.2s
250:	learn: 6.9128451	total: 4.43s	remaining: 13.2s
251:	learn: 6.9115173	total: 4.45s	remaining: 13.2s
252:	learn: 6.9111205	total: 4.47s	remaining: 13.2s
253:	learn: 6.9107242	total: 4.49s	remaining: 13.2s
254:	learn: 6.9094681	total: 4.5s	remaining: 13.2s
255:	learn: 6.9087027	total: 4.52s	remaining: 13.1s
256:	learn: 6.9081518	total: 4.54s	remaining: 13.1s
257:	learn: 6.9

406:	learn: 6.8478604	total: 7.11s	remaining: 10.4s
407:	learn: 6.8476435	total: 7.13s	remaining: 10.3s
408:	learn: 6.8472928	total: 7.15s	remaining: 10.3s
409:	learn: 6.8469451	total: 7.16s	remaining: 10.3s
410:	learn: 6.8464861	total: 7.18s	remaining: 10.3s
411:	learn: 6.8462769	total: 7.2s	remaining: 10.3s
412:	learn: 6.8458940	total: 7.22s	remaining: 10.3s
413:	learn: 6.8456923	total: 7.23s	remaining: 10.2s
414:	learn: 6.8453559	total: 7.25s	remaining: 10.2s
415:	learn: 6.8450456	total: 7.26s	remaining: 10.2s
416:	learn: 6.8448957	total: 7.29s	remaining: 10.2s
417:	learn: 6.8446613	total: 7.31s	remaining: 10.2s
418:	learn: 6.8443439	total: 7.33s	remaining: 10.2s
419:	learn: 6.8441602	total: 7.34s	remaining: 10.1s
420:	learn: 6.8439140	total: 7.36s	remaining: 10.1s
421:	learn: 6.8436805	total: 7.38s	remaining: 10.1s
422:	learn: 6.8434923	total: 7.39s	remaining: 10.1s
423:	learn: 6.8431049	total: 7.41s	remaining: 10.1s
424:	learn: 6.8429764	total: 7.43s	remaining: 10.1s
425:	learn: 6

569:	learn: 6.8143670	total: 9.97s	remaining: 7.52s
570:	learn: 6.8139615	total: 9.99s	remaining: 7.51s
571:	learn: 6.8138435	total: 10s	remaining: 7.49s
572:	learn: 6.8136562	total: 10s	remaining: 7.47s
573:	learn: 6.8135079	total: 10s	remaining: 7.46s
574:	learn: 6.8133665	total: 10.1s	remaining: 7.44s
575:	learn: 6.8131922	total: 10.1s	remaining: 7.42s
576:	learn: 6.8130138	total: 10.1s	remaining: 7.4s
577:	learn: 6.8128396	total: 10.1s	remaining: 7.38s
578:	learn: 6.8127341	total: 10.1s	remaining: 7.36s
579:	learn: 6.8127211	total: 10.1s	remaining: 7.34s
580:	learn: 6.8125340	total: 10.2s	remaining: 7.33s
581:	learn: 6.8123378	total: 10.2s	remaining: 7.31s
582:	learn: 6.8122071	total: 10.2s	remaining: 7.29s
583:	learn: 6.8121655	total: 10.2s	remaining: 7.28s
584:	learn: 6.8119954	total: 10.2s	remaining: 7.26s
585:	learn: 6.8118346	total: 10.3s	remaining: 7.24s
586:	learn: 6.8116328	total: 10.3s	remaining: 7.22s
587:	learn: 6.8114944	total: 10.3s	remaining: 7.2s
588:	learn: 6.811359

729:	learn: 6.7951815	total: 12.8s	remaining: 4.75s
730:	learn: 6.7951185	total: 12.9s	remaining: 4.73s
731:	learn: 6.7950419	total: 12.9s	remaining: 4.71s
732:	learn: 6.7950343	total: 12.9s	remaining: 4.7s
733:	learn: 6.7949741	total: 12.9s	remaining: 4.68s
734:	learn: 6.7949678	total: 12.9s	remaining: 4.66s
735:	learn: 6.7948812	total: 12.9s	remaining: 4.64s
736:	learn: 6.7948160	total: 13s	remaining: 4.62s
737:	learn: 6.7947131	total: 13s	remaining: 4.61s
738:	learn: 6.7946683	total: 13s	remaining: 4.59s
739:	learn: 6.7945956	total: 13s	remaining: 4.57s
740:	learn: 6.7945255	total: 13s	remaining: 4.55s
741:	learn: 6.7945024	total: 13s	remaining: 4.54s
742:	learn: 6.7943128	total: 13.1s	remaining: 4.52s
743:	learn: 6.7942453	total: 13.1s	remaining: 4.5s
744:	learn: 6.7941650	total: 13.1s	remaining: 4.48s
745:	learn: 6.7940809	total: 13.1s	remaining: 4.47s
746:	learn: 6.7939295	total: 13.1s	remaining: 4.45s
747:	learn: 6.7938347	total: 13.2s	remaining: 4.43s
748:	learn: 6.7938124	tota

889:	learn: 6.7857143	total: 15.6s	remaining: 1.93s
890:	learn: 6.7855707	total: 15.7s	remaining: 1.92s
891:	learn: 6.7855389	total: 15.7s	remaining: 1.9s
892:	learn: 6.7855355	total: 15.7s	remaining: 1.88s
893:	learn: 6.7854865	total: 15.7s	remaining: 1.86s
894:	learn: 6.7854450	total: 15.7s	remaining: 1.84s
895:	learn: 6.7853867	total: 15.7s	remaining: 1.83s
896:	learn: 6.7853423	total: 15.8s	remaining: 1.81s
897:	learn: 6.7853390	total: 15.8s	remaining: 1.79s
898:	learn: 6.7852870	total: 15.8s	remaining: 1.77s
899:	learn: 6.7852574	total: 15.8s	remaining: 1.76s
900:	learn: 6.7852286	total: 15.8s	remaining: 1.74s
901:	learn: 6.7851021	total: 15.8s	remaining: 1.72s
902:	learn: 6.7850630	total: 15.9s	remaining: 1.7s
903:	learn: 6.7850250	total: 15.9s	remaining: 1.69s
904:	learn: 6.7849710	total: 15.9s	remaining: 1.67s
905:	learn: 6.7849608	total: 15.9s	remaining: 1.65s
906:	learn: 6.7848135	total: 15.9s	remaining: 1.63s
907:	learn: 6.7848101	total: 15.9s	remaining: 1.61s
908:	learn: 6.

53:	learn: 6.9068883	total: 1.01s	remaining: 17.7s
54:	learn: 6.8993317	total: 1.03s	remaining: 17.6s
55:	learn: 6.8938335	total: 1.04s	remaining: 17.6s
56:	learn: 6.8890308	total: 1.06s	remaining: 17.6s
57:	learn: 6.8860029	total: 1.08s	remaining: 17.6s
58:	learn: 6.8815812	total: 1.1s	remaining: 17.5s
59:	learn: 6.8763291	total: 1.12s	remaining: 17.5s
60:	learn: 6.8705655	total: 1.13s	remaining: 17.4s
61:	learn: 6.8685487	total: 1.15s	remaining: 17.4s
62:	learn: 6.8658558	total: 1.17s	remaining: 17.4s
63:	learn: 6.8634334	total: 1.19s	remaining: 17.4s
64:	learn: 6.8604048	total: 1.21s	remaining: 17.4s
65:	learn: 6.8574617	total: 1.23s	remaining: 17.4s
66:	learn: 6.8555724	total: 1.24s	remaining: 17.3s
67:	learn: 6.8524852	total: 1.26s	remaining: 17.3s
68:	learn: 6.8502944	total: 1.28s	remaining: 17.3s
69:	learn: 6.8481950	total: 1.3s	remaining: 17.2s
70:	learn: 6.8452652	total: 1.31s	remaining: 17.2s
71:	learn: 6.8422253	total: 1.33s	remaining: 17.1s
72:	learn: 6.8369044	total: 1.34s

223:	learn: 6.6775678	total: 4.12s	remaining: 14.3s
224:	learn: 6.6774199	total: 4.14s	remaining: 14.3s
225:	learn: 6.6772037	total: 4.16s	remaining: 14.3s
226:	learn: 6.6760845	total: 4.18s	remaining: 14.3s
227:	learn: 6.6751932	total: 4.21s	remaining: 14.3s
228:	learn: 6.6740699	total: 4.23s	remaining: 14.2s
229:	learn: 6.6739274	total: 4.25s	remaining: 14.2s
230:	learn: 6.6729413	total: 4.27s	remaining: 14.2s
231:	learn: 6.6728040	total: 4.28s	remaining: 14.2s
232:	learn: 6.6725983	total: 4.3s	remaining: 14.2s
233:	learn: 6.6724660	total: 4.33s	remaining: 14.2s
234:	learn: 6.6714251	total: 4.35s	remaining: 14.2s
235:	learn: 6.6703320	total: 4.37s	remaining: 14.1s
236:	learn: 6.6702046	total: 4.39s	remaining: 14.1s
237:	learn: 6.6688788	total: 4.41s	remaining: 14.1s
238:	learn: 6.6687559	total: 4.42s	remaining: 14.1s
239:	learn: 6.6686374	total: 4.44s	remaining: 14.1s
240:	learn: 6.6685232	total: 4.46s	remaining: 14.1s
241:	learn: 6.6672406	total: 4.48s	remaining: 14s
242:	learn: 6.6

392:	learn: 6.6015927	total: 7.42s	remaining: 11.5s
393:	learn: 6.6013681	total: 7.43s	remaining: 11.4s
394:	learn: 6.6012064	total: 7.45s	remaining: 11.4s
395:	learn: 6.6011752	total: 7.47s	remaining: 11.4s
396:	learn: 6.6005695	total: 7.49s	remaining: 11.4s
397:	learn: 6.6005300	total: 7.5s	remaining: 11.4s
398:	learn: 6.6004924	total: 7.52s	remaining: 11.3s
399:	learn: 6.6002742	total: 7.54s	remaining: 11.3s
400:	learn: 6.5996971	total: 7.55s	remaining: 11.3s
401:	learn: 6.5993987	total: 7.57s	remaining: 11.3s
402:	learn: 6.5988546	total: 7.59s	remaining: 11.2s
403:	learn: 6.5983728	total: 7.6s	remaining: 11.2s
404:	learn: 6.5983450	total: 7.62s	remaining: 11.2s
405:	learn: 6.5980992	total: 7.64s	remaining: 11.2s
406:	learn: 6.5980644	total: 7.66s	remaining: 11.2s
407:	learn: 6.5977828	total: 7.68s	remaining: 11.1s
408:	learn: 6.5975794	total: 7.69s	remaining: 11.1s
409:	learn: 6.5973435	total: 7.71s	remaining: 11.1s
410:	learn: 6.5970025	total: 7.72s	remaining: 11.1s
411:	learn: 6.

553:	learn: 6.5648728	total: 10.2s	remaining: 8.25s
554:	learn: 6.5645885	total: 10.3s	remaining: 8.23s
555:	learn: 6.5643021	total: 10.3s	remaining: 8.21s
556:	learn: 6.5640163	total: 10.3s	remaining: 8.2s
557:	learn: 6.5638352	total: 10.3s	remaining: 8.18s
558:	learn: 6.5637781	total: 10.3s	remaining: 8.16s
559:	learn: 6.5636569	total: 10.4s	remaining: 8.14s
560:	learn: 6.5636029	total: 10.4s	remaining: 8.12s
561:	learn: 6.5635705	total: 10.4s	remaining: 8.1s
562:	learn: 6.5635195	total: 10.4s	remaining: 8.08s
563:	learn: 6.5632482	total: 10.4s	remaining: 8.06s
564:	learn: 6.5629428	total: 10.4s	remaining: 8.04s
565:	learn: 6.5627099	total: 10.5s	remaining: 8.02s
566:	learn: 6.5624864	total: 10.5s	remaining: 8s
567:	learn: 6.5622080	total: 10.5s	remaining: 7.99s
568:	learn: 6.5619951	total: 10.5s	remaining: 7.97s
569:	learn: 6.5619040	total: 10.5s	remaining: 7.95s
570:	learn: 6.5617028	total: 10.6s	remaining: 7.93s
571:	learn: 6.5615835	total: 10.6s	remaining: 7.91s
572:	learn: 6.561

717:	learn: 6.5429735	total: 13.1s	remaining: 5.15s
718:	learn: 6.5428563	total: 13.1s	remaining: 5.14s
719:	learn: 6.5428153	total: 13.2s	remaining: 5.12s
720:	learn: 6.5428036	total: 13.2s	remaining: 5.1s
721:	learn: 6.5427614	total: 13.2s	remaining: 5.08s
722:	learn: 6.5425614	total: 13.2s	remaining: 5.06s
723:	learn: 6.5424313	total: 13.2s	remaining: 5.04s
724:	learn: 6.5424051	total: 13.2s	remaining: 5.02s
725:	learn: 6.5422650	total: 13.3s	remaining: 5s
726:	learn: 6.5422340	total: 13.3s	remaining: 4.99s
727:	learn: 6.5420568	total: 13.3s	remaining: 4.97s
728:	learn: 6.5419960	total: 13.3s	remaining: 4.95s
729:	learn: 6.5419847	total: 13.3s	remaining: 4.93s
730:	learn: 6.5418019	total: 13.4s	remaining: 4.91s
731:	learn: 6.5416390	total: 13.4s	remaining: 4.89s
732:	learn: 6.5414831	total: 13.4s	remaining: 4.88s
733:	learn: 6.5413285	total: 13.4s	remaining: 4.86s
734:	learn: 6.5413034	total: 13.4s	remaining: 4.84s
735:	learn: 6.5412084	total: 13.4s	remaining: 4.82s
736:	learn: 6.54

880:	learn: 6.5300071	total: 16s	remaining: 2.16s
881:	learn: 6.5299778	total: 16s	remaining: 2.14s
882:	learn: 6.5298890	total: 16s	remaining: 2.13s
883:	learn: 6.5298075	total: 16.1s	remaining: 2.11s
884:	learn: 6.5297704	total: 16.1s	remaining: 2.09s
885:	learn: 6.5296178	total: 16.1s	remaining: 2.07s
886:	learn: 6.5295898	total: 16.1s	remaining: 2.05s
887:	learn: 6.5295058	total: 16.1s	remaining: 2.04s
888:	learn: 6.5294705	total: 16.2s	remaining: 2.02s
889:	learn: 6.5293962	total: 16.2s	remaining: 2s
890:	learn: 6.5293178	total: 16.2s	remaining: 1.98s
891:	learn: 6.5292451	total: 16.2s	remaining: 1.96s
892:	learn: 6.5291754	total: 16.2s	remaining: 1.94s
893:	learn: 6.5291414	total: 16.2s	remaining: 1.93s
894:	learn: 6.5291139	total: 16.3s	remaining: 1.91s
895:	learn: 6.5291012	total: 16.3s	remaining: 1.89s
896:	learn: 6.5290658	total: 16.3s	remaining: 1.87s
897:	learn: 6.5289566	total: 16.3s	remaining: 1.85s
898:	learn: 6.5288686	total: 16.3s	remaining: 1.83s
899:	learn: 6.5288428

41:	learn: 5.2425243	total: 777ms	remaining: 17.7s
42:	learn: 5.2341612	total: 795ms	remaining: 17.7s
43:	learn: 5.2263510	total: 814ms	remaining: 17.7s
44:	learn: 5.2181417	total: 833ms	remaining: 17.7s
45:	learn: 5.2099412	total: 856ms	remaining: 17.8s
46:	learn: 5.2020529	total: 875ms	remaining: 17.7s
47:	learn: 5.1944145	total: 891ms	remaining: 17.7s
48:	learn: 5.1885508	total: 907ms	remaining: 17.6s
49:	learn: 5.1827032	total: 923ms	remaining: 17.5s
50:	learn: 5.1779329	total: 940ms	remaining: 17.5s
51:	learn: 5.1716996	total: 956ms	remaining: 17.4s
52:	learn: 5.1666867	total: 973ms	remaining: 17.4s
53:	learn: 5.1629893	total: 995ms	remaining: 17.4s
54:	learn: 5.1594392	total: 1.01s	remaining: 17.4s
55:	learn: 5.1560960	total: 1.03s	remaining: 17.3s
56:	learn: 5.1529281	total: 1.05s	remaining: 17.3s
57:	learn: 5.1507472	total: 1.06s	remaining: 17.3s
58:	learn: 5.1474895	total: 1.08s	remaining: 17.2s
59:	learn: 5.1440584	total: 1.1s	remaining: 17.2s
60:	learn: 5.1409051	total: 1.11

206:	learn: 4.9680174	total: 3.67s	remaining: 14.1s
207:	learn: 4.9669549	total: 3.69s	remaining: 14s
208:	learn: 4.9660074	total: 3.7s	remaining: 14s
209:	learn: 4.9657943	total: 3.72s	remaining: 14s
210:	learn: 4.9654878	total: 3.74s	remaining: 14s
211:	learn: 4.9644609	total: 3.76s	remaining: 14s
212:	learn: 4.9635637	total: 3.78s	remaining: 14s
213:	learn: 4.9633603	total: 3.79s	remaining: 13.9s
214:	learn: 4.9622940	total: 3.81s	remaining: 13.9s
215:	learn: 4.9620996	total: 3.83s	remaining: 13.9s
216:	learn: 4.9611137	total: 3.84s	remaining: 13.9s
217:	learn: 4.9601159	total: 3.86s	remaining: 13.8s
218:	learn: 4.9598247	total: 3.88s	remaining: 13.8s
219:	learn: 4.9596400	total: 3.9s	remaining: 13.8s
220:	learn: 4.9593621	total: 3.91s	remaining: 13.8s
221:	learn: 4.9591865	total: 3.93s	remaining: 13.8s
222:	learn: 4.9584549	total: 3.95s	remaining: 13.8s
223:	learn: 4.9582867	total: 3.97s	remaining: 13.7s
224:	learn: 4.9580223	total: 3.98s	remaining: 13.7s
225:	learn: 4.9578622	tota

373:	learn: 4.8858064	total: 6.52s	remaining: 10.9s
374:	learn: 4.8857648	total: 6.54s	remaining: 10.9s
375:	learn: 4.8853608	total: 6.56s	remaining: 10.9s
376:	learn: 4.8848738	total: 6.57s	remaining: 10.9s
377:	learn: 4.8844301	total: 6.59s	remaining: 10.8s
378:	learn: 4.8841976	total: 6.61s	remaining: 10.8s
379:	learn: 4.8840399	total: 6.63s	remaining: 10.8s
380:	learn: 4.8839998	total: 6.65s	remaining: 10.8s
381:	learn: 4.8839580	total: 6.66s	remaining: 10.8s
382:	learn: 4.8833567	total: 6.68s	remaining: 10.8s
383:	learn: 4.8827419	total: 6.7s	remaining: 10.7s
384:	learn: 4.8823284	total: 6.72s	remaining: 10.7s
385:	learn: 4.8819946	total: 6.74s	remaining: 10.7s
386:	learn: 4.8817752	total: 6.75s	remaining: 10.7s
387:	learn: 4.8813894	total: 6.77s	remaining: 10.7s
388:	learn: 4.8810195	total: 6.79s	remaining: 10.7s
389:	learn: 4.8808389	total: 6.8s	remaining: 10.6s
390:	learn: 4.8804263	total: 6.82s	remaining: 10.6s
391:	learn: 4.8802768	total: 6.83s	remaining: 10.6s
392:	learn: 4.

534:	learn: 4.8421468	total: 9.39s	remaining: 8.16s
535:	learn: 4.8420461	total: 9.41s	remaining: 8.14s
536:	learn: 4.8418631	total: 9.43s	remaining: 8.13s
537:	learn: 4.8414989	total: 9.45s	remaining: 8.11s
538:	learn: 4.8413592	total: 9.47s	remaining: 8.1s
539:	learn: 4.8413090	total: 9.48s	remaining: 8.08s
540:	learn: 4.8409316	total: 9.5s	remaining: 8.06s
541:	learn: 4.8408423	total: 9.52s	remaining: 8.04s
542:	learn: 4.8405989	total: 9.53s	remaining: 8.02s
543:	learn: 4.8405806	total: 9.54s	remaining: 8s
544:	learn: 4.8403530	total: 9.56s	remaining: 7.98s
545:	learn: 4.8403053	total: 9.57s	remaining: 7.96s
546:	learn: 4.8402065	total: 9.6s	remaining: 7.95s
547:	learn: 4.8399487	total: 9.61s	remaining: 7.93s
548:	learn: 4.8397294	total: 9.63s	remaining: 7.91s
549:	learn: 4.8396086	total: 9.65s	remaining: 7.9s
550:	learn: 4.8394073	total: 9.67s	remaining: 7.88s
551:	learn: 4.8393124	total: 9.69s	remaining: 7.87s
552:	learn: 4.8391160	total: 9.71s	remaining: 7.85s
553:	learn: 4.83887

701:	learn: 4.8157673	total: 12.3s	remaining: 5.21s
702:	learn: 4.8156329	total: 12.3s	remaining: 5.19s
703:	learn: 4.8153476	total: 12.3s	remaining: 5.17s
704:	learn: 4.8152529	total: 12.3s	remaining: 5.16s
705:	learn: 4.8151646	total: 12.3s	remaining: 5.14s
706:	learn: 4.8150751	total: 12.4s	remaining: 5.12s
707:	learn: 4.8149781	total: 12.4s	remaining: 5.11s
708:	learn: 4.8148319	total: 12.4s	remaining: 5.09s
709:	learn: 4.8147580	total: 12.4s	remaining: 5.07s
710:	learn: 4.8146451	total: 12.4s	remaining: 5.05s
711:	learn: 4.8145397	total: 12.4s	remaining: 5.03s
712:	learn: 4.8144171	total: 12.5s	remaining: 5.02s
713:	learn: 4.8143651	total: 12.5s	remaining: 5s
714:	learn: 4.8142471	total: 12.5s	remaining: 4.98s
715:	learn: 4.8141289	total: 12.5s	remaining: 4.96s
716:	learn: 4.8139972	total: 12.5s	remaining: 4.95s
717:	learn: 4.8138597	total: 12.6s	remaining: 4.93s
718:	learn: 4.8137905	total: 12.6s	remaining: 4.91s
719:	learn: 4.8137085	total: 12.6s	remaining: 4.89s
720:	learn: 4.8

866:	learn: 4.8011413	total: 15.2s	remaining: 2.33s
867:	learn: 4.8010718	total: 15.2s	remaining: 2.31s
868:	learn: 4.8009956	total: 15.2s	remaining: 2.29s
869:	learn: 4.8009803	total: 15.2s	remaining: 2.28s
870:	learn: 4.8009530	total: 15.3s	remaining: 2.26s
871:	learn: 4.8008861	total: 15.3s	remaining: 2.24s
872:	learn: 4.8008136	total: 15.3s	remaining: 2.22s
873:	learn: 4.8007992	total: 15.3s	remaining: 2.21s
874:	learn: 4.8007344	total: 15.3s	remaining: 2.19s
875:	learn: 4.8006631	total: 15.3s	remaining: 2.17s
876:	learn: 4.8006585	total: 15.3s	remaining: 2.15s
877:	learn: 4.8005358	total: 15.4s	remaining: 2.13s
878:	learn: 4.8004017	total: 15.4s	remaining: 2.12s
879:	learn: 4.8003034	total: 15.4s	remaining: 2.1s
880:	learn: 4.8002621	total: 15.4s	remaining: 2.08s
881:	learn: 4.8001391	total: 15.4s	remaining: 2.06s
882:	learn: 4.8000302	total: 15.5s	remaining: 2.05s
883:	learn: 4.7999917	total: 15.5s	remaining: 2.03s
884:	learn: 4.7999019	total: 15.5s	remaining: 2.01s
885:	learn: 4

34:	learn: 6.6906637	total: 663ms	remaining: 18.3s
35:	learn: 6.6814317	total: 682ms	remaining: 18.3s
36:	learn: 6.6720977	total: 702ms	remaining: 18.3s
37:	learn: 6.6641209	total: 722ms	remaining: 18.3s
38:	learn: 6.6561902	total: 740ms	remaining: 18.2s
39:	learn: 6.6501984	total: 759ms	remaining: 18.2s
40:	learn: 6.6436998	total: 777ms	remaining: 18.2s
41:	learn: 6.6379361	total: 795ms	remaining: 18.1s
42:	learn: 6.6310515	total: 810ms	remaining: 18s
43:	learn: 6.6240707	total: 829ms	remaining: 18s
44:	learn: 6.6166898	total: 847ms	remaining: 18s
45:	learn: 6.6103050	total: 872ms	remaining: 18.1s
46:	learn: 6.6024261	total: 896ms	remaining: 18.2s
47:	learn: 6.5945654	total: 919ms	remaining: 18.2s
48:	learn: 6.5924312	total: 934ms	remaining: 18.1s
49:	learn: 6.5888240	total: 951ms	remaining: 18.1s
50:	learn: 6.5843144	total: 967ms	remaining: 18s
51:	learn: 6.5791705	total: 983ms	remaining: 17.9s
52:	learn: 6.5751877	total: 1000ms	remaining: 17.9s
53:	learn: 6.5734563	total: 1.01s	rema

197:	learn: 6.3407327	total: 3.52s	remaining: 14.2s
198:	learn: 6.3398702	total: 3.53s	remaining: 14.2s
199:	learn: 6.3390844	total: 3.55s	remaining: 14.2s
200:	learn: 6.3382973	total: 3.57s	remaining: 14.2s
201:	learn: 6.3375774	total: 3.59s	remaining: 14.2s
202:	learn: 6.3368935	total: 3.61s	remaining: 14.2s
203:	learn: 6.3361984	total: 3.62s	remaining: 14.1s
204:	learn: 6.3355711	total: 3.64s	remaining: 14.1s
205:	learn: 6.3337069	total: 3.66s	remaining: 14.1s
206:	learn: 6.3330721	total: 3.67s	remaining: 14.1s
207:	learn: 6.3324961	total: 3.69s	remaining: 14s
208:	learn: 6.3307502	total: 3.71s	remaining: 14s
209:	learn: 6.3302354	total: 3.73s	remaining: 14s
210:	learn: 6.3296529	total: 3.74s	remaining: 14s
211:	learn: 6.3280163	total: 3.76s	remaining: 14s
212:	learn: 6.3275442	total: 3.78s	remaining: 14s
213:	learn: 6.3270957	total: 3.8s	remaining: 13.9s
214:	learn: 6.3258627	total: 3.81s	remaining: 13.9s
215:	learn: 6.3254368	total: 3.83s	remaining: 13.9s
216:	learn: 6.3251300	tot

365:	learn: 6.2612285	total: 6.41s	remaining: 11.1s
366:	learn: 6.2609610	total: 6.43s	remaining: 11.1s
367:	learn: 6.2607089	total: 6.44s	remaining: 11.1s
368:	learn: 6.2603821	total: 6.46s	remaining: 11.1s
369:	learn: 6.2601463	total: 6.48s	remaining: 11s
370:	learn: 6.2599124	total: 6.5s	remaining: 11s
371:	learn: 6.2596017	total: 6.52s	remaining: 11s
372:	learn: 6.2591478	total: 6.53s	remaining: 11s
373:	learn: 6.2584466	total: 6.55s	remaining: 11s
374:	learn: 6.2583900	total: 6.57s	remaining: 10.9s
375:	learn: 6.2581632	total: 6.58s	remaining: 10.9s
376:	learn: 6.2575481	total: 6.6s	remaining: 10.9s
377:	learn: 6.2574464	total: 6.62s	remaining: 10.9s
378:	learn: 6.2572456	total: 6.64s	remaining: 10.9s
379:	learn: 6.2570817	total: 6.66s	remaining: 10.9s
380:	learn: 6.2567660	total: 6.68s	remaining: 10.9s
381:	learn: 6.2565747	total: 6.7s	remaining: 10.8s
382:	learn: 6.2564066	total: 6.71s	remaining: 10.8s
383:	learn: 6.2562882	total: 6.73s	remaining: 10.8s
384:	learn: 6.2559944	tot

531:	learn: 6.2273280	total: 9.28s	remaining: 8.16s
532:	learn: 6.2271330	total: 9.29s	remaining: 8.14s
533:	learn: 6.2270718	total: 9.31s	remaining: 8.13s
534:	learn: 6.2269117	total: 9.33s	remaining: 8.11s
535:	learn: 6.2267208	total: 9.35s	remaining: 8.09s
536:	learn: 6.2264547	total: 9.37s	remaining: 8.08s
537:	learn: 6.2263137	total: 9.38s	remaining: 8.06s
538:	learn: 6.2262082	total: 9.4s	remaining: 8.04s
539:	learn: 6.2259570	total: 9.42s	remaining: 8.02s
540:	learn: 6.2258277	total: 9.43s	remaining: 8s
541:	learn: 6.2257346	total: 9.45s	remaining: 7.98s
542:	learn: 6.2256457	total: 9.47s	remaining: 7.97s
543:	learn: 6.2255701	total: 9.48s	remaining: 7.95s
544:	learn: 6.2254852	total: 9.5s	remaining: 7.93s
545:	learn: 6.2254200	total: 9.52s	remaining: 7.92s
546:	learn: 6.2253388	total: 9.54s	remaining: 7.9s
547:	learn: 6.2250380	total: 9.56s	remaining: 7.88s
548:	learn: 6.2249760	total: 9.57s	remaining: 7.86s
549:	learn: 6.2247218	total: 9.59s	remaining: 7.84s
550:	learn: 6.2243

691:	learn: 6.2111553	total: 12.1s	remaining: 5.37s
692:	learn: 6.2111085	total: 12.1s	remaining: 5.36s
693:	learn: 6.2110628	total: 12.1s	remaining: 5.34s
694:	learn: 6.2110170	total: 12.1s	remaining: 5.32s
695:	learn: 6.2109951	total: 12.1s	remaining: 5.3s
696:	learn: 6.2108641	total: 12.2s	remaining: 5.29s
697:	learn: 6.2108551	total: 12.2s	remaining: 5.27s
698:	learn: 6.2108122	total: 12.2s	remaining: 5.25s
699:	learn: 6.2106894	total: 12.2s	remaining: 5.23s
700:	learn: 6.2106486	total: 12.2s	remaining: 5.21s
701:	learn: 6.2105257	total: 12.2s	remaining: 5.2s
702:	learn: 6.2104213	total: 12.3s	remaining: 5.18s
703:	learn: 6.2102992	total: 12.3s	remaining: 5.17s
704:	learn: 6.2102466	total: 12.3s	remaining: 5.15s
705:	learn: 6.2101130	total: 12.3s	remaining: 5.13s
706:	learn: 6.2099602	total: 12.3s	remaining: 5.11s
707:	learn: 6.2099041	total: 12.4s	remaining: 5.09s
708:	learn: 6.2098046	total: 12.4s	remaining: 5.08s
709:	learn: 6.2096685	total: 12.4s	remaining: 5.06s
710:	learn: 6.

857:	learn: 6.2018064	total: 14.9s	remaining: 2.47s
858:	learn: 6.2017277	total: 15s	remaining: 2.45s
859:	learn: 6.2017125	total: 15s	remaining: 2.44s
860:	learn: 6.2016933	total: 15s	remaining: 2.42s
861:	learn: 6.2016188	total: 15s	remaining: 2.4s
862:	learn: 6.2016042	total: 15s	remaining: 2.38s
863:	learn: 6.2015826	total: 15s	remaining: 2.37s
864:	learn: 6.2015641	total: 15.1s	remaining: 2.35s
865:	learn: 6.2015364	total: 15.1s	remaining: 2.33s
866:	learn: 6.2015229	total: 15.1s	remaining: 2.31s
867:	learn: 6.2015121	total: 15.1s	remaining: 2.3s
868:	learn: 6.2014430	total: 15.1s	remaining: 2.28s
869:	learn: 6.2014144	total: 15.1s	remaining: 2.26s
870:	learn: 6.2014059	total: 15.2s	remaining: 2.25s
871:	learn: 6.2013977	total: 15.2s	remaining: 2.23s
872:	learn: 6.2013634	total: 15.2s	remaining: 2.21s
873:	learn: 6.2013222	total: 15.2s	remaining: 2.19s
874:	learn: 6.2012124	total: 15.2s	remaining: 2.18s
875:	learn: 6.2011956	total: 15.3s	remaining: 2.16s
876:	learn: 6.2011843	tota

22:	learn: 7.3267194	total: 443ms	remaining: 18.8s
23:	learn: 7.2852195	total: 462ms	remaining: 18.8s
24:	learn: 7.2472891	total: 482ms	remaining: 18.8s
25:	learn: 7.2160335	total: 502ms	remaining: 18.8s
26:	learn: 7.1877891	total: 523ms	remaining: 18.8s
27:	learn: 7.1609247	total: 550ms	remaining: 19.1s
28:	learn: 7.1388873	total: 569ms	remaining: 19s
29:	learn: 7.1181088	total: 586ms	remaining: 18.9s
30:	learn: 7.0998573	total: 603ms	remaining: 18.9s
31:	learn: 7.0843805	total: 620ms	remaining: 18.8s
32:	learn: 7.0689564	total: 642ms	remaining: 18.8s
33:	learn: 7.0563080	total: 662ms	remaining: 18.8s
34:	learn: 7.0459426	total: 681ms	remaining: 18.8s
35:	learn: 7.0357886	total: 703ms	remaining: 18.8s
36:	learn: 7.0270797	total: 723ms	remaining: 18.8s
37:	learn: 7.0184865	total: 741ms	remaining: 18.8s
38:	learn: 7.0100941	total: 758ms	remaining: 18.7s
39:	learn: 7.0025448	total: 774ms	remaining: 18.6s
40:	learn: 6.9967308	total: 790ms	remaining: 18.5s
41:	learn: 6.9889456	total: 807ms

189:	learn: 6.7633511	total: 3.51s	remaining: 14.9s
190:	learn: 6.7630208	total: 3.52s	remaining: 14.9s
191:	learn: 6.7627106	total: 3.54s	remaining: 14.9s
192:	learn: 6.7619989	total: 3.56s	remaining: 14.9s
193:	learn: 6.7606008	total: 3.58s	remaining: 14.9s
194:	learn: 6.7600654	total: 3.6s	remaining: 14.9s
195:	learn: 6.7586959	total: 3.62s	remaining: 14.8s
196:	learn: 6.7574980	total: 3.63s	remaining: 14.8s
197:	learn: 6.7569910	total: 3.65s	remaining: 14.8s
198:	learn: 6.7567002	total: 3.66s	remaining: 14.7s
199:	learn: 6.7564211	total: 3.68s	remaining: 14.7s
200:	learn: 6.7561532	total: 3.69s	remaining: 14.7s
201:	learn: 6.7549046	total: 3.71s	remaining: 14.7s
202:	learn: 6.7537655	total: 3.73s	remaining: 14.7s
203:	learn: 6.7532591	total: 3.75s	remaining: 14.6s
204:	learn: 6.7531448	total: 3.77s	remaining: 14.6s
205:	learn: 6.7526631	total: 3.79s	remaining: 14.6s
206:	learn: 6.7522046	total: 3.8s	remaining: 14.6s
207:	learn: 6.7515803	total: 3.82s	remaining: 14.5s
208:	learn: 6.

355:	learn: 6.6764132	total: 6.37s	remaining: 11.5s
356:	learn: 6.6754519	total: 6.39s	remaining: 11.5s
357:	learn: 6.6749056	total: 6.41s	remaining: 11.5s
358:	learn: 6.6745738	total: 6.42s	remaining: 11.5s
359:	learn: 6.6742717	total: 6.44s	remaining: 11.5s
360:	learn: 6.6742083	total: 6.46s	remaining: 11.4s
361:	learn: 6.6737166	total: 6.48s	remaining: 11.4s
362:	learn: 6.6735336	total: 6.49s	remaining: 11.4s
363:	learn: 6.6732429	total: 6.51s	remaining: 11.4s
364:	learn: 6.6729467	total: 6.52s	remaining: 11.4s
365:	learn: 6.6728858	total: 6.54s	remaining: 11.3s
366:	learn: 6.6725711	total: 6.56s	remaining: 11.3s
367:	learn: 6.6723021	total: 6.58s	remaining: 11.3s
368:	learn: 6.6722247	total: 6.6s	remaining: 11.3s
369:	learn: 6.6720995	total: 6.61s	remaining: 11.3s
370:	learn: 6.6720252	total: 6.63s	remaining: 11.2s
371:	learn: 6.6714642	total: 6.65s	remaining: 11.2s
372:	learn: 6.6713259	total: 6.67s	remaining: 11.2s
373:	learn: 6.6710970	total: 6.68s	remaining: 11.2s
374:	learn: 6

517:	learn: 6.6378394	total: 10.1s	remaining: 9.39s
518:	learn: 6.6376989	total: 10.1s	remaining: 9.37s
519:	learn: 6.6375037	total: 10.1s	remaining: 9.35s
520:	learn: 6.6374150	total: 10.2s	remaining: 9.33s
521:	learn: 6.6373636	total: 10.2s	remaining: 9.32s
522:	learn: 6.6369812	total: 10.2s	remaining: 9.3s
523:	learn: 6.6369192	total: 10.2s	remaining: 9.28s
524:	learn: 6.6368722	total: 10.2s	remaining: 9.26s
525:	learn: 6.6367243	total: 10.3s	remaining: 9.24s
526:	learn: 6.6366425	total: 10.3s	remaining: 9.22s
527:	learn: 6.6365605	total: 10.3s	remaining: 9.2s
528:	learn: 6.6365030	total: 10.3s	remaining: 9.18s
529:	learn: 6.6363116	total: 10.3s	remaining: 9.16s
530:	learn: 6.6360655	total: 10.4s	remaining: 9.15s
531:	learn: 6.6358906	total: 10.4s	remaining: 9.13s
532:	learn: 6.6358421	total: 10.4s	remaining: 9.11s
533:	learn: 6.6355813	total: 10.4s	remaining: 9.09s
534:	learn: 6.6353497	total: 10.4s	remaining: 9.07s
535:	learn: 6.6351188	total: 10.5s	remaining: 9.05s
536:	learn: 6.

685:	learn: 6.6154557	total: 13.3s	remaining: 6.11s
686:	learn: 6.6154437	total: 13.4s	remaining: 6.09s
687:	learn: 6.6153843	total: 13.4s	remaining: 6.07s
688:	learn: 6.6153435	total: 13.4s	remaining: 6.05s
689:	learn: 6.6152809	total: 13.4s	remaining: 6.03s
690:	learn: 6.6152417	total: 13.4s	remaining: 6.01s
691:	learn: 6.6151677	total: 13.5s	remaining: 5.99s
692:	learn: 6.6151366	total: 13.5s	remaining: 5.97s
693:	learn: 6.6150141	total: 13.5s	remaining: 5.95s
694:	learn: 6.6149771	total: 13.5s	remaining: 5.93s
695:	learn: 6.6149557	total: 13.5s	remaining: 5.92s
696:	learn: 6.6148850	total: 13.6s	remaining: 5.9s
697:	learn: 6.6148563	total: 13.6s	remaining: 5.88s
698:	learn: 6.6148290	total: 13.6s	remaining: 5.86s
699:	learn: 6.6147853	total: 13.6s	remaining: 5.84s
700:	learn: 6.6146766	total: 13.6s	remaining: 5.82s
701:	learn: 6.6145731	total: 13.7s	remaining: 5.8s
702:	learn: 6.6144992	total: 13.7s	remaining: 5.78s
703:	learn: 6.6143385	total: 13.7s	remaining: 5.76s
704:	learn: 6.

845:	learn: 6.6036774	total: 16.4s	remaining: 2.98s
846:	learn: 6.6036554	total: 16.4s	remaining: 2.96s
847:	learn: 6.6036086	total: 16.4s	remaining: 2.95s
848:	learn: 6.6035926	total: 16.5s	remaining: 2.93s
849:	learn: 6.6035299	total: 16.5s	remaining: 2.91s
850:	learn: 6.6034713	total: 16.5s	remaining: 2.89s
851:	learn: 6.6034215	total: 16.5s	remaining: 2.87s
852:	learn: 6.6033579	total: 16.5s	remaining: 2.85s
853:	learn: 6.6033461	total: 16.6s	remaining: 2.83s
854:	learn: 6.6033076	total: 16.6s	remaining: 2.81s
855:	learn: 6.6032935	total: 16.6s	remaining: 2.79s
856:	learn: 6.6031713	total: 16.6s	remaining: 2.77s
857:	learn: 6.6030564	total: 16.6s	remaining: 2.75s
858:	learn: 6.6029457	total: 16.6s	remaining: 2.73s
859:	learn: 6.6028414	total: 16.7s	remaining: 2.71s
860:	learn: 6.6027410	total: 16.7s	remaining: 2.69s
861:	learn: 6.6027120	total: 16.7s	remaining: 2.67s
862:	learn: 6.6026172	total: 16.7s	remaining: 2.65s
863:	learn: 6.6025745	total: 16.7s	remaining: 2.63s
864:	learn: 

9:	learn: 8.9485665	total: 185ms	remaining: 18.3s
10:	learn: 8.7397286	total: 206ms	remaining: 18.5s
11:	learn: 8.5548601	total: 226ms	remaining: 18.6s
12:	learn: 8.3878472	total: 246ms	remaining: 18.7s
13:	learn: 8.2415932	total: 268ms	remaining: 18.9s
14:	learn: 8.1078129	total: 288ms	remaining: 18.9s
15:	learn: 7.9923143	total: 308ms	remaining: 19s
16:	learn: 7.8883077	total: 332ms	remaining: 19.2s
17:	learn: 7.7970100	total: 353ms	remaining: 19.2s
18:	learn: 7.7185154	total: 372ms	remaining: 19.2s
19:	learn: 7.6487051	total: 392ms	remaining: 19.2s
20:	learn: 7.5850514	total: 419ms	remaining: 19.6s
21:	learn: 7.5285890	total: 442ms	remaining: 19.7s
22:	learn: 7.4830104	total: 463ms	remaining: 19.7s
23:	learn: 7.4414389	total: 480ms	remaining: 19.5s
24:	learn: 7.4019707	total: 499ms	remaining: 19.5s
25:	learn: 7.3687845	total: 517ms	remaining: 19.4s
26:	learn: 7.3394569	total: 534ms	remaining: 19.3s
27:	learn: 7.3125639	total: 552ms	remaining: 19.2s
28:	learn: 7.2881353	total: 570ms	

176:	learn: 6.9509369	total: 3.29s	remaining: 15.3s
177:	learn: 6.9503784	total: 3.31s	remaining: 15.3s
178:	learn: 6.9499057	total: 3.33s	remaining: 15.3s
179:	learn: 6.9497319	total: 3.35s	remaining: 15.3s
180:	learn: 6.9492781	total: 3.38s	remaining: 15.3s
181:	learn: 6.9485394	total: 3.4s	remaining: 15.3s
182:	learn: 6.9481039	total: 3.42s	remaining: 15.3s
183:	learn: 6.9477617	total: 3.44s	remaining: 15.3s
184:	learn: 6.9470770	total: 3.46s	remaining: 15.3s
185:	learn: 6.9469214	total: 3.48s	remaining: 15.2s
186:	learn: 6.9467720	total: 3.5s	remaining: 15.2s
187:	learn: 6.9462401	total: 3.53s	remaining: 15.2s
188:	learn: 6.9458295	total: 3.55s	remaining: 15.2s
189:	learn: 6.9454394	total: 3.57s	remaining: 15.2s
190:	learn: 6.9452964	total: 3.59s	remaining: 15.2s
191:	learn: 6.9451592	total: 3.62s	remaining: 15.2s
192:	learn: 6.9447493	total: 3.64s	remaining: 15.2s
193:	learn: 6.9424450	total: 3.66s	remaining: 15.2s
194:	learn: 6.9421298	total: 3.67s	remaining: 15.2s
195:	learn: 6.

343:	learn: 6.8708867	total: 6.39s	remaining: 12.2s
344:	learn: 6.8706818	total: 6.41s	remaining: 12.2s
345:	learn: 6.8701198	total: 6.43s	remaining: 12.1s
346:	learn: 6.8691373	total: 6.45s	remaining: 12.1s
347:	learn: 6.8686980	total: 6.46s	remaining: 12.1s
348:	learn: 6.8686617	total: 6.49s	remaining: 12.1s
349:	learn: 6.8684458	total: 6.51s	remaining: 12.1s
350:	learn: 6.8684336	total: 6.52s	remaining: 12.1s
351:	learn: 6.8682247	total: 6.54s	remaining: 12s
352:	learn: 6.8678384	total: 6.55s	remaining: 12s
353:	learn: 6.8678062	total: 6.57s	remaining: 12s
354:	learn: 6.8673764	total: 6.59s	remaining: 12s
355:	learn: 6.8662810	total: 6.61s	remaining: 12s
356:	learn: 6.8658542	total: 6.63s	remaining: 11.9s
357:	learn: 6.8653997	total: 6.65s	remaining: 11.9s
358:	learn: 6.8651031	total: 6.66s	remaining: 11.9s
359:	learn: 6.8647564	total: 6.68s	remaining: 11.9s
360:	learn: 6.8644221	total: 6.7s	remaining: 11.9s
361:	learn: 6.8641015	total: 6.71s	remaining: 11.8s
362:	learn: 6.8637940	t

509:	learn: 6.8250314	total: 9.5s	remaining: 9.13s
510:	learn: 6.8245339	total: 9.52s	remaining: 9.11s
511:	learn: 6.8244748	total: 9.54s	remaining: 9.09s
512:	learn: 6.8243614	total: 9.56s	remaining: 9.08s
513:	learn: 6.8243427	total: 9.58s	remaining: 9.06s
514:	learn: 6.8243221	total: 9.61s	remaining: 9.04s
515:	learn: 6.8242652	total: 9.62s	remaining: 9.03s
516:	learn: 6.8241183	total: 9.65s	remaining: 9.02s
517:	learn: 6.8240143	total: 9.67s	remaining: 9s
518:	learn: 6.8239483	total: 9.69s	remaining: 8.98s
519:	learn: 6.8238649	total: 9.71s	remaining: 8.96s
520:	learn: 6.8238475	total: 9.73s	remaining: 8.94s
521:	learn: 6.8235218	total: 9.75s	remaining: 8.93s
522:	learn: 6.8232042	total: 9.77s	remaining: 8.91s
523:	learn: 6.8230626	total: 9.79s	remaining: 8.89s
524:	learn: 6.8226055	total: 9.81s	remaining: 8.87s
525:	learn: 6.8225865	total: 9.84s	remaining: 8.87s
526:	learn: 6.8223079	total: 9.85s	remaining: 8.84s
527:	learn: 6.8220583	total: 9.87s	remaining: 8.82s
528:	learn: 6.82

673:	learn: 6.7996676	total: 12.8s	remaining: 6.2s
674:	learn: 6.7996366	total: 12.8s	remaining: 6.18s
675:	learn: 6.7995393	total: 12.8s	remaining: 6.16s
676:	learn: 6.7994463	total: 12.9s	remaining: 6.14s
677:	learn: 6.7993575	total: 12.9s	remaining: 6.12s
678:	learn: 6.7993264	total: 12.9s	remaining: 6.1s
679:	learn: 6.7992416	total: 12.9s	remaining: 6.08s
680:	learn: 6.7991308	total: 12.9s	remaining: 6.06s
681:	learn: 6.7991214	total: 13s	remaining: 6.04s
682:	learn: 6.7990929	total: 13s	remaining: 6.03s
683:	learn: 6.7990825	total: 13s	remaining: 6.01s
684:	learn: 6.7990014	total: 13s	remaining: 6s
685:	learn: 6.7989239	total: 13.1s	remaining: 5.98s
686:	learn: 6.7988372	total: 13.1s	remaining: 5.96s
687:	learn: 6.7987503	total: 13.1s	remaining: 5.94s
688:	learn: 6.7986474	total: 13.1s	remaining: 5.92s
689:	learn: 6.7985616	total: 13.1s	remaining: 5.9s
690:	learn: 6.7985224	total: 13.2s	remaining: 5.88s
691:	learn: 6.7983986	total: 13.2s	remaining: 5.87s
692:	learn: 6.7982979	tota

837:	learn: 6.7885780	total: 16.1s	remaining: 3.1s
838:	learn: 6.7884795	total: 16.1s	remaining: 3.09s
839:	learn: 6.7884369	total: 16.1s	remaining: 3.07s
840:	learn: 6.7883549	total: 16.1s	remaining: 3.05s
841:	learn: 6.7883508	total: 16.1s	remaining: 3.03s
842:	learn: 6.7883246	total: 16.2s	remaining: 3.01s
843:	learn: 6.7881469	total: 16.2s	remaining: 2.99s
844:	learn: 6.7880128	total: 16.2s	remaining: 2.97s
845:	learn: 6.7879994	total: 16.2s	remaining: 2.95s
846:	learn: 6.7879954	total: 16.2s	remaining: 2.93s
847:	learn: 6.7878806	total: 16.3s	remaining: 2.91s
848:	learn: 6.7877563	total: 16.3s	remaining: 2.9s
849:	learn: 6.7877518	total: 16.3s	remaining: 2.88s
850:	learn: 6.7876984	total: 16.3s	remaining: 2.86s
851:	learn: 6.7875360	total: 16.3s	remaining: 2.84s
852:	learn: 6.7875212	total: 16.4s	remaining: 2.82s
853:	learn: 6.7874700	total: 16.4s	remaining: 2.8s
854:	learn: 6.7874063	total: 16.4s	remaining: 2.78s
855:	learn: 6.7873616	total: 16.4s	remaining: 2.76s
856:	learn: 6.7

Learning rate set to 0.073021
0:	learn: 12.4501975	total: 27.4ms	remaining: 27.4s
1:	learn: 11.8849151	total: 48.7ms	remaining: 24.3s
2:	learn: 11.3838036	total: 69.7ms	remaining: 23.2s
3:	learn: 10.9250943	total: 91.1ms	remaining: 22.7s
4:	learn: 10.5021485	total: 121ms	remaining: 24.2s
5:	learn: 10.1255271	total: 155ms	remaining: 25.7s
6:	learn: 9.7888875	total: 185ms	remaining: 26.2s
7:	learn: 9.4836458	total: 207ms	remaining: 25.6s
8:	learn: 9.2045915	total: 230ms	remaining: 25.3s
9:	learn: 8.9531225	total: 253ms	remaining: 25s
10:	learn: 8.7211441	total: 276ms	remaining: 24.8s
11:	learn: 8.5177313	total: 299ms	remaining: 24.6s
12:	learn: 8.3374035	total: 320ms	remaining: 24.3s
13:	learn: 8.1795245	total: 340ms	remaining: 23.9s
14:	learn: 8.0399966	total: 360ms	remaining: 23.7s
15:	learn: 7.9152075	total: 384ms	remaining: 23.6s
16:	learn: 7.8037802	total: 404ms	remaining: 23.3s
17:	learn: 7.7070474	total: 425ms	remaining: 23.2s
18:	learn: 7.6178230	total: 446ms	remaining: 23s
19:	l

165:	learn: 6.7150123	total: 3.3s	remaining: 16.6s
166:	learn: 6.7131275	total: 3.32s	remaining: 16.6s
167:	learn: 6.7128668	total: 3.34s	remaining: 16.5s
168:	learn: 6.7123606	total: 3.36s	remaining: 16.5s
169:	learn: 6.7121093	total: 3.38s	remaining: 16.5s
170:	learn: 6.7110461	total: 3.4s	remaining: 16.5s
171:	learn: 6.7092036	total: 3.41s	remaining: 16.4s
172:	learn: 6.7074951	total: 3.43s	remaining: 16.4s
173:	learn: 6.7072520	total: 3.45s	remaining: 16.4s
174:	learn: 6.7070001	total: 3.46s	remaining: 16.3s
175:	learn: 6.7065077	total: 3.48s	remaining: 16.3s
176:	learn: 6.7055428	total: 3.5s	remaining: 16.3s
177:	learn: 6.7053051	total: 3.52s	remaining: 16.2s
178:	learn: 6.7047984	total: 3.54s	remaining: 16.2s
179:	learn: 6.7039001	total: 3.56s	remaining: 16.2s
180:	learn: 6.7030299	total: 3.57s	remaining: 16.2s
181:	learn: 6.7025722	total: 3.59s	remaining: 16.1s
182:	learn: 6.7021345	total: 3.61s	remaining: 16.1s
183:	learn: 6.7008469	total: 3.62s	remaining: 16.1s
184:	learn: 6.6

333:	learn: 6.6184180	total: 6.33s	remaining: 12.6s
334:	learn: 6.6182646	total: 6.35s	remaining: 12.6s
335:	learn: 6.6182100	total: 6.36s	remaining: 12.6s
336:	learn: 6.6175470	total: 6.38s	remaining: 12.6s
337:	learn: 6.6174004	total: 6.4s	remaining: 12.5s
338:	learn: 6.6170277	total: 6.42s	remaining: 12.5s
339:	learn: 6.6169750	total: 6.44s	remaining: 12.5s
340:	learn: 6.6168350	total: 6.45s	remaining: 12.5s
341:	learn: 6.6165544	total: 6.47s	remaining: 12.4s
342:	learn: 6.6165037	total: 6.49s	remaining: 12.4s
343:	learn: 6.6164407	total: 6.5s	remaining: 12.4s
344:	learn: 6.6163936	total: 6.52s	remaining: 12.4s
345:	learn: 6.6157919	total: 6.54s	remaining: 12.4s
346:	learn: 6.6150840	total: 6.56s	remaining: 12.3s
347:	learn: 6.6144478	total: 6.58s	remaining: 12.3s
348:	learn: 6.6138085	total: 6.6s	remaining: 12.3s
349:	learn: 6.6131486	total: 6.61s	remaining: 12.3s
350:	learn: 6.6126048	total: 6.63s	remaining: 12.3s
351:	learn: 6.6122404	total: 6.64s	remaining: 12.2s
352:	learn: 6.6

492:	learn: 6.5764949	total: 9.2s	remaining: 9.46s
493:	learn: 6.5763483	total: 9.22s	remaining: 9.44s
494:	learn: 6.5763083	total: 9.24s	remaining: 9.42s
495:	learn: 6.5761224	total: 9.26s	remaining: 9.4s
496:	learn: 6.5760839	total: 9.27s	remaining: 9.39s
497:	learn: 6.5757442	total: 9.29s	remaining: 9.37s
498:	learn: 6.5753509	total: 9.31s	remaining: 9.35s
499:	learn: 6.5751017	total: 9.33s	remaining: 9.33s
500:	learn: 6.5746805	total: 9.35s	remaining: 9.31s
501:	learn: 6.5743176	total: 9.36s	remaining: 9.29s
502:	learn: 6.5739167	total: 9.38s	remaining: 9.27s
503:	learn: 6.5738953	total: 9.4s	remaining: 9.26s
504:	learn: 6.5736233	total: 9.42s	remaining: 9.24s
505:	learn: 6.5736026	total: 9.44s	remaining: 9.22s
506:	learn: 6.5732900	total: 9.46s	remaining: 9.2s
507:	learn: 6.5728663	total: 9.48s	remaining: 9.18s
508:	learn: 6.5724704	total: 9.5s	remaining: 9.16s
509:	learn: 6.5722373	total: 9.51s	remaining: 9.14s
510:	learn: 6.5720285	total: 9.53s	remaining: 9.12s
511:	learn: 6.571

657:	learn: 6.5494480	total: 12.5s	remaining: 6.49s
658:	learn: 6.5492456	total: 12.5s	remaining: 6.47s
659:	learn: 6.5490399	total: 12.5s	remaining: 6.45s
660:	learn: 6.5488322	total: 12.5s	remaining: 6.43s
661:	learn: 6.5487909	total: 12.6s	remaining: 6.41s
662:	learn: 6.5487002	total: 12.6s	remaining: 6.39s
663:	learn: 6.5485467	total: 12.6s	remaining: 6.38s
664:	learn: 6.5484668	total: 12.6s	remaining: 6.36s
665:	learn: 6.5482864	total: 12.6s	remaining: 6.34s
666:	learn: 6.5481600	total: 12.7s	remaining: 6.32s
667:	learn: 6.5481203	total: 12.7s	remaining: 6.3s
668:	learn: 6.5480246	total: 12.7s	remaining: 6.28s
669:	learn: 6.5478505	total: 12.7s	remaining: 6.26s
670:	learn: 6.5477193	total: 12.7s	remaining: 6.24s
671:	learn: 6.5476466	total: 12.8s	remaining: 6.22s
672:	learn: 6.5476084	total: 12.8s	remaining: 6.21s
673:	learn: 6.5474862	total: 12.8s	remaining: 6.19s
674:	learn: 6.5474669	total: 12.8s	remaining: 6.17s
675:	learn: 6.5472699	total: 12.8s	remaining: 6.15s
676:	learn: 6

823:	learn: 6.5342161	total: 15.5s	remaining: 3.32s
824:	learn: 6.5341999	total: 15.6s	remaining: 3.3s
825:	learn: 6.5340593	total: 15.6s	remaining: 3.28s
826:	learn: 6.5339527	total: 15.6s	remaining: 3.26s
827:	learn: 6.5338685	total: 15.6s	remaining: 3.24s
828:	learn: 6.5338249	total: 15.6s	remaining: 3.23s
829:	learn: 6.5337142	total: 15.7s	remaining: 3.21s
830:	learn: 6.5336159	total: 15.7s	remaining: 3.19s
831:	learn: 6.5334598	total: 15.7s	remaining: 3.17s
832:	learn: 6.5334258	total: 15.7s	remaining: 3.15s
833:	learn: 6.5332685	total: 15.8s	remaining: 3.14s
834:	learn: 6.5331395	total: 15.8s	remaining: 3.12s
835:	learn: 6.5331322	total: 15.8s	remaining: 3.1s
836:	learn: 6.5330093	total: 15.8s	remaining: 3.08s
837:	learn: 6.5328966	total: 15.8s	remaining: 3.06s
838:	learn: 6.5328545	total: 15.9s	remaining: 3.04s
839:	learn: 6.5327547	total: 15.9s	remaining: 3.02s
840:	learn: 6.5326398	total: 15.9s	remaining: 3s
841:	learn: 6.5325133	total: 15.9s	remaining: 2.99s
842:	learn: 6.532

983:	learn: 6.5249322	total: 18.4s	remaining: 299ms
984:	learn: 6.5248299	total: 18.4s	remaining: 280ms
985:	learn: 6.5247775	total: 18.4s	remaining: 262ms
986:	learn: 6.5247130	total: 18.4s	remaining: 243ms
987:	learn: 6.5247056	total: 18.5s	remaining: 224ms
988:	learn: 6.5246552	total: 18.5s	remaining: 206ms
989:	learn: 6.5246000	total: 18.5s	remaining: 187ms
990:	learn: 6.5245475	total: 18.5s	remaining: 168ms
991:	learn: 6.5244975	total: 18.5s	remaining: 149ms
992:	learn: 6.5244903	total: 18.5s	remaining: 131ms
993:	learn: 6.5244469	total: 18.6s	remaining: 112ms
994:	learn: 6.5243570	total: 18.6s	remaining: 93.4ms
995:	learn: 6.5243223	total: 18.6s	remaining: 74.7ms
996:	learn: 6.5242387	total: 18.6s	remaining: 56ms
997:	learn: 6.5242299	total: 18.6s	remaining: 37.3ms
998:	learn: 6.5241967	total: 18.7s	remaining: 18.7ms
999:	learn: 6.5241650	total: 18.7s	remaining: 0us
Learning rate set to 0.073021
0:	learn: 9.3496638	total: 25.2ms	remaining: 25.2s
1:	learn: 8.9440826	total: 44.5ms	

152:	learn: 5.0108790	total: 2.7s	remaining: 14.9s
153:	learn: 5.0105751	total: 2.72s	remaining: 14.9s
154:	learn: 5.0101666	total: 2.73s	remaining: 14.9s
155:	learn: 5.0097770	total: 2.75s	remaining: 14.9s
156:	learn: 5.0094053	total: 2.77s	remaining: 14.9s
157:	learn: 5.0088106	total: 2.79s	remaining: 14.9s
158:	learn: 5.0082788	total: 2.81s	remaining: 14.8s
159:	learn: 5.0080208	total: 2.82s	remaining: 14.8s
160:	learn: 5.0076851	total: 2.84s	remaining: 14.8s
161:	learn: 5.0061019	total: 2.86s	remaining: 14.8s
162:	learn: 5.0058682	total: 2.87s	remaining: 14.7s
163:	learn: 5.0056439	total: 2.89s	remaining: 14.7s
164:	learn: 5.0053376	total: 2.91s	remaining: 14.7s
165:	learn: 5.0049206	total: 2.93s	remaining: 14.7s
166:	learn: 5.0036193	total: 2.94s	remaining: 14.7s
167:	learn: 5.0033225	total: 2.96s	remaining: 14.7s
168:	learn: 5.0019884	total: 2.98s	remaining: 14.6s
169:	learn: 5.0017782	total: 2.99s	remaining: 14.6s
170:	learn: 5.0015030	total: 3.01s	remaining: 14.6s
171:	learn: 5

318:	learn: 4.9090698	total: 5.53s	remaining: 11.8s
319:	learn: 4.9082584	total: 5.55s	remaining: 11.8s
320:	learn: 4.9076592	total: 5.57s	remaining: 11.8s
321:	learn: 4.9069322	total: 5.58s	remaining: 11.8s
322:	learn: 4.9063358	total: 5.6s	remaining: 11.7s
323:	learn: 4.9056435	total: 5.62s	remaining: 11.7s
324:	learn: 4.9051624	total: 5.64s	remaining: 11.7s
325:	learn: 4.9044624	total: 5.66s	remaining: 11.7s
326:	learn: 4.9038151	total: 5.67s	remaining: 11.7s
327:	learn: 4.9031641	total: 5.69s	remaining: 11.7s
328:	learn: 4.9025081	total: 5.71s	remaining: 11.6s
329:	learn: 4.9021796	total: 5.72s	remaining: 11.6s
330:	learn: 4.9020389	total: 5.74s	remaining: 11.6s
331:	learn: 4.9019877	total: 5.76s	remaining: 11.6s
332:	learn: 4.9017958	total: 5.78s	remaining: 11.6s
333:	learn: 4.9011678	total: 5.8s	remaining: 11.6s
334:	learn: 4.9008517	total: 5.82s	remaining: 11.5s
335:	learn: 4.9002505	total: 5.83s	remaining: 11.5s
336:	learn: 4.9000660	total: 5.85s	remaining: 11.5s
337:	learn: 4.

486:	learn: 4.8526465	total: 8.41s	remaining: 8.86s
487:	learn: 4.8523704	total: 8.43s	remaining: 8.84s
488:	learn: 4.8521940	total: 8.45s	remaining: 8.83s
489:	learn: 4.8518688	total: 8.46s	remaining: 8.81s
490:	learn: 4.8516135	total: 8.48s	remaining: 8.79s
491:	learn: 4.8513874	total: 8.5s	remaining: 8.78s
492:	learn: 4.8509709	total: 8.52s	remaining: 8.76s
493:	learn: 4.8508016	total: 8.53s	remaining: 8.74s
494:	learn: 4.8504151	total: 8.55s	remaining: 8.72s
495:	learn: 4.8503910	total: 8.57s	remaining: 8.71s
496:	learn: 4.8502787	total: 8.59s	remaining: 8.69s
497:	learn: 4.8502158	total: 8.61s	remaining: 8.68s
498:	learn: 4.8498931	total: 8.63s	remaining: 8.66s
499:	learn: 4.8498704	total: 8.64s	remaining: 8.64s
500:	learn: 4.8496264	total: 8.66s	remaining: 8.63s
501:	learn: 4.8492229	total: 8.68s	remaining: 8.61s
502:	learn: 4.8490604	total: 8.7s	remaining: 8.59s
503:	learn: 4.8487538	total: 8.71s	remaining: 8.57s
504:	learn: 4.8482967	total: 8.73s	remaining: 8.55s
505:	learn: 4.

652:	learn: 4.8227317	total: 11.3s	remaining: 5.99s
653:	learn: 4.8224218	total: 11.3s	remaining: 5.97s
654:	learn: 4.8221343	total: 11.3s	remaining: 5.96s
655:	learn: 4.8219170	total: 11.3s	remaining: 5.94s
656:	learn: 4.8216841	total: 11.3s	remaining: 5.92s
657:	learn: 4.8216237	total: 11.4s	remaining: 5.91s
658:	learn: 4.8214644	total: 11.4s	remaining: 5.89s
659:	learn: 4.8213762	total: 11.4s	remaining: 5.87s
660:	learn: 4.8211709	total: 11.4s	remaining: 5.85s
661:	learn: 4.8210372	total: 11.4s	remaining: 5.83s
662:	learn: 4.8209767	total: 11.4s	remaining: 5.82s
663:	learn: 4.8209651	total: 11.5s	remaining: 5.8s
664:	learn: 4.8208026	total: 11.5s	remaining: 5.78s
665:	learn: 4.8206322	total: 11.5s	remaining: 5.76s
666:	learn: 4.8204534	total: 11.5s	remaining: 5.75s
667:	learn: 4.8201965	total: 11.5s	remaining: 5.73s
668:	learn: 4.8200558	total: 11.6s	remaining: 5.72s
669:	learn: 4.8200446	total: 11.6s	remaining: 5.7s
670:	learn: 4.8199826	total: 11.6s	remaining: 5.68s
671:	learn: 4.

815:	learn: 4.8041563	total: 14.1s	remaining: 3.19s
816:	learn: 4.8040762	total: 14.1s	remaining: 3.17s
817:	learn: 4.8040191	total: 14.2s	remaining: 3.15s
818:	learn: 4.8039791	total: 14.2s	remaining: 3.13s
819:	learn: 4.8039586	total: 14.2s	remaining: 3.12s
820:	learn: 4.8038825	total: 14.2s	remaining: 3.1s
821:	learn: 4.8038280	total: 14.2s	remaining: 3.08s
822:	learn: 4.8037761	total: 14.3s	remaining: 3.07s
823:	learn: 4.8036940	total: 14.3s	remaining: 3.05s
824:	learn: 4.8035814	total: 14.3s	remaining: 3.03s
825:	learn: 4.8035318	total: 14.3s	remaining: 3.01s
826:	learn: 4.8034977	total: 14.3s	remaining: 3s
827:	learn: 4.8033904	total: 14.3s	remaining: 2.98s
828:	learn: 4.8032963	total: 14.4s	remaining: 2.96s
829:	learn: 4.8032255	total: 14.4s	remaining: 2.94s
830:	learn: 4.8032063	total: 14.4s	remaining: 2.93s
831:	learn: 4.8031739	total: 14.4s	remaining: 2.91s
832:	learn: 4.8031274	total: 14.4s	remaining: 2.89s
833:	learn: 4.8030595	total: 14.4s	remaining: 2.87s
834:	learn: 4.80

982:	learn: 4.7952386	total: 17s	remaining: 294ms
983:	learn: 4.7951821	total: 17s	remaining: 277ms
984:	learn: 4.7951278	total: 17s	remaining: 259ms
985:	learn: 4.7950446	total: 17.1s	remaining: 242ms
986:	learn: 4.7949981	total: 17.1s	remaining: 225ms
987:	learn: 4.7949449	total: 17.1s	remaining: 208ms
988:	learn: 4.7948937	total: 17.1s	remaining: 190ms
989:	learn: 4.7948752	total: 17.1s	remaining: 173ms
990:	learn: 4.7948632	total: 17.1s	remaining: 156ms
991:	learn: 4.7948536	total: 17.2s	remaining: 138ms
992:	learn: 4.7948272	total: 17.2s	remaining: 121ms
993:	learn: 4.7948184	total: 17.2s	remaining: 104ms
994:	learn: 4.7947931	total: 17.2s	remaining: 86.5ms
995:	learn: 4.7947454	total: 17.2s	remaining: 69.2ms
996:	learn: 4.7947053	total: 17.3s	remaining: 51.9ms
997:	learn: 4.7946840	total: 17.3s	remaining: 34.6ms
998:	learn: 4.7946767	total: 17.3s	remaining: 17.3ms
999:	learn: 4.7946563	total: 17.3s	remaining: 0us


Verificando o desempenho dos modelos segundo às métricas :

In [107]:
(pd.DataFrame({'MAE' : scores_MAE , 'MSE' : scores_MSE , 'R²' : scores_R2} , index = nome_modelos)).sort_values(by = 'MAE')

MAE        MSE        R²
LGBM               3.277265  52.090186  0.535116
Gradient Boosting  3.287891  54.111251  0.522423
Random Forest      3.309458  55.136831  0.520149
CatBoost           3.317141  58.243490  0.497389
XGB                3.336575  60.790793  0.482784
Decision Tree      3.337105  60.146558  0.486510
KNN                3.338724  57.360443  0.490462
Linear Regression  3.750121  51.306298  0.485538
ADA Boost          3.941128  58.935967  0.465221

O modelo que possui as melhores métricas é o LGBM ! Era de se esperar, pois encontramos o conjunto ótimo de features para esse modelo !

Mas veja que vários outros modelos desempenham próximo do LGBM !

Estamos conseguindo um MAE de ~ 3.28 em dados não vistos durante o treinamento do modelo ! Isso é ótimo e indica que o erro que devemos esperar ao tentarmos prever a quantidade de leads de um anúncio é de aproximadamente 3, ou seja, em média erramos para mais ou para menos em 3 anúncios.

## 4.3 Gerando Previsões em um Conjunto de Teste

Vamos criar um conjunto de treino e um de teste para podermos comparar nossas previsões com os valores reais.

In [112]:
# Criando um conjunto de treino e um de teste na mesma proporção da cross-validation a cima

X_train, X_test , y_train, y_test = train_test_split(X, y, test_size = 0.2 , random_state = 123)

In [109]:
# Instanciando, treinando e fazendo previsões

model = LGBMRegressor()

model.fit(X_train, y_train)

previsões = model.predict(X_test)

In [110]:
mean_absolute_error(y_test , previsões)

3.140539509291439

Veja que o erro absoluto médio está em linha com o da validação !

In [111]:
# Comparando valores reais com as previsões

print(pd.DataFrame({'N° verdadeiro de leads' : y_test ,  'Previsões' : previsões}).to_string())

      N° verdadeiro de leads   Previsões
0                          1   10.271232
1                          1    4.484124
2                          0    1.972642
3                          4    3.394380
4                          8    8.318844
5                          1    1.972642
6                          1    1.377064
7                          1    0.861132
8                         32   11.501408
9                          4    1.752205
10                         0    1.377064
11                         0   19.463648
12                         8    2.371246
13                         0    3.394380
14                         1    1.752205
15                         1    1.377064
16                         0    0.861132
17                         1   10.271232
18                         1    1.065462
19                         1    1.196667
20                         0    2.371246
21                         1    1.972642
22                         4    1.752205
23              

Nosso modelo está bom !

## 4.4 Otimização de Hiperparâmetros com GridSearchCV

In [113]:
# Criando a grade

grid_params = {'n_estimators' : [100, 200, 300, 400, 500, 750] , 'learning_rate' : [0.01 , 0.1 , 0.2 , 0.3] ,
               'max_depth' : [2 , 3, 4, 5]}

In [114]:
# Instanciando

gs = GridSearchCV(LGBMRegressor() , grid_params , cv = 5 , scoring = 'neg_mean_absolute_error')

In [115]:
# Treinando... essa célula demora um pouco pra rodar

gs.fit(X, y)

GridSearchCV(cv=5, estimator=LGBMRegressor(),
             param_grid={'learning_rate': [0.01, 0.1, 0.2, 0.3],
                         'max_depth': [2, 3, 4, 5],
                         'n_estimators': [100, 200, 300, 400, 500, 750]},
             scoring='neg_mean_absolute_error')

In [116]:
# Descobrindo o melhor score obtido

- gs.best_score_

3.2688013296505725

Conseguimos melhorar um pouquinho nosso MAE que foi de 3.2772 para 3.2688 .

In [117]:
# Descobrindo os parâmetros que conduzem ao melhor score

gs.best_params_

{'learning_rate': 0.1, 'max_depth': 2, 'n_estimators': 300}

## 4.5 Conclusão

Concluímos que o melhor modelo é um **LGBMRegressor** treinado apenas na feature **"cliques_telefone*"** com os seguintes hiperparâmetros :

- n_estimators = 300

- learning_rate = 0.1

- max_depth = 2

Ao prevermos com esse modelo em dados não vistos durante o treinamento devemos esperar um erro médio no número de Leads de um anúncio de ~ 3,2688 leads.

Se quisermos prever um número inteiro de leads basta utilizarmos a função round() para aproximarmos nossas previsões para o inteiro mais próximo.

In [118]:
model = LGBMRegressor(learning_rate = 0.1, max_depth = 2, n_estimators = 300)
model.fit(X, y)
pred = model.predict(X)

In [119]:
# MAE no conjunto de treino

mean_absolute_error(y , pred)

3.0594373706567173

In [120]:
# MAE no conjunto de treino ao gerarmos números inteiros como previsões

previsões_inteiras = []

for previsão in pred :
    previsões_inteiras.append(round(previsão))
    

mean_absolute_error(y , previsões_inteiras)

3.004705737300674

Gerando previsões inteiras nosso score parece melhorar ainda mais !

# <center>5. Parte 2 - Modelo para determinar se um Anúncio receberá um Lead<center>

## 5.1 - Considerações Iniciais

In [121]:
# Observando o percentual de modelos que recebem pelo menos 1 lead

(sum(df['leads'] > 0)/df['leads'].count())*100

78.15017261219793

Criar um modelo com acurácia elevada não é muito difícil: Basta pensar em um modelo que prevê que todo anúncio receberá pelo menos um Lead. Como visto a cima esse modelo terá 78,15 % de acurácia, porém não conseguirá identificar corretamente nenhum dos anúncios que não recebem nenhum lead.

Sendo assim vou propor um modelo com foco em identificar corretamente o que chamaremos de **anúncios fracos, ou seja, anúncios que não recebem nenhum lead**. Assim focaremos em otimizar a métrica **Recall que mede a habilidade de um classificador em encontrar todas as amostras positivas**.

A maioria dos modelos treinados no dataset inteiro acabará "entendendo" que é melhor prever que um anúncio sempre recebe leads devido ao dataset estar fortemente desbalanceado quanto ao fato de um anúncio receber ou não um lead. Qualquer modelo terá bastante dificuldade em classificar corretamente os anúncios que não recebem leads. 

Para combater essa dificuldade precisaremos balancear as classes e para isso utilizaremos **Oversampling** que consiste em tomarmos amostras aleatórias da classe minoritária e unirmos aos dados disponíveis até que tenhamos o mesmo número de representantes em cada classe.

In [122]:
# Criando a variável Anúncio_Fraco que recebe 1 se o anúncio não recebe nenhum lead (Anúncio Fraco) e 0 caso contrário

target = []

for n_leads in df['leads'] :
    if n_leads > 0 :
        target.append(0)
    else :
        target.append(1)

df['Anúncio_Fraco'] = target

In [123]:
# Percentual de anúncios fracos

(df['Anúncio_Fraco'].mean())*100

21.84982738780207

## 5.2 Oversampling

Primeiramente vamos criar nossos conjuntos de treino e teste :

In [124]:
X = np.array(df[features])

y = np.array(df['Anúncio_Fraco'])

X_train , X_test , y_train , y_test = train_test_split(X, y , test_size = 0.2 , random_state = 90)

Vamos realizar Oversampling no conjunto de treino para balancearmos as classes, mas vamos manter o conjunto de teste desbalanceado, pois precisamos medir a performance dos nossos modelos em dados desbalanceados.

In [125]:
# Instanciando o método

ros = RandomOverSampler(sampling_strategy = 'minority')

In [126]:
X_res , y_res = ros.fit_resample(X_train , y_train)

In [127]:
# Observando quantas amostras da classe majoritária temos em y_train

sum(y_train == 0)

30403

Portanto após o oversampling devemos ter 2x30403 = 60806 amostras.

In [128]:
# Conferindo

X_res.shape[0] , y_res.shape[0]

(60806, 60806)

Tudo correto !

In [129]:
# Conferindo também se temos o mesmo número de representantes em cada classe

sum(y_res == 0) == sum(y_res == 1)

True

## 5.3 Medindo a Performance pós Oversampling

In [130]:
# Modelos

modelos = [LGBMClassifier() , KNeighborsClassifier() , DecisionTreeClassifier(),
          RandomForestClassifier() , AdaBoostClassifier(), GradientBoostingClassifier(), 
          XGBClassifier(use_label_encoder = False),
          CatBoostClassifier()]

In [131]:
# Nome dos modelos

nome_modelos = ['LGBM' , 'KNN' , 'Decision Tree' , 'Random Forest' , 'ADA Boost',
               'Gradient Boosting' , 'XGB' , 'CatBoost']

Calculando Accuracy , Precision , Recall e F1 para vários modelos :

In [132]:
# Essa célula demora um pouco pra rodar... São treinados 8 modelos em um conjunto com mais dados que antes

acc = []
precision = []
recall = []
f1 = []

for model in modelos :
    model.fit(X_res  , y_res)
    pred = model.predict(X_test)
    acc.append(accuracy_score(y_test , pred))
    precision.append(precision_score(y_test , pred))
    recall.append(recall_score(y_test , pred))
    f1.append(f1_score(y_test , pred))

[10:50:17] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Learning rate set to 0.059522
0:	learn: 0.6897294	total: 78.8ms	remaining: 1m 18s
1:	learn: 0.6868005	total: 149ms	remaining: 1m 14s
2:	learn: 0.6845945	total: 239ms	remaining: 1m 19s
3:	learn: 0.6819886	total: 338ms	remaining: 1m 24s
4:	learn: 0.6796669	total: 402ms	remaining: 1m 20s
5:	learn: 0.6774867	total: 481ms	remaining: 1m 19s
6:	learn: 0.6755004	total: 567ms	remaining: 1m 20s
7:	learn: 0.6742274	total: 648ms	remaining: 1m 20s
8:	learn: 0.6728501	total: 736ms	remaining: 1m 21s
9:	learn: 0.6715769	total: 825ms	remaining: 1m 21s
10:	learn: 0.6704719	total: 937ms	remaining: 1m 24s
11:	learn: 0.6694120	total: 1.06s	remaining: 1m 27s
12:	learn: 0.6683997	total: 1.14s	remaining: 1m 26s
13:	learn: 0.6675925	total: 1.23s	remaining: 1m 26s

155:	learn: 0.6336921	total: 12.3s	remaining: 1m 6s
156:	learn: 0.6335280	total: 12.4s	remaining: 1m 6s
157:	learn: 0.6333668	total: 12.4s	remaining: 1m 6s
158:	learn: 0.6332372	total: 12.5s	remaining: 1m 6s
159:	learn: 0.6330528	total: 12.6s	remaining: 1m 6s
160:	learn: 0.6328133	total: 12.7s	remaining: 1m 5s
161:	learn: 0.6327335	total: 12.7s	remaining: 1m 5s
162:	learn: 0.6325465	total: 12.8s	remaining: 1m 5s
163:	learn: 0.6322914	total: 12.9s	remaining: 1m 5s
164:	learn: 0.6321780	total: 13s	remaining: 1m 5s
165:	learn: 0.6319875	total: 13s	remaining: 1m 5s
166:	learn: 0.6319184	total: 13.1s	remaining: 1m 5s
167:	learn: 0.6318230	total: 13.2s	remaining: 1m 5s
168:	learn: 0.6316005	total: 13.2s	remaining: 1m 5s
169:	learn: 0.6314496	total: 13.3s	remaining: 1m 4s
170:	learn: 0.6312555	total: 13.4s	remaining: 1m 4s
171:	learn: 0.6310710	total: 13.4s	remaining: 1m 4s
172:	learn: 0.6309045	total: 13.5s	remaining: 1m 4s
173:	learn: 0.6306725	total: 13.6s	remaining: 1m 4s
174:	learn: 0.63

315:	learn: 0.6046563	total: 24.2s	remaining: 52.4s
316:	learn: 0.6044958	total: 24.3s	remaining: 52.3s
317:	learn: 0.6043838	total: 24.4s	remaining: 52.2s
318:	learn: 0.6041799	total: 24.4s	remaining: 52.2s
319:	learn: 0.6039770	total: 24.5s	remaining: 52.1s
320:	learn: 0.6038398	total: 24.6s	remaining: 52s
321:	learn: 0.6036517	total: 24.7s	remaining: 51.9s
322:	learn: 0.6033939	total: 24.7s	remaining: 51.9s
323:	learn: 0.6031977	total: 24.8s	remaining: 51.8s
324:	learn: 0.6029306	total: 24.9s	remaining: 51.7s
325:	learn: 0.6027295	total: 25s	remaining: 51.6s
326:	learn: 0.6025222	total: 25s	remaining: 51.5s
327:	learn: 0.6022869	total: 25.1s	remaining: 51.4s
328:	learn: 0.6021561	total: 25.2s	remaining: 51.4s
329:	learn: 0.6020591	total: 25.3s	remaining: 51.3s
330:	learn: 0.6018822	total: 25.3s	remaining: 51.2s
331:	learn: 0.6016267	total: 25.4s	remaining: 51.1s
332:	learn: 0.6014520	total: 25.5s	remaining: 51.1s
333:	learn: 0.6013829	total: 25.6s	remaining: 51s
334:	learn: 0.601185

476:	learn: 0.5786454	total: 36.5s	remaining: 40s
477:	learn: 0.5784903	total: 36.6s	remaining: 39.9s
478:	learn: 0.5783638	total: 36.6s	remaining: 39.8s
479:	learn: 0.5782262	total: 36.7s	remaining: 39.8s
480:	learn: 0.5780067	total: 36.8s	remaining: 39.7s
481:	learn: 0.5778530	total: 36.9s	remaining: 39.6s
482:	learn: 0.5777240	total: 36.9s	remaining: 39.5s
483:	learn: 0.5776220	total: 37s	remaining: 39.5s
484:	learn: 0.5774820	total: 37.1s	remaining: 39.4s
485:	learn: 0.5773644	total: 37.1s	remaining: 39.3s
486:	learn: 0.5771893	total: 37.2s	remaining: 39.2s
487:	learn: 0.5769847	total: 37.3s	remaining: 39.1s
488:	learn: 0.5768041	total: 37.4s	remaining: 39.1s
489:	learn: 0.5766631	total: 37.5s	remaining: 39s
490:	learn: 0.5764592	total: 37.5s	remaining: 38.9s
491:	learn: 0.5763496	total: 37.6s	remaining: 38.8s
492:	learn: 0.5762087	total: 37.7s	remaining: 38.8s
493:	learn: 0.5760302	total: 37.7s	remaining: 38.7s
494:	learn: 0.5758785	total: 37.8s	remaining: 38.6s
495:	learn: 0.5757

637:	learn: 0.5556529	total: 48.5s	remaining: 27.5s
638:	learn: 0.5555363	total: 48.6s	remaining: 27.4s
639:	learn: 0.5554543	total: 48.6s	remaining: 27.4s
640:	learn: 0.5553124	total: 48.7s	remaining: 27.3s
641:	learn: 0.5551807	total: 48.8s	remaining: 27.2s
642:	learn: 0.5550452	total: 48.9s	remaining: 27.1s
643:	learn: 0.5548539	total: 48.9s	remaining: 27s
644:	learn: 0.5547159	total: 49s	remaining: 27s
645:	learn: 0.5546592	total: 49.1s	remaining: 26.9s
646:	learn: 0.5545709	total: 49.1s	remaining: 26.8s
647:	learn: 0.5544249	total: 49.2s	remaining: 26.7s
648:	learn: 0.5543352	total: 49.3s	remaining: 26.7s
649:	learn: 0.5542415	total: 49.4s	remaining: 26.6s
650:	learn: 0.5541152	total: 49.5s	remaining: 26.5s
651:	learn: 0.5539387	total: 49.5s	remaining: 26.4s
652:	learn: 0.5537902	total: 49.6s	remaining: 26.4s
653:	learn: 0.5536931	total: 49.7s	remaining: 26.3s
654:	learn: 0.5535707	total: 49.7s	remaining: 26.2s
655:	learn: 0.5534677	total: 49.8s	remaining: 26.1s
656:	learn: 0.5533

798:	learn: 0.5350419	total: 1m	remaining: 15.3s
799:	learn: 0.5348738	total: 1m	remaining: 15.2s
800:	learn: 0.5347309	total: 1m	remaining: 15.1s
801:	learn: 0.5346052	total: 1m	remaining: 15s
802:	learn: 0.5345168	total: 1m	remaining: 14.9s
803:	learn: 0.5344269	total: 1m 1s	remaining: 14.9s
804:	learn: 0.5343469	total: 1m 1s	remaining: 14.8s
805:	learn: 0.5341931	total: 1m 1s	remaining: 14.7s
806:	learn: 0.5340469	total: 1m 1s	remaining: 14.6s
807:	learn: 0.5338920	total: 1m 1s	remaining: 14.6s
808:	learn: 0.5337604	total: 1m 1s	remaining: 14.5s
809:	learn: 0.5336486	total: 1m 1s	remaining: 14.4s
810:	learn: 0.5335417	total: 1m 1s	remaining: 14.3s
811:	learn: 0.5334477	total: 1m 1s	remaining: 14.3s
812:	learn: 0.5333414	total: 1m 1s	remaining: 14.2s
813:	learn: 0.5332058	total: 1m 1s	remaining: 14.1s
814:	learn: 0.5331063	total: 1m 1s	remaining: 14s
815:	learn: 0.5330112	total: 1m 1s	remaining: 14s
816:	learn: 0.5329028	total: 1m 1s	remaining: 13.9s
817:	learn: 0.5328165	total: 1m 2

956:	learn: 0.5164486	total: 1m 12s	remaining: 3.27s
957:	learn: 0.5163141	total: 1m 12s	remaining: 3.19s
958:	learn: 0.5162106	total: 1m 12s	remaining: 3.12s
959:	learn: 0.5161100	total: 1m 12s	remaining: 3.04s
960:	learn: 0.5160401	total: 1m 13s	remaining: 2.96s
961:	learn: 0.5159016	total: 1m 13s	remaining: 2.89s
962:	learn: 0.5157327	total: 1m 13s	remaining: 2.81s
963:	learn: 0.5156401	total: 1m 13s	remaining: 2.73s
964:	learn: 0.5155592	total: 1m 13s	remaining: 2.66s
965:	learn: 0.5154523	total: 1m 13s	remaining: 2.58s
966:	learn: 0.5152771	total: 1m 13s	remaining: 2.51s
967:	learn: 0.5152052	total: 1m 13s	remaining: 2.43s
968:	learn: 0.5150968	total: 1m 13s	remaining: 2.35s
969:	learn: 0.5149831	total: 1m 13s	remaining: 2.28s
970:	learn: 0.5148529	total: 1m 13s	remaining: 2.2s
971:	learn: 0.5147006	total: 1m 13s	remaining: 2.13s
972:	learn: 0.5145685	total: 1m 13s	remaining: 2.05s
973:	learn: 0.5144866	total: 1m 13s	remaining: 1.97s
974:	learn: 0.5143491	total: 1m 14s	remaining: 

In [133]:
# Exibindo os resultados obtidos

pd.DataFrame({'Recall' : recall , 'Acurácia' : acc , 'Precision' : precision , 'F1' : f1}, index = nome_modelos).sort_values(
by = 'Recall' , ascending = False)

Recall  Acurácia  Precision        F1
Gradient Boosting  0.749169  0.487722   0.261309  0.387469
ADA Boost          0.709739  0.508579   0.263678  0.384506
LGBM               0.638480  0.527895   0.259560  0.369079
CatBoost           0.487411  0.600534   0.267536  0.345455
KNN                0.467458  0.548752   0.231257  0.309434
XGB                0.467458  0.591185   0.256117  0.330923
Decision Tree      0.248931  0.671016   0.244289  0.246588
Random Forest      0.029454  0.775609   0.305419  0.053726

**Agora é tudo uma questão de objetivo do nosso modelo**. Por exemplo, **se o objetivo for ter o maior número de acertos quanto a um anúncio receber ou não Leads o melhor modelo seria o de maior acurácia que nesse caso é o Random Forest**. Porém, nesse caso não estaríamos nos preocupando em identificar corretamente os anúncios que não recebem leads já que o recall do RF é baixíssimo. Por outro lado, **o Gradient Boosting classifica corretamente 74,92 % dos anúncios fracos , mas classifica somente aproximadamente 48,77 % do total de anúncios corretamente**.

**Como acredito ser importantíssimo identificar quem são os anúncios que não recebem leads acabo optando pelo Gradient Boosting ainda que esse tenha apenas 50 % de acurácia**. Não existem muitos problemas quanto ao modelo classificar errôneamente anúncios fortes, porém deixando de detectar os anúncios fracos a empresa não poderia explicar para seus clientes como proceder para não montar um anúncio fraco.

## 5.4 Feature Selection 

In [134]:
# Treinando um Gradient Boosting

model = GradientBoostingClassifier()
model.fit(X_res  , y_res)
pred = model.predict(X_test)

In [135]:
# Obtendo a importância das Features

imps = model.feature_importances_

In [136]:
pd.DataFrame({'Feature' : features , '% de Importância' : imps}).sort_values(by = '% de Importância' , ascending = False)

Feature  % de Importância
5                         cliques_telefone*          0.613711
10                                 cep_2dig          0.088418
0                               cod_anuncio          0.043763
1                               cod_cliente          0.038147
13                               km_veiculo          0.029374
..                                      ...               ...
47                              gas natural          0.000000
50                      gasolina e eletrico          0.000000
51                   gasolina e gas natural          0.000000
53  gasolina, alcool, gas natural e benzina          0.000000
81                                       TO          0.000000

[82 rows x 2 columns]

Novamente a feature mais importante para o modelo é "cliques_telefone*" . Será que se treinarmos um GradientBoosting nas duas features mais importantes (juntas reúnem pouco mais 70% da importância total) teremos um melhor recall ? É o que vamos verificar abaixo :

In [137]:
# Treinando e obtendo as métricas

model = GradientBoostingClassifier()
model.fit(X_res[: , [5, 10]] , y_res)
pred = model.predict(X_test[: , [5,10]])
acurácia = accuracy_score(y_test, pred)
precisão = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)

In [138]:
pd.DataFrame({'Recall' :[recall], 'Acurácia' : [acurácia] , 'Precisão' : [precisão] , 'F1' : [f1]})

Recall  Acurácia  Precisão       F1
0  0.811401   0.45392  0.257772  0.39125

A acurácia diminui um pouco, mas conseguimos obter 81,14 % de recall !

Proponho então o uso do seguinte modelo :

**Gradient Boosting treinado nas features "cliques_telefone*" e "cep_2dig"**

Observação : O modelo entrega ~ 81 % de recall, ou seja, classifica anúncios fracos corretamente em 81 % dos casos apesar de ter uma acurácia de 45,39%. Cumpre bem o papel de achar quem são os anúncios fracos.

## 5.5 O que poderia nos levar a conclusões melhores ?

O grande problema do dataset em questão é que ele é desbalanceado, ou seja, a quantidade de anúncios em que houve pelo menos 1 lead é muito maior do que a quantidade de anúncios em que não houve nenhum lead. A proporção é de aproximadamente 4 : 1 . Para termos modelos melhores precisaríamos de mais amostras referentes a anúncios que não tiveram nenhum lead, pois assim conseguiriamos balancear mais os dados e o modelo conseguiria aprender a distinguir as duas classes ao invés de prever sempre 0. A distribuição dos anúncios dificulta o treinamento dos modelos, pois eles tendem a "entender" que é melhor prever que sempre há pelo menos um lead afinal um modelo que prevê isso obtém alta acurácia (~ 80%).

A técnica Oversampling permite que consigamos contornar um pouco isso e classificar corretamente um número maior de anúncios fracos, mas ela tem o preço de diminuir a acurácia dos nossos modelos. Além disso, durante o Oversampling inserimos amostras da classe minoritária, porém essas amostras não são distintas das já existentes e assim temos uma série de amostras repetidas a fim de igualar a quantidade de elementos da mesma classe. Isso pode levar ao overfitting uma vez que o modelo vê o mesmo exemplo mais de uma vez e, por isso, pode simplesmente memorizar o conjunto de treino e não conseguir generalizar para dados não vistos durante o treinamento.